### ISSUE TITLE
[Investigation] AppVeyor & Travis are failed

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#110]

**Comment by hishamco** [comment]
Travis seems got fixed after @troydai commit https://github.com/aspnet/Localization/commit/e40f89174edada331a80cc71f9c9d5d7306aa2ee

**Comment by troydai** [comment]
@hishamco thanks for the validation. I'll close this bug now.

**Comment by hishamco** [comment]
@troydai but the AppVoyer is still :smile:

**Comment by troydai** [comment]
Hum? I passed when I made the fix. I reopen this anyway.

**Comment by hishamco** [comment]
it's fifty fifty :smile:

**Comment by kirthik** [comment]
AppVeyor build is passing - https://ci.appveyor.com/project/aspnetci/localization-r5928 
@hishamco - where did you see the build fail?

**Comment by hishamco** [comment]
Have a look to this https://ci.appveyor.com/project/aspnetci/Localization/branch/dev

**Comment by kirthik** [comment]
@hishamco - the link you sent has a check in from 6 months ago. Closing this bug since AppVeyor build passes against latest check in.

**Comment by hishamco** [comment]
Ya I know, but i'm not sure why AppVoyer build is failing in Localization repo?
