### ISSUE TITLE
Fall back to parent cultures from the supported list when the desired culture is not available or known

### ISSUE THREAD

**Issue by Eilon** [aspnet/Localization#112]
Have loc selectors fall back to parent cultures from the supported list when the desired culture is not available or known. E.g. if the request culture is “en-Damian” and the supported cultures has “en”, then fall back to that.

**Comment by hishamco** [comment]
What if the supported cultures have "en-US" should fallback to that or return ```null```?

**Comment by Eilon** [comment]
@hishamco that depends on what the supported cultures are *and* on what the *requested* culture is. Can you give a more complete example?

BTW, either way we don't plan on doing this work item now - it's on the Backlog.

**Comment by miloush** [comment]
@hishamco `null` would be the current behavior in .NET resources fallback and there might be sensitive cases where you don't want to mix it up. I agree that fallback to the parent culture is an important feature, though, and probably provider specific (if you set the cookie, set something you don't need fallback for).

**Comment by DamianEdwards** [comment]
Going to make this depth-first instead so re-opening.
