### ISSUE TITLE
Localization not working in Controller (VS)

### ISSUE THREAD

**Issue by damienbod** [aspnet/Localization#115]
I'm trying to use localization inside a controller of a MVC 6 controller. The localization always returns the default value, no matter what culture is sent.

http://localhost:13572/api/about

Accept: text/html, application/xhtml+xml, */*
Accept-Language: de-CH;
Host: localhost:13572

Code: https://github.com/damienbod/AspNet5Localization

Any ideas what's going wrong?

Greetings Damien

**Comment by hishamco** [comment]
@damienbod can you try to pass the culture in QueryString, probably it's the default culture in your browser languages options

**Comment by damienbod** [comment]
Hi hishamco
Thanks for your answer. 
I test with fiddler, IE, and Firefox with different default cultures. The Accept-Language header is set to de-CH; which is the header used for this. 

Greetings Damien

**Comment by BenjiZombie** [comment]
Try with ?culture=de-CH at the end of your URL

**Comment by hishamco** [comment]
You can change it from Internet Options, anyhow try what I told you before (which the same that @BenjiZombie mentioned before), or run the Sample that included in the localization repo, I'm sure it will work as expected :smile:

**Comment by damienbod** [comment]
@BenjiZombie 
Thanks for your answer, doesn't work
GET http://localhost:5000/api/about/?culture=de-CH HTTP/1.1
User-Agent: Fiddler
Host: localhost:5000
Accept-Language: de-CH;q=0.9,de;

-------
HTTP/1.1 200 OK
Date: Sun, 18 Oct 2015 17:50:41 GMT
Content-Type: text/plain; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

Name en-GB

-----------

Greetings Damien

**Comment by damienbod** [comment]
@hishamco I tried it, and it doesn't work

The example does not use the localization in the controller.

Greetings Damien

**Comment by hishamco** [comment]
No no, change the QueryString to another culture, for example  http://localhost:5000/api/about/?culture=fr-FR

**Comment by damienbod** [comment]
http://localhost:13572/api/about/?culture=fr-FR

Still the same result

Greetings Damien

**Comment by hishamco** [comment]
Strange!! let me dig into your code

**Comment by damienbod** [comment]
Thanks

**Comment by kirthik** [comment]
@damienbod - are you running from VS or command line?

**Comment by damienbod** [comment]
Hi @kirthik 

both

Greetings Damien

**Comment by hishamco** [comment]
@damienbod **en-US** show up in my end

**Comment by damienbod** [comment]
Hi @hishamco 
Thanks for your feedback.

Stills not working at my side, my default culture is en-US, if I set the query string nothing changes, maybe I need to installed something, or the something is missing from my packages.

You tested with my code and everything runs on your computer?

Greetings Damien

**Comment by damienbod** [comment]
Hi @hishamco @kirthik 

I did a dnu restore (console) and ran from the console, not using Visual studio and everything works fine. Inside Visual Studio using IIS Express or web, it does not work. 

Is this a bug with Visual Studio and localization?

Greetings Damien

**Comment by hishamco** [comment]
So that's why @kirthik asked you before :smile: , seems there's an issue with VS tooling

**Comment by damienbod** [comment]
Yes, didn't read @kirthik correctly

Thanks for your help

Greetings Damien

**Comment by hishamco** [comment]
@damienbod please close this if you got the answer

**Comment by damienbod** [comment]
I got my answer, but the VS tooling is not working. ASP.NET localization is working fine. Should I close this, maybe this is the wrong place for this problem. 

What's your opinion? For me , everything is clear.

Thanks

Greetings Damien

**Comment by kirthik** [comment]
Yes, please file an issue here - https://github.com/aspnet/Tooling

**Comment by jln1989** [comment]
Hi,

Can anyone tell me as to how to run this application using console? Please point to me in the direction where any docs are available. 

Am using Visual Studio 2015, Windows 10 OS and beta8 updated in my machine.

@damienbod @hishamco

**Comment by hishamco** [comment]
@jln1989 you can go to the root of your app, where project.json is located and open the command line and run the following commands:
```dnu restore```
```dnx web```

**Comment by damienbod** [comment]
Ref issue now:
https://github.com/aspnet/Tooling/issues/236

**Comment by jln1989** [comment]
@damienbod @hishamco : Does any of you face the issue where we need to make the resource file designer class name as "Public" once we add a new key every time? Is this a known issue which is being tracked somewhere or am missing something from my end?

**Comment by hishamco** [comment]
@jln1989 almost the time I work on Visual Code, because still there's an issue with tooling in Visual Studio

**Comment by damienbod** [comment]
@jln1989 
Hi yes, always, everything the resource is recreated

Greetings Damien

**Comment by jln1989** [comment]
@damienbod @hishamco : Thank you for the reply. 

I have a question regarding how to add a new language dynamically. Assume my application currently supports en-US (which is the default resource file with designer) and fr-CH so I have two resx files now. When I build my solution I could see in the output folder has a folder fr-ch and a DLL inside it. 

Let me assume that I have a solution which is running now and I need to add a new language to it. How do we achieve this in vNext? If my understanding is right I need to add the resource file to the solution and compile it and run the solution again. Is there a better way to achieve this at runtime?

**Comment by hishamco** [comment]
@jln1989 I prefer to create a new issue while you got the answer for this issue
