### ISSUE TITLE
Inconsistent behaviour of CookieRequestCultureProvider compared to QueryStringRequestCultureProvider

### ISSUE THREAD

**Issue by jerriep** [aspnet/Localization#116]
I have noticed that there is inconsistent behaviour between the Cookie provider and the Query String provider in terms of how they handle the situation when a user specifies either a culture or a UI culture, but not both.

In the case of the Cookie provider it requires the user to specify both otherwise it does nothing (see https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNet.Localization/CookieRequestCultureProvider.cs#L87-L90)

In the case of the Query String provider is allows the user to specify either (or both). In the case where you just specify one, the other will also revert to that value. So if I specify just the culture, then the UI culture will take the same value. (see https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNet.Localization/QueryStringRequestCultureProvider.cs#L62-L72)

Why is this behaviour inconsistent? Can we get it to work the same way across both?

**Comment by hishamco** [comment]
You are right @jerriep I made PR #63 to allow the user to specify either (or both) cultures in ```QueryStringProvider``` while the ```CookieProvider``` allows to specify both. I was supposed to do that before but I miss it :(
your thoughts @Eilon @kirthik

**Comment by TomArcher** [comment]
@jerriep I'm currently working on the Localization article. Let me know if you'd like to review the first draft and I'll let you know when it's ready.

**Comment by jerriep** [comment]
Sure @TomArcher . I am also publishing a series of blog posts on Localization, starting with this one tomorrow:
http://www.jerriepelser.com/blog/how-aspnet5-determines-culture-info-for-localization

**Comment by Eilon** [comment]
@kirthik can you sync with @DamianEdwards and/or @lodejard to decide the right behavior for these?

**Comment by kirthik** [comment]
Fixed with merge 636459a6f7d1753f06ddb77898f2d747c5a8af73
