### ISSUE TITLE
AcceptLanguageHeaderRequestCultureProvider not working in a MVC 6

### ISSUE THREAD

**Issue by damienbod** [aspnet/Localization#118]
If I set the Header: Accept-Language: de-CH, it is not used, the default resource from the browser is used instead

-------

GET http://localhost:5000/api/about/ HTTP/1.1
User-Agent: Fiddler
Host: localhost:5000
Accept-Language: de-CH;q=0.9,de;

---------

Greetings Damien

**Comment by hishamco** [comment]
Yes you should set it from the browser, I'm not sure what's the issue exactly?!!

**Comment by damienbod** [comment]
If I set the ?culture=de-CH in the URL everything works fine from the console.
If I use the Accept-Language HTML request Header, the localization does not work.

Greetings Damien

**Comment by hishamco** [comment]
Did you set the culture from the browser or control panel - internet options?

**Comment by damienbod** [comment]
both my language in the control panel is en-IE
IE : en-IE
Firefox: en-US

**Comment by hishamco** [comment]
I added Italian/Switzerland (it-CH) and I move it up to become the 1st language in firefox, your code recognize it :smile:
I don't think there's an issue at all

**Comment by damienbod** [comment]
I checked it again running from the console and it works with it-CH Accept-Headers.

Sorry, this is my mistake, 

Thanks for your help

Greetings Damien

**Comment by hishamco** [comment]
All the best :smile:

**Comment by Kirua88** [comment]
How can we run an mvc 6 web application from the console ?

**Comment by hishamco** [comment]
@Kirua88 you can use following DNX commands:
dnu restore
dnx web
also you can use DotNet coomands:
dotnet restore
dotnet run

**Comment by Kirua88** [comment]
Ok thank you =)
and can u you tell where i can ask a question about the equivalent of JsonRequestBehavior.AllowGet in asp core ?

**Comment by hishamco** [comment]
If you wanna ask a general question post it in [Home repo](http://github.com/aspnet/home), and if it's MVC specific post it in [MVC repo](https://github.com/aspnet/Mvc)
