### ISSUE TITLE
Custom CultureProvider not working in  a MVC 6 application

### ISSUE THREAD

**Issue by damienbod** [aspnet/Localization#119]
If I set the culture in the URL, this is not used 

example http://localhost:5000/api/de-CH/about

```c#
namespace AspNet5Localization.Controllers
{
    [Route("api/{culture}/[controller]")]
    public class AboutController : Controller
    {
        private IHtmlLocalizer<AmazingResource> _htmlLocalizer;

        public AboutController(IHtmlLocalizer<AmazingResource> localizer)
        {
            _htmlLocalizer = localizer;
        }

        [HttpGet]
        public string Get()
        {
            return _htmlLocalizer["Name"];
        }
    }
}
```

------

Greetings Damien

**Comment by hishamco** [comment]
@damienbod ```CustomCultureProvider``` needs you to write the code to provide the culture, have a look to what I come up with here https://github.com/aspnet/Localization/blob/dev/test/Microsoft.AspNet.Localization.Tests/CustomRequestCultureProviderTest.cs#L27

**Comment by damienbod** [comment]
OK, I have a look at this

Greetings Damien

**Comment by hishamco** [comment]
Did you implement a custom culture provider in your code? if it's yes post the code snippet

**Comment by damienbod** [comment]
Not yet, busy at present, won't have time till Friday
Greetings Damien

**Comment by hishamco** [comment]
So that mean there's no issue with ```CustomCultureProvider``` :smile: while you didn't implement it yet

**Comment by Eilon** [comment]
Indeed, you need to actually set the culture on the request using the Localization middleware, or something else similar.

**Comment by Codenator81** [comment]
I have same code for reference https://github.com/WeebDo/WeebDo.CMF/blob/master/src/WeebDoCMF/Startup.cs#L188

**Comment by hishamco** [comment]
Also this may related to issue #54 #57

**Comment by Muchiachio** [comment]
I'm actually going down the old route of overriding `OnActionExecuting` and taking language from the route values
```C#
public override void OnActionExecuting(ActionExecutingContext context)
{
    Thread.CurrentThread.CurrentUICulture = new CultureInfo(context.RouteData.Values["lang"] as String);

    base.OnActionExecuting(context);
}
```
hopefully it works later on. I can't trust parsing the query string, because this kind of routing breaks instantly
```
fr/en/users/create // create English user in French language
en/users/create // create English user in Japanese lang. (which is inferred as default from routing config)
```

**Comment by Codenator81** [comment]
@Muchiachio you need do
```c#
Thread.CurrentThread.CurrentCulture = new CultureInfo(context.RouteData.Values["lang"] as String);
Thread.CurrentThread.CurrentUICulture = new CultureInfo(context.RouteData.Values["lang"] as String);
```
at the same time.
You do only for CoreUI
