### ISSUE TITLE
Get segment from mapped route for CustomRequestCultureProvider

### ISSUE THREAD

**Issue by Codenator81** [aspnet/Localization#122]
I tested after 
```
app.UseMvc(routes =>
```
in startup class app.UseRequestLocalization not work.
For example user want culture segment been in:
```c#
routes.MapRoute(
                    name: "transRoute",
                    template: "{controller=Home}/{culture=en-US}/{action=Index}/{id?}");
```

So how I can get ```{culture}``` segment to find route match? 

This is all way not processed:
```c#
options.RequestCultureProviders.Insert(0, new CustomRequestCultureProvider(async context =>
            {
                var routeContext = new RouteContext(context); // IsHandled all ways false
```

Thanks Alex

**Comment by BenjiZombie** [comment]
What I did was create a `RouteRequestCultureProvider` instead.

	namespace Microsoft.AspNet.Localization
	{
		/// <summary>
		/// Determines the culture information for a request via values in the route.
		/// </summary>
		public class RouteRequestCultureProvider : RequestCultureProvider
		{
			#region Overrides of RequestCultureProvider

			public override Task<RequestCulture> DetermineRequestCulture(HttpContext httpContext)
			{
				if (httpContext == null)
				{
					throw new ArgumentNullException(nameof(httpContext));
				}

				var request = httpContext.Request;
				if (!request.Path.HasValue)
				{
					return Task.FromResult((RequestCulture) null);
				}

				var cultureValue = Regex.Match(
					request.Path.Value,
					@"^/([A-Za-z]{2})",
					RegexOptions.IgnoreCase);

				if (cultureValue.Success)
				{
					var culture = CultureInfoCache.GetCultureInfo(cultureValue.Groups[1].Value);
					var uiCulture = CultureInfoCache.GetCultureInfo(cultureValue.Groups[1].Value);

					if (culture == null || uiCulture == null)
					{
						return Task.FromResult((RequestCulture) null);
					}

					var requestCulture = new RequestCulture(culture, uiCulture);
					requestCulture = ValidateRequestCulture(requestCulture);

					return Task.FromResult(requestCulture);
				}

				return Task.FromResult((RequestCulture) null);
			}

			#endregion
		}
	}

Then simply register it in the `Configure` method:

	// Add localization to the request pipeline.
	var requestLocalizationOptions = new RequestLocalizationOptions
	{
		SupportedCultures = new List<CultureInfo>
		{
			new CultureInfo("en"),
			new CultureInfo("fr"),
			new CultureInfo("es")
		},
		SupportedUICultures = new List<CultureInfo>
		{
			new CultureInfo("en"),
			new CultureInfo("fr"),
			new CultureInfo("es")
		}
	};
	requestLocalizationOptions.RequestCultureProviders.Insert(2, new RouteRequestCultureProvider
	{
		Options = requestLocalizationOptions
	});
	app.UseRequestLocalization(requestLocalizationOptions);

My route mapping is different from yours, but you can easily modify the code to fit your needs

	// Add MVC to the request pipeline.
	app.UseMvc(routes =>
	{
		routes.MapRoute(
			name: "default",
			template: "{culture?}/{controller}/{action}/{id?}",
			defaults: new { culture = "en", controller = "Home", action = "Index" });
	});

**Comment by Codenator81** [comment]
@BenjiZombie thanks for good example. 
I do similar in my code https://github.com/WeebDo/WeebDo.CMF/blob/master/src/WeebDoCMF/Startup.cs#L190
I think there no way to get segment {culture} from route for now before 
```c#
app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{culture?}/{controller}/{action}/{id?}",
        defaults: new { culture = "en", controller = "Home", action = "Index" });
});
```

**Comment by hishamco** [comment]
You can have a look to issue #54 #57 as well as https://github.com/aspnet/Localization/blob/dev/test/Microsoft.AspNet.Localization.Tests/CustomRequestCultureProviderTest.cs#L46

**Comment by Codenator81** [comment]
@hishamco Thanks I implement my code based on your links :+1: 
Here cuestion more about how get culture as I do in MVC 5 from Controller
```
RouteData.Values["culture"] as string;
```

**Comment by hishamco** [comment]
@Codenator81 you can inject ```IHtmlLocalizer``` in your controller constructor, have a look to @damienbod source here https://github.com/damienbod/AspNet5Localization/blob/master/AspNet5Localization/src/AspNet5Localization/Controllers/AboutController.cs#L16

**Comment by Codenator81** [comment]
@hishamco I do it in HomeController all ready)
https://github.com/WeebDo/WeebDo.CMF/blob/master/src/WeebDoCMF/Controllers/HomeController.cs#L19

**Comment by hishamco** [comment]
What is the value of ``` ViewBag.Trans``` when you print it out, because I don't know what is the issue in your sample

**Comment by Codenator81** [comment]
@hishamco  There everything work great. My issue is how get route segment from route template before UseMVC middleware. But I think it is not possible. I will try different approach.

**Comment by hishamco** [comment]
Why you need it before MVC middleware?!! if that's the case i will try to look in your sample

**Comment by Codenator81** [comment]
@hishamco You are right :+1: 
 I will write own middleware which going to work after UseMVC and set needed culture thread

**Comment by hishamco** [comment]
All the best @Codenator81 , be free to ask if you have an issue again

**Comment by danroth27** [comment]
@kirthik @DamianEdwards We should look at what our guidance is for using path segments for determining the culture and maybe provide a sample on how to do it.

**Comment by hishamco** [comment]
@danroth27 i provide a simple unit test in https://github.com/aspnet/Localization/blob/dev/test/Microsoft.AspNet.Localization.Tests/CustomRequestCultureProviderTest.cs#L46, also I already suggest #43, if this will help i will make a PR for that

**Comment by Codenator81** [comment]
No one middleware work after UseMVC middleware

**Comment by hishamco** [comment]
@Codenator81 if what you are looking for is in culture segment in "{controller=Home}/{culture=en-US}/{action=Index}/{id?}", I will try to look to into your sample or i will write a code snippet to display the culture segment

**Comment by Codenator81** [comment]
@hishamco Yes I looking for that.

**Comment by damienbod** [comment]
I think this should be an extra  default Provider like the others as this is a common use case. What do you think? 

Greetings Damien

**Comment by hishamco** [comment]
Ok @Codenator81 I will dig into that
@damienbod as I said before, I already suggest that in #43

**Comment by hishamco** [comment]
@Codenator81 for saving time do you have a repo with the latest changes that you did?

**Comment by damienbod** [comment]
@hishamco 

Thanks for your answer, your PR sounds great, I was thinking more of a MVC 6 extension which would allow me to define my culture in the MVC attribute routing.

Greetings Damien

**Comment by hishamco** [comment]
@damienbod IMHO while there's ```RequestCultureProvider``` is out-of-the-box it will be nice to be provider than extension

**Comment by Codenator81** [comment]
So I do it in controller old way from MVC 5:
https://github.com/WeebDo/WeebDo.CMF/blob/master/src/WeebDoCMF/WDCore/Controllers/WDTranslationController.cs
and using
https://github.com/WeebDo/WeebDo.CMF/blob/master/src/WeebDoCMF/Controllers/HomeController.cs#L14

**Comment by hishamco** [comment]
@Codenator81 have you look to this sample https://github.com/aspnet/Mvc/tree/9342cb0ab78add8c527edcbc4c0988edc96f01e3/test/WebSites/LocalizationWebSite if you didn't get your answer, I will add a sample demo for that

**Comment by Codenator81** [comment]
@hishamco I see that example long time ago. For now it is outdated? For example app.UseCultureReplacer(); I don`t find (may be removed from code)?
I think there is good example for starters or people who moving from < MVC5.

As I wrote one comment before I looking for segment in Controller. Same people do simelar approach in filter. But for now it is not possible get segment from middleware. I think it is routing feature or issue.
 Not Localization.

**Comment by hishamco** [comment]
I see, but as I mentioned before issue #54 and https://github.com/aspnet/Localization/blob/dev/test/Microsoft.AspNet.Localization.Tests/CustomRequestCultureProviderTest.cs#L57 do such thing without using routes, I used segments instead, probably the idea is same. I'm not sure such sample should be in localization repo or mvc?!!
/cc @Eilon

**Comment by Codenator81** [comment]
@hishamco I see all that examples. All of them great :+1:   My issue different.
I wrote before:
```c#
routes.MapRoute(
         name: "transRoute",
         template: "{controller=Home}/{culture=en-US}/{action=Index}/{id?}");
```
So I wont detect culture segment if it is at end route or at middle without rewrite code and just get that segment as I do in code there:
```c#
string cultureFromRoute = RouteData.Values["culture"] as string;
```

**Comment by hishamco** [comment]
Could you please add a repo summarize your scenario without any other stuff  (MiniMVC), i already saw **WeebDoCMF** but I don't wanna miss on any other stuff :smile:

**Comment by Codenator81** [comment]
Ok I will do it. May be today evening.

**Comment by hishamco** [comment]
It's in the way @Codenator81 :smile: 
https://github.com/aspnet/Localization/commit/53a8fa6abc85712bfd6d7f4543b0a1c632912774
