### ISSUE TITLE
better samples?

### ISSUE THREAD

**Issue by joeaudette** [aspnet/Localization#124]
The current sample does not provide a lot of guidance. I wish there were samples showing how to:

* localize strings in Views 
* localize strings in a controller
* localize data annotations, error messages, displayname etc for viewmodels

**Comment by hishamco** [comment]
@joeaudette the sample is shows how to use the localization APIs and how to use Culture Providers, IMHO what you ask for is cool, but it's MVC specific
your thoughts @Eilon @kirthik

**Comment by joeaudette** [comment]
ok, so maybe better samples need to be added to mvc repo, though it seems more obvious to look for them here.

In any case we need more real world examples.

**Comment by hishamco** [comment]
The samples in almost the repos give the audience a quick glance to how use the APIs, sure it will not shows all the scenarios :smile: 
But you can post an issue with your needs, and i'm sure the folks will help you a lot

**Comment by Eilon** [comment]
There's an MVC localization sample here: https://github.com/aspnet/Mvc/tree/9342cb0ab78add8c527edcbc4c0988edc96f01e3/test/WebSites/LocalizationWebSite

It includes controller localization, view localization, and model localization.

**Comment by joeaudette** [comment]
Thank you so much! That sample looks like just what I was looking for. I had not looked under the test folder for samples.

**Comment by joeaudette** [comment]
unfortunately when I make a copy of that sample and change it to use beta8 it does not seem to work. It does correctly select a view for a culture like Home/Index.fr.cshtml
If I set my browser language preference to fr I see the correct view but it does not seem to localize anything using the .resx files in the Resources folder. The Locpage just appears as blank which made me think it was possibly a 404 so I copied the logic from the locpage action into the index action:

    ViewData["Message"] = _localizer["Learn More"];

 and added

    @ViewBag.Message

into Index.fr.cshtml which should come from HomeController.fr.resx but it does not get localized.

So it seems to me that use of resx files for localization is not really working in beta 8.

**Comment by hishamco** [comment]
What I have seen in the localization sample before if there's something wrong in the culture the ```RequestProvider``` will return ```null``` which makes the page blank. So if you have a repo for the latest modification that you made, write down the link and i will dig into that

**Comment by joeaudette** [comment]
Thanks that would be great if you could take a look. I've just added it to a public repo here: https://github.com/joeaudette/experiments

**Comment by kirthik** [comment]
Are you running your website from VS or from command line? Please run it frmo command line. Pulling localized content from resources is not supported yet from VS - https://github.com/aspnet/dnx/issues/2727

**Comment by joeaudette** [comment]
Thank you @kirthik! I was running it from VS 2015. I just tried running it from the command line and I see you are right it works there.
That is very helpful, I can work with that until the next tooling update.

I wonder does that issue also exist if I install the platform handler in IIS and publish/deploy it to IIS?
ie is it really VS that is the problem or is it the platform handler/IIS Express integration?

**Comment by hishamco** [comment]
@joeaudette I thought you already see the issue #117 #115, for the reason that @kirthik mentioned before. So I think there's no need to dig into your repo, problem solved :smile:
