### ISSUE TITLE
How to force a certain localization?

### ISSUE THREAD

**Issue by leak** [aspnet/Localization#125]
Tried it like suggested here: http://www.jerriepelser.com/blog/setting-thread-culture-aspnet5

Doesn't seem to be working. In my WebApi controller the CultureInfo.CurrentCulture is still set to my systems setting rather than what I configured (see below).

````
app.UseRequestLocalization(new RequestLocalizationOptions
{
    DefaultRequestCulture = new RequestCulture(new CultureInfo("en-US")),
    SupportedCultures = new List<CultureInfo>
    {
        new CultureInfo("en-US")
    },
    SupportedUICultures = new List<CultureInfo>
    {
        new CultureInfo("en-US")
    }
});
````

**Comment by hishamco** [comment]
Do you have the sample in online repo?

**Comment by leak** [comment]
After a bit of testing I think I solved my problem.

Turns out that I had `app.UseRequestLocalization()` and `app.UseMvc()` in the wrong order basically rendering all localization efforts useless.

While it now totally makes sense to me, I think it wouldn't be all wrong if there would be a small hint about this in any future documentation at docs.asp.net
