### ISSUE TITLE
[Bug] Unable to locate Microsoft.Extensions.PlatformAbstractions

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#126]
While i'm running ```dnu restore``` I got this exception **Unable to locate Microsoft.Extensions.PlatformAbstractions**, probably this happen after this commit https://github.com/aspnet/Localization/commit/d25ad6607e0abca395a7a1fca45d5afbee5356c9
/cc @pakrym @kirthik @Eilon

**Comment by hishamco** [comment]
After I run **build.cmd** all the packages has been restored successfully, nothing but this exception is show up
![capture](https://cloud.githubusercontent.com/assets/3237266/10707039/eb03f92a-79f5-11e5-8e1f-d5e232f7dd94.JPG)
/cc @kirthik

**Comment by kirthik** [comment]
You need to upgrade `dnx`

**Comment by hishamco** [comment]
I already did that yesterday it's **1.0.0-beta8-15604**

**Comment by hishamco** [comment]
New version show up in the list today **1.0.0-rc1-15838** i will upgrade and check now

**Comment by hishamco** [comment]
@kirthik I upgrade and run ```dnu restore --no-cache``` with no luck :(, any idea

**Comment by hishamco** [comment]
Still I'm stuck with this bug, any idea
/cc @Eilon

**Comment by danroth27** [comment]
Could you please provide:
- The output of `dnx --version`
- The output of `dnu feeds list`
- Your web command from project.json

Also, could you please try clearing out your `.dnx/packages` folder and run restore again?

**Comment by hishamco** [comment]
1.0.0-rc1-15838

Feeds in use:
    https://www.nuget.org/api/v2/
      Origin: C:\Users\Hisham\AppData\Roaming\NuGet\nuget.config
    https://api.nuget.org/v3/index.json [Disabled]
      Offical NuGet Source, enabled by default

NuGet Config files in use:
    C:\Users\Hisham\AppData\Roaming\NuGet\nuget.config

Web Command "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"

**Comment by hishamco** [comment]
Still I got the exception :(

**Comment by Eilon** [comment]
None of those feeds have RC1 on them - where are you getting RC1 builds from?

**Comment by hishamco** [comment]
@Eilon I just upgrade dnvm couple days ago, how can i fix it

**Comment by Eilon** [comment]
@NTaylorMullen can you take a look at this? I still think this is just a DNX or package mismatch. Note that there's a linked bug https://github.com/aspnet/Mvc/issues/3407 where another person saw something similar.

**Comment by hishamco** [comment]
@Eilon I did whatever I can, upgrading dnvm to rc, remove .dnx entries .. ect, no way, the sample and test units won't run

**Comment by Eilon** [comment]
@hishamco everything on all the machines here is working fine, so clearly there's some difference in what feeds or configuration people are using.

**Comment by hishamco** [comment]
Really I stuck @Eilon, I notice whenever I pull the latest changes from the **upstream** something should go wrong in my machine, so any idea how can I avoid this.
BTW when you mentioned issue #3407 I thought it's a common issue

**Comment by NTaylorMullen** [comment]
Hey @hishamco I was able to `dnu restore` successfully.

**DNX:** 
```
Microsoft .NET Execution environment
 Version:      1.0.0-rc2-16071
 Type:         Clr
 Architecture: x86
 OS Name:      Windows
 OS Version:   10.0
 Runtime Id:   win10-x86
```

**Feeds:**
```
Feeds in use:
    https://www.nuget.org/api/v2/ [Disabled]
      Origin: C:\Users\nimullen\AppData\Roaming\NuGet\nuget.config
    https://www.myget.org/F/aspnetcidev/api/v3/index.json
      Origin: C:\Users\nimullen\Documents\GitHub\Localization\nuget.config
    https://api.nuget.org/v3/index.json
      Origin: C:\Users\nimullen\Documents\GitHub\Localization\nuget.config

NuGet Config files in use:
    C:\Users\nimullen\AppData\Roaming\NuGet\nuget.config
    C:\Users\nimullen\Documents\GitHub\Localization\nuget.config
```

I'm not entirely sure why things are failing on your end, something may have put your machine in a bad state. Do the following and then try dnu restoring again:
- Delete your `%UserProfile%/.dnx/packages` folder
- Delete your `%LocalAppData%/dnu/cache` folder
- Remove all `project.lock.json` files in your Localization directory.

**Comment by hishamco** [comment]
@NTaylorMullen I'm using **1.0.0-rc1-15838**, whenever i upgrade the dnvm **1.0.0-rc2-16071** doesn't show up on the list

**Comment by NTaylorMullen** [comment]
@hishamco You must have an odd `dnvm` feed setup. To upgrade your DNX to development bits do the following in powershell:

```
$env:DNX_FEED="https://www.myget.org/F/aspnetcidev/api/v2"
dnvm upgrade
```

The problem here is that `dnvm` uses a different feed than the ones specified in your `NuGet.config`.

**Comment by hishamco** [comment]
@NTaylorMullen i upgraded the dnvm to the same version but i got this exception in sample project
![capture1](https://cloud.githubusercontent.com/assets/3237266/10853311/7f3a3b90-7f46-11e5-85ac-28cfe75b1ee4.JPG)
and this in unit test project
![capture2](https://cloud.githubusercontent.com/assets/3237266/10853320/8c5368ce-7f46-11e5-80d5-402672fb665e.JPG)

**Comment by NTaylorMullen** [comment]
Did you `dnu restore`?

**Comment by hishamco** [comment]
Of course

**Comment by NTaylorMullen** [comment]
That's indeed odd. Could you do `$env:DNX_TRACE="1"` and then clean everything like I suggested and re-run then post the output?

**Comment by hishamco** [comment]
Finally, after one week it works fine :smile: ,removing an old **KRE_HOME** key and  following the steps of @NTaylorMullen in Localization folder, it works like a charm :smile:

**Comment by NTaylorMullen** [comment]
Awesome, glad I could help :smile:
