### ISSUE TITLE
ResourceManagerStringLocalizer should support throwing if name not found

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Localization#13]
Add the ability to configure the `ResourceManagerStringLocalizer` so that if a given resource name is not found it throws, rather than returning the key itself. This effectively makes it behave like the underlying `ResourceManager` API itself.

e.g.

```
public enum ResourceLookupBehavior
{
    UseNameIfNotFound,
    ThrowIfNotFound
}

public class ResourceManagerStringLocalizerFactory...
{
    ...
    public ResourceLookupBehavior ResourceLookupBehavior { get; set; } = ResourceLookupBehavior.UseNameIfNotFound;
    ...
}
```

**Comment by glen-84** [comment]
This could be used by other implementations of `IStringLocalizer`, so you might consider making it more generic (f.e. `LookupBehavior` / `StringLookupBehavior` / `LocalizedStringLookupBehavior`).

**Comment by Rick-Anderson** [comment]
If you could make it act like MVC does when it can't find a view - that is, MVC will list the folders searched, that would really help debug.

``An unhandled exception occurred while processing the request.

InvalidOperationException: The view 'About' was not found. The following locations were searched:
/Views/Home/About.cshtml
/Views/Shared/About.cshtml.``

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
