### ISSUE TITLE
[Discussion] LocalizationOptions

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#133]
I'm still wondering if we really need ```ResourcesPath``` in ```LocalizationOptions```, because ```ResourcesPath``` is resx specific, although localized values can come from resx or database, json .. etc.
IMHO ```LocalizationOptions``` should provide general configurations for Localization such as DefaultCulture, SupportedCulture and so on. I find issue #127 which is may express what i mean

/cc @DamianEdwards @kirthik

**Comment by danroth27** [comment]
The `ResourcesPath` isn't intended to be resx specific - it is a path to your localized content which could be in whatever format you want. You are not required to set a `ResourcesPath` and `IStringLocalizerFactory` implementations are free to ignore it.

**Comment by hishamco** [comment]
@danroth27 I know it's not required, but seems a file-based specific, anyhow, what about the second part of ```LocalizationOptions```

**Comment by danroth27** [comment]
Options like SupportedCultures are specified when you setup the localization middleware.
