### ISSUE TITLE
DisplayAttribute not works with ResX ResourceType

### ISSUE THREAD

**Issue by YZahringer** [aspnet/Localization#134]
Hello,

Using the DisplayAttribute with ResourceType property does not work. ValidationAttribute types works (Required, EmailAdress, ...).

The problem is the generated code in .Designer.cs of ResX as the internal properties, the Display attribute does not accept.

**Comment by hishamco** [comment]
IMHO you should make the access specifier ```public``` because the ```Designer.cs``` will make it ```internal``` whenever you change it

**Comment by hishamco** [comment]
@YZahringer you can check the latest posts in this issue #115

**Comment by YZahringer** [comment]
@hishamco yes, but Designer.cs is generated at each modification of ResX, I can not edit it.

The internal properties works with RequiredAttribute, this should also work with the DisplayAttribute in my opinion.

**Comment by hishamco** [comment]
@YZahringer i think this a common issue have a look to the last post in issue #31, @kirthik is already assigned to that issue

**Comment by YZahringer** [comment]
@hishamco Yes sorry for duplication
