### ISSUE TITLE
Localization  Query regarding adding a new language without compiling the solution

### ISSUE THREAD

**Issue by jln1989** [aspnet/Localization#135]
I have a question regarding how to add a new language dynamically. Assume my application currently supports en-US (which is the default resource file with designer) and fr-CH so I have two resx files now. When I build my solution I could see in the output folder has a folder fr-ch and a DLL inside it. 

Let me assume that I have a solution which is running now and I need to add a new language to it. How do we achieve this in vNext? If my understanding is right I need to add the resource file to the solution and compile it and run the solution again. Is there a better way to achieve this without compiling the solution?

**Comment by hishamco** [comment]
After the new design change in #111, you should provide the list of supported cultures in localization middleware. Regarding the localization values it depends, in your case adding a new resx is required, but if you have different store such as json, database .. etc you should do something else based on your needs.
Of course you need to restart the app to initialize the middleware after newly adding language, @kirthik @Eilon if there's a better solution you can share it if you don't mind

**Comment by csunali** [comment]
@hishamco Hi, are you aware of any sample code for storing localization resource data in database? Or just any simple custom resource store, so I can figure out how to implement one for myself.

**Comment by jln1989** [comment]
Closing this as dupliicate #87
