### ISSUE TITLE
Where in the middleware should app.UseRequestLocalization() be called?

### ISSUE THREAD

**Issue by jerriep** [aspnet/Localization#136]
I have an application which uses the localization middleware. Previously I would call `app.UseRequestLocalization()` very early in the `Configure` method:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.MinimumLevel = LogLevel.Information;
    loggerFactory.AddConsole();
    loggerFactory.AddDebug();

   app.UseRequestLocalization();

   // Rest of the method...
}
```

But I have written a custom `RequestCultureProvider` which read the culture from the user info. Well actually it reads it from a claim on the ClaimsPrincipal (i.e. HttpContext.User property).

Thing is however that if put the call to `app.UseRequestLocalization()` early in the methodm the user is not set because the Identity middleware has not executed yet. So I need to move it to somewhere after the call to `app.UseIdentity()`, then all works fine.

I am curious however whether there will be some sort of obviously bad side effect I may suffer when moving the Localization middleware further down the middleware pipeline?

**Comment by c1rus** [comment]
I was solving same problem and i ended with this:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.MinimumLevel = LogLevel.Information;
    loggerFactory.AddConsole();
    loggerFactory.AddDebug();

	app.UseRequestLocalization();

	// UseCookieAuthentication..
	// UseJwtBearerAuthentication..
   
	//add userculture provider for authenticated user
	var requestOpt = new Microsoft.AspNet.Localization.RequestLocalizationOptions();
	requestOpt.RequestCultureProviders.Clear();
	requestOpt.RequestCultureProviders.Add(new UserCultureProvider());
	app.UseRequestLocalization(requestOpt);
	
	app.UseMvc();
}

public class UserCultureProvider : IRequestCultureProvider
{
	public async Task<RequestCulture> DetermineRequestCulture(HttpContext httpContext)
	{
		var requestFeature = httpContext.Features.Get<IRequestCultureFeature>();

		if (requestFeature?.RequestCulture != null) return requestFeature.RequestCulture;

		if (httpContext.User == null || !httpContext.User.Identity.IsAuthenticated) return null;

		var culture = httpContext.User.GetCulture(); // custom extension method

		return new RequestCulture(culture);
	}
}
```

**Comment by jerriep** [comment]
Aah yes, that should work, thanks :)

**Comment by jerriep** [comment]
@c1rus It works, but there is one slight modification. You need to ensure that you set the DefaultRequestCulture to null, otherwise it will reset the culture to the whatever the culture of the current thread is that IIS Express is running under, which will override the culture that was set before, in my case by the Accept-Language HTTP header

```
            var requestLocalizationOptions = new RequestLocalizationOptions
            {
                DefaultRequestCulture = null
            };
            requestLocalizationOptions.RequestCultureProviders.Clear();
            requestLocalizationOptions.RequestCultureProviders.Add(new UserProfileRequestCultureProvider());
            app.UseRequestLocalization(requestLocalizationOptions);
```

This is the behaviour in Beta 8. 

It seems that the MS team has subsequently removed the `DefaultRequestCulture` property from the `RequestLocalizationOptions` class, and from RC1 you will have to pass in the value when registering the middleware, and it cannot be null, so not sure whether this method of yours will still work then...

**Comment by c1rus** [comment]
Actually, i dont want to override the default providers with user provider. My provider priority list is this in the end:

1. QueryStringRequestCultureProvider
2. CookieRequestCultureProvider
3. AcceptLanguageHeaderRequestCultureProvider
4. UserCultureProvider

So maybe this will work better for you:
```
public class UserCultureProvider : IRequestCultureProvider
{

	public Task<RequestCulture> DetermineRequestCulture(HttpContext httpContext)
	{
		if (httpContext.User == null || !httpContext.User.Identity.IsAuthenticated) return null;

		var culture = httpContext.User.GetCulture(); // custom extension method

		return new RequestCulture(culture);
	}
}
```

**Comment by hishamco** [comment]
No need @jerriep you can do something like this
```csharp
options.RequestCultureProviders.Insert(0, new UserCultureProvider())
```

**Comment by jerriep** [comment]
@hishamco Yeah, that is what I am doing. Here is my startup.cs:

https://github.com/jerriep/LocalizationByUser/blob/master/src/LocalizationByUser/Startup.cs

It is working 100%. My question is however about whether the fact that the Localization middleware executes so late (i.e. **after** the call to `app.UseIdentity()`) whether that will cause strange side effects. Usually it is configured to execute quite early in the Localization timeline.

**Comment by hishamco** [comment]
I'm not quite sure if there's side effect, IMHO you should use ```UseRequestLocalization``` before the middlewares that may need localization such as ```UseMvcWithDefaultRoute```

**Comment by jerriep** [comment]
Yeah, the only effect now is that my error pages won't be localized. Although I am not sure whether they even support localization.

My thought was also that as long as it executes before the MVC middleware I should be OK.

**Comment by hishamco** [comment]
That's what I think too :smile:

**Comment by danroth27** [comment]
The only side effect is when the culture gets established. So for example if something throws an exception early in the pipeline before the culture gets established then you might get an unlocalized content in the error page depending on how you've set up your error handling logic.

**Comment by jerriep** [comment]
Thank you for confirming the very limited possible side-effects @danroth27. I can live with that and will explain this clearly in my blog post.

**Comment by dudedev** [comment]
Hey, I am using UseRequestLocalization() after authentication middleware. But, still httpContext.User.Identity.IsAuthenticated is false, because request localization is happening before authentication as per logs. I do not understand why. 
The middleware order in Configure method is given below.

```
            webApi.UseAuthentication();
            webApi.UseRequestLocalization(localizationOptions);
            webApi.UseMvc();
```

Anyone has any idea?

**Comment by nilbert** [comment]
> Hey, I am using UseRequestLocalization() after authentication middleware. But, still httpContext.User.Identity.IsAuthenticated is false, because request localization is happening before authentication as per logs. I do not understand why.
> The middleware order in Configure method is given below.
> 
> ```
>             webApi.UseAuthentication();
>             webApi.UseRequestLocalization(localizationOptions);
>             webApi.UseMvc();
> ```
> I am using IdentityServer4 bearer token authentication.
> Anyone has any idea?

I solved configuring the services `  services.Configure<RequestLocalizationOptions>(localizationOptions);`
