### ISSUE TITLE
Unable to use localized resources from different classlibrary

### ISSUE THREAD

**Issue by XplMarcel** [aspnet/Localization#139]
I don't know if this is the correct approach, but i'm struggling to get resources from existing classlibraries (win) localized. My project setup is like this:

- Solution
  - Applications
   - Asp.net 5 application
    - References
      - DNX 4.6
        - MyClassLibrary.Resources.DNX
- DNX classlibraries
  - MyClassLibrary.Resources.DNX
    - project.json
```json
{
  "compile": [
    "../../Win/MyClassLibrary.Resources/*.cs"
  ],
  "exclude": [
    "../../Win/MyClassLibrary.Resources/Properties"
  ],
  "resource": [ "../../Win/MyClassLibrary.Resources/*.resx" ],
  "frameworks": {
    "dnx46": { }
  }
}
```
- Win classlibraries
  - MyClassLibrary.Resources

So basicly I included the necessary source files from the win classlibrary in my dnx classlibrary.
Everything works fine using strongly typed resources like this, except localization.
I can see the correct culture in my controllers if i check HttpContext.Features.Get<IRequestCultureFeature>().RequestCulture.Culture, but the strongly typed resourcemanager doesn't have any resourcesets.

Any ideas how to make this work ?

**Comment by hishamco** [comment]
Can you check if the resources are ```internal```?

**Comment by XplMarcel** [comment]
@hishamco they are public in the .Designer.cs
public class ExceptionStrings {
 public static global::System.Resources.ResourceManager ResourceManager {
 }
}

**Comment by hishamco** [comment]
Ok, but why you need to access the ```ResourceManager``` while you can use DI and ```IStringLocalizer``` to fetch the resources?!!

**Comment by XplMarcel** [comment]
Ok, I have Domain classes which are shared between a win classlibrary and dnx classlibrary.
These domain classes use FluentValidation and strongly typed resources for validation failure messages since i don't have DI available in the win classlibrary.
This (ofcourse) worked perfectly fine in MVC 5, because the resources were build to sattelite assemblies.
If i can't use strongly typed resources migrating from MVC 5 to MVC 6 will become a major pain.

**Comment by hishamco** [comment]
I'm not sure if this belong to this repo or shall you post it in Tooling repo
your thoughts @Eilon

**Comment by XplMarcel** [comment]
@hishamco 
I think i know what the problem is.
I was looking through other issues and saw this one https://github.com/aspnet/Localization/issues/115, which is very similair to my issue.
So i did the same and ran the application in powershell (dnx web) and it worked.
So this is indeed a tooling issue where running from VS doesn't load sattelite assemblies.
Strongly typed resources are working, except when running in VS.

**Comment by hishamco** [comment]
Yep this is a common issue :(

**Comment by Eilon** [comment]
Yup, sorry about that, this is a known issue that is being fixed in DNX.
