### ISSUE TITLE
Why is _missingManifestCache in ResourceManagerStringLocalizer

### ISSUE THREAD

**Issue by Anderman** [aspnet/Localization#142]
Why is _missingManifestCache in ResourceManagerStringLocalizer. Because ResourceManagerStringLocalizer is Transient. Now it is not likely to cache anything

```
 services.TryAdd(new ServiceDescriptor(
                typeof(IStringLocalizerFactory),
                typeof(ResourceManagerStringLocalizerFactory),
                ServiceLifetime.Singleton));
            services.TryAdd(new ServiceDescriptor(
                typeof(IStringLocalizer<>),
                typeof(StringLocalizer<>),
                ServiceLifetime.Transient));
```

**Comment by hishamco** [comment]
IMHO ```missingManifestCache ``` is a ```ConcurrentDictionary``` to cache the missing requested keys instead of going back and forth to the disk, asking the ```ResourceManager``` each time for a missing resources is expensive while there are nt exist at all. I think this a clear solution and that's why it's there

**Comment by Anderman** [comment]
No, Now you get a new empty cache object for every request. With 2 request the disk is accessed 2 times. 
This will only work If the cache was placed in the factory or the IStringLocalizer was a singleton

Maybe I use this object wrong

I used this in my home controller

```
public HomeController(IStringLocalizer<HomeController> loc)
        {
            _loc = loc;
        }
```

**Comment by Eilon** [comment]
@Anderman we took a look at this issue and we believe there's no bug here because the code is always run on a single thread anyway. But this did reveal that there's no need to use a ConcurrentDictionary at all here, so we'll change that to a regular dictionary in https://github.com/aspnet/Localization/issues/156.

Thanks!
