### ISSUE TITLE
GetAllStrings give System.ArgumentNullException

### ISSUE THREAD

**Issue by Anderman** [aspnet/Localization#143]
GetAllStrings give `System.ArgumentNullException`.because `cultureResourceStream` is null

The problem seems to be in `private IList<string> GetResourceNamesForCulture(CultureInfo culture)` in `ResourceManagerStringLocalizer.cs`

 ```
var cultureResourceNames = _resourceNamesCache.GetOrAdd(cacheKey, _ =>
            {
                var names = new List<string>();
                using (var cultureResourceStream = _resourceAssemblyWrapper.GetManifestResourceStream(resourceStreamName))
                using (var resources = new ResourceReader(cultureResourceStream))
                {
                    foreach (DictionaryEntry entry in resources)
                    {
                        var resourceName = (string)entry.Key;
                        names.Add(resourceName);
                    }
                }
                return names;
            });
```

If have 3 files but only Invariant can be read (`HomeController.nl-NL.resx`,`HomeController.nl.resx`, `HomeController.resx`)
The files are ok and can be read by `resourceManager.GetString(name)` command

**Comment by hishamco** [comment]
If I'm not wrong, this is a duplicate to what @DamianEdwards is catch in issue #138

**Comment by Anderman** [comment]
Hmm could be, but I think that's is not the case. 

I think that .resx will be compiled to .cs files and that's why you can't have .cs file with the same name as .resx files. 

I seems that rosline or DNX only compile `HomeController.resx' to HomeController.cs. 

The Assembly.GetManifestResourceStream(name) will only look to the compiled version
and the ResourceManager..GetString(name) will first try the compiled version and then fallback to the .resx file on disk.

**Comment by hishamco** [comment]
There's a bug, so you can't have both class and resource files with the same name

**Comment by Anderman** [comment]
I Used GetManifestResourceNames. to lookup the .resource files. In my program I got only `DBC.My.Resources.HomeController.resources` So  I think there are two problems.

* rosline/dnx problem to generate a DBC.My.Resources.HomeController.resources.nl-NL file
* ArgumentNullException if resource file is not available

The Try Catch can be removed because `MissingManifestResourceException` isn't an exception that will be generated when using GetManifestResourceStream

```
try
                {
                    var cultureResourceNames = GetResourceNamesForCulture(currentCulture);
                    foreach (var resourceName in cultureResourceNames)
                    {
                        resourceNames.Add(resourceName);
                    }
                }
                catch (MissingManifestResourceException) { }
```

**Comment by hishamco** [comment]
Your thought @kirthik

**Comment by Eilon** [comment]
@ryanbrandenburg can you try to reproduce this issue?

@Anderman if you can upload your app to GitHub to show this issue that would also be helpful. Thanks!

**Comment by Anderman** [comment]
Ok I found 3 different issue's with the localizer. Should I create 2 other issue?
This one is the has the problem with the 
Get 
`var cultureResourceStream = _resourceAssemblyWrapper.GetManifestResourceStream(resourceStreamName)`

The `resourceStreamName` has the name of something like 
`localize.Resources.localize.Controllers.HomeController.nl-NL.resources`

But if I check with `Assembly.GetManifestResourceNames()` only
`localize.Resources.Localize.Controllers.HomeController.resources` is available

The other .resource file are not available.

I created this [repository](https://github.com/Anderman/Issue143) with 3 bugs

```
public HomeController(IStringLocalizerFactory stringLocalizerFactory, IStringLocalizer<HomeController> T)
        {
            var stringLocalizer = stringLocalizerFactory.Create("Test", location: null);

            var resourceFiles = typeof(HomeController).Assembly.GetManifestResourceNames();
            foreach (var resFile in resourceFiles)
                Console.WriteLine(resFile.ToString());
            //bug 1. See the base name contruction is with capital in the ResourceManagerStringLocalizerFactory.cs
            Console.WriteLine("Watch the capital problem in the 2e localize");

            //Make sure this is working
            Console.WriteLine(T["test"], T["test"].ResourceNotFound.ToString());
            //bug 2
            Console.WriteLine(T.WithCulture(new CultureInfo("nl-NL"))["test"] + ":" + T["test"].ResourceNotFound.ToString() + "should be false!!!"); ;
            Console.WriteLine(T.WithCulture(new CultureInfo("nl-NL"))["Hello"]);
            Console.WriteLine(T.WithCulture(new CultureInfo("nl"))["Hello"]);
            Console.WriteLine(T.WithCulture(new CultureInfo(""))["Hello"]);


            var specific = T.WithCulture(new CultureInfo("nl-NL")).GetAllStrings(true);
            var neutral = T.WithCulture(new CultureInfo("nl")).GetAllStrings(true);
            var invariant = T.WithCulture(new CultureInfo("")).GetAllStrings(true);

            // bug 1 will crashes because of capital problem
            foreach (string s in invariant)
                Console.WriteLine(s);
            Debugger.Launch();
            // will 3 will crash because of missing resource file
            foreach (string s in specific)
                Console.WriteLine(s);
            foreach (string s in neutral)
                Console.WriteLine(s);
        }
```

**Comment by Anderman** [comment]
I added bug 4 to the example about a wrong exception the is swallowed in `GetResourceNamesFromCultureHierarchy`

**Comment by ryanbrandenburg** [comment]
@Anderman yes, please create separate issues for other bugs, as having multiple bugs on one issue leads to a lot of confusion.

Does #184 address this original bug here? If not please give me an example which addresses only that issue, explaining the input, expected output and actual result.

**Comment by Anderman** [comment]
Yes, Fix 184 looks good to me. I will create 3 other issues
