### ISSUE TITLE
Add functional test that runs the sample site and verifies it works

### ISSUE THREAD

**Issue by Eilon** [aspnet/Localization#148]

**Comment by hishamco** [comment]
@Eilon the functional test is ready shall I make a PR? but I have one doubt, comparing response result looks weird because the previous functional test that done by @kirthik doesn't have much html content.
Any idea
/cc @kirthik

**Comment by hishamco** [comment]
Your thoughts @Eilon?

**Comment by DamianEdwards** [comment]
Appears to have been done https://github.com/aspnet/Localization/tree/dev/test/Microsoft.AspNet.Localization.FunctionalTests

**Comment by hishamco** [comment]
This meant to test the Localization Sample that's in the sample folder not the LocalizationWebsite that done by @kirthik
@Eilon correct me if i'm wrong

**Comment by DamianEdwards** [comment]
Ah yes, you're right.

**Comment by hishamco** [comment]
This functional test is ready shall I make a PR? but I have one doubt, comparing response result looks weird because the previous functional test that done by @kirthik doesn't have much html content.

Your suggestion

**Comment by DamianEdwards** [comment]
I suggest you send the PR and we'll look at it there.

**Comment by hishamco** [comment]
Sure, but i think it's bad idea to compare the html code of sample because it's too big, and if someone add space only it 'll break, I hope you understand what I mean

**Comment by hishamco** [comment]
I think it's fine to compare if piece of code from the sample is localized instead of compare the entire web page

**Comment by DamianEdwards** [comment]
Yeah I'd just ensure a pertinent part of the page is rendered correctly for at least two different cultures (similar to what I did in the functional test addition in aspnet/Entropy#83).

**Comment by hishamco** [comment]
I was looking to the sample that you pushed
thanks

**Comment by hishamco** [comment]
@ryanbrandenburg can you please close this
