### ISSUE TITLE
Localization through resources (.resx)

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Localization#151]
It's already rc1, and after a year I'm still unable to get .resx files working :disappointed:
Something simple like this
```C#
Titles.resx
Titles.fr.resx
```
```C#
public ActionResult Index()
{
	Thread.CurrentThread.CurrentCulture = new CultureInfo("en");
	Thread.CurrentThread.CurrentUICulture = new CultureInfo("en");

	string name = Titles.Name; // Get default en resource

	Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("fr");
	Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("fr");

	string name = Titles.Name;  // Get fr resource, but this always return en one...
}
```
I'm not using any localization packages, because I don't think they are necessary especially in console applications. I even tried
```C#
ResourceManager.GetString(string name, CultureInfo culture)
```
which still doesn't work, I don't get it :confused:

**Comment by hishamco** [comment]
Do you have the example in a repo?

**Comment by Muchiachio** [comment]
[Here's a repo](https://github.com/Muchiachio/LocalKonkole).
I'm using rc1-final dnx.

**Comment by hishamco** [comment]
Let me have a quick look ..

**Comment by hishamco** [comment]
It works fine, it shows **Présent**

**Comment by Muchiachio** [comment]
Interesting, does that mean that my installation is bad? I did updates from beta5 to rc1.

**Comment by hishamco** [comment]
![capture](https://cloud.githubusercontent.com/assets/3237266/11318334/fce54d9a-905e-11e5-93ed-95f0d1ce22f1.JPG)

**Comment by Muchiachio** [comment]
Hehe, you are cheating I run from VS.
It works from command line for me too :o

**Comment by Muchiachio** [comment]
This seems to be tracked in a tooling repo already, back to the cave until rc2 hype ;x

**Comment by hishamco** [comment]
I'm not cheating :smile: , if you mentioned before you are ran it in VS, I will tell you, that you should follow the repo tooling
