### ISSUE TITLE
How to get the resource from the satellite assembly of class library

### ISSUE THREAD

**Issue by noeljiangcc** [aspnet/Localization#154]
I have an ASP.NET 5 class library:

```
ASPNET5ClassLibrary
--Test.cs:
Public Test Class{
public string Msg{  get{ return Resource.ResourceManager.GetString("Msg"); } }
}
--Resource.resx
--Resource.Designer.cs
--Resource.ja.resx

Build ASPNET5ClassLibrary, the nupkg will be generated, its lib contains:
ASPNET5ClassLibrary.dll
ja
--ASPNET5ClassLibrary.resources.dll
```

Then create an ASPNET5App which use the ASPNET5ClassLibrary nupkg as the dependency.
Set the Culture and UI Culture to ja by adding below code in Startup.Configure:
app.UseRequestLocalization(new RequestCulture("ja", "ja"));
Then get the Test.Msg in the View. The Msg always returns the resource from Resource.resx, not the ja one.

How can I get the resource from ja?

BTW, I am using rc1 version.

**Comment by Eilon** [comment]
You generally don't access the resources of one project from another project. The class library project needs to expose some functionality that uses its own resources (e.g. for exceptions, data annotations, etc.).

**Comment by noeljiangcc** [comment]
@Eilon Sorry. My description was wrong. And I have updated.

**Comment by Eilon** [comment]
@noeljiangcc sorry I can't see what was changed. Can you clarify what the scenario is?

**Comment by noeljiangcc** [comment]
Here is detail steps:
1. Define a Test class in an asp.net 5 class library, its implementation is:
Public Test Class{
public string Msg{ get{ return Resource.ResourceManager.GetString("Msg"); } }
}
And there are also files of the resources:
--Resource.resx
--Resource.Designer.cs
--Resource.ja.resx

2.Then add the class library as the dependencies of an asp.net 5 web app.

3. Create a Test instance in the Index action of HomeController, and get the Test.Msg property. Code is like:
public ActionResult Index(){
ViewBag.Msg = new Test().Msg;
return View();
}

4. Add below codes to Startup.Configure method to test the app in ja culture:
app.UseRequestLocalization(new RequestCulture("ja", "ja"));

5. Run the web app, debug and watch the value of Test.Msg.
It returns the resource defined in Resource.resx, not the ja one.

Why not return ja resource? How can I get the resource from ja?

**Comment by Eilon** [comment]
Re-opening so the team can review in the next bug review meeting (next week).

**Comment by Eilon** [comment]
@DamianEdwards can you try to repro this? This might just not work from VS due to the known issue (which will be fixed with dotnet-cli).

**Comment by muena** [comment]
@Eilon I have the same issue as @noeljiangcc and just tried to run the project from clr with dnx web: The localization works without problems!
So you're right, it's a VS issue.
Can you please provide me a link for more information about that VS issue?
Thanks!

**Comment by Eilon** [comment]
@muena unfortunately not a lot of specific info to share on this. It has to do with how VS launches the DNX applications. We're making some changes to how apps are compiled and run and that will resolve this issue.

**Comment by Eilon** [comment]
@DamianEdwards closing because this sounds like another instance of https://github.com/aspnet/dnx/issues/3047.
