### ISSUE TITLE
Change ConcurrentDictionary in ResourceManagerStringLocalizer to a regular dictionary

### ISSUE THREAD

**Issue by Eilon** [aspnet/Localization#156]
See: https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L21-L22

This code uses a `ConcurrentDictionary` even though the code is run on a single thread. It was once part of some static caching system, but that is long since gone, so it can safely be changed to a regular dictionary.

This was found while looking at https://github.com/aspnet/Localization/issues/142.

**Comment by DamianEdwards** [comment]
So it turns out that this member **really** needs to be on the factory, as the performance once a page is localized right now is absolutely terrible (like, >6s to load the page). Making this cache global returns it to sane numbers after the initial render (<20ms).

**Comment by ryanbrandenburg** [comment]
So @DamianEdwards you're saying that part of making that cache a singleton will be that this has to stay a ConcurrentDictionary and therefore this bug is obsolete?

**Comment by Eilon** [comment]
@ryanbrandenburg I'm guessing the cache is just in the wrong place, maybe? As in, instead of being on the localizer, which is transient (so caching is almost useless), the cache needs to move to the factory, which is a singleton.

**Comment by DamianEdwards** [comment]
Yeah I have a prototype, I'll send a PR.

**Comment by DamianEdwards** [comment]
Fixed in 96462b9528da1b01d5f1759f28e49f2fb7cb2d7d
