### ISSUE TITLE
Perf: Reduce number of `AssemblyName`s allocated in even minimal scenarios

### ISSUE THREAD

**Issue by dougbu** [aspnet/Localization#159]
In a conversation in aspnet/Mvc#3661, we discussed 2.8 ~~GB~~ MB of `AssemblyName`s allocated over 3000 requests with a small view containing just two uses of a `ViewLocalizer`. Need to dive deeper into this.

[Details](https://github.com/aspnet/Mvc/pull/3661#issuecomment-161429284):
Most of the allocations are internal to `ResourceManager` and trace back through `Microsoft.Extensions.Localization.ResourceManagerStringLocalizer.GetStringSafely(...)`. `ResourceManagerStringLocalizer` has a cache of _missing_ resources (well, manifests) but that's per-instance. Not sure why `ResourceManagerStringLocalizerFactory` (a singleton) doesn't own that cache nor why only `ResourceManagerStringLocalizer.GetAllStrings()` uses the factory's resource string cache.

The few allocations outside `GetStringSafely()` are shown below.
![assemblyname](https://cloud.githubusercontent.com/assets/6431421/11543215/453d64c6-98f0-11e5-9bbc-ccc6dc0da46d.png)

@DamianEdwards [suggested](https://github.com/aspnet/Mvc/pull/3661#issuecomment-161448673) making the `ResourceManagerStringLocalizer`'s missing manifest cache global and "cache whatever makes sense".

**Comment by rynowak** [comment]
That would be **mb** not **gb**

**Comment by rynowak** [comment]
IIRC in the context of the site being tested the `AssemblyName`s were still above 1% of the allocations right?

**Comment by dougbu** [comment]
> the AssemblyNames were still above 1% of the allocations right?

Just a touch over 1.5% of the total allocations in the scenario.

**Comment by DamianEdwards** [comment]
This should be run again after 96462b9528da1b01d5f1759f28e49f2fb7cb2d7d

**Comment by Eilon** [comment]
@dougbu please re-measure now that caching is correctly implemented. We believe that the cost should now be negligible.

**Comment by dougbu** [comment]
`AssemblyName` no longer shows up when measuring allocations in a `ViewLocalizer` scenario. In fact allocations for our `LocalizedViews` scenario now look fairly similar to the `BasicViews` one.

The remaining glaring problem in the `LocalizedViews` scenario is inefficiency in `LocalizedHtmlString.FormatValue()`, a `private` method used within `WriteTo()`. But that method is also incorrect and I expect this problem to go away when I fix aspnet/MVC#3659.
![capture](https://cloud.githubusercontent.com/assets/6431421/12489937/c91f79c4-c027-11e5-8a70-8c33ffb65555.png)

**Comment by dougbu** [comment]
Closing as no repro since remaining problems in scenario are not in the repo.
