### ISSUE TITLE
Text Direction

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#16]
Indeed getting text direction is tiny feature but very useful in almost localization frameworks, also it is helpful for the front-end developers to control the direction or flow of the markup.

The implementation will be something like:
```csharp
public enum FlowDirection
{
     LeftToRight,
     RightToLeft
}

public FlowDirection FlowDirection
{
     get
     {
          return CurrentCulture.TextInfo.IsRightToLeft? FlowDirection.RightToLeft : FlowDirection.LeftToRight;
     }
}
```

**Comment by DamianEdwards** [comment]
What are you proposing this would be added to? We expose the current culture information as standard `CultureInfo` objects so the text direction is easily determined via the `IsRightToLeft` property. We don't intend on adding new API around what defines a culture itself.

**Comment by hishamco** [comment]
@DamianEdwards I am agree that we expose the current culture information as ```CultureInfo``` object, IMHO this tiny wrapper is very helpful while working with multilingual websites instead of checking ```cultureInfo.TextInfo.IsRightToLeft``` ourselves. 
FYI I saw many wrappers in aspnet repos such as https://github.com/aspnet/Hosting/blob/c390d47317c8d0bdac35b1a22d4c180ea79791bb/src/Microsoft.AspNet.Hosting.Abstractions/HostingEnvironmentExtensions.cs#L20 which is basically reduce the effort for developers

**Comment by DamianEdwards** [comment]
In this case I'm not really convinced an existing simple boolean property requires an extension method for the reverse case. We'd be adding a *lot* of extension methods if that's the case.

**Comment by hishamco** [comment]
I think there's no need to introduce an extension method anymore, we can make the property like this:
```csharp
public FlowDirection FlowDirection
{
     get
     {
          return CurrentCulture.TextInfo.IsRightToLeft? FlowDirection.RightToLeft : FlowDirection.LeftToRight;
     }
     set
     {
          CurrentCulture.TextInfo.IsRightToLeft = (value == FlowDirection.RightToLeft);
     }
}
```
