### ISSUE TITLE
Examples doesn´t work with 1.0.0-RC1-update1

### ISSUE THREAD

**Issue by lurumad** [aspnet/Localization#163]
I've downloaded localization examples and running on my machine. When I try to change culture and uiculture from combos and click on "go QS" or "go cookie" buttons the **Hello** text doesn't translate to the selected language. StringLocalizer said that resource can not found.

Regards!

**Comment by hishamco** [comment]
@lurumad I see you are closed the issue, are you still facing the issue or not

**Comment by lurumad** [comment]
Hi, I've seen another thread with teh same issue https://github.com/aspnet/Localization/issues/153 

For this reason I've closed this issue. It was my fault sorry ;)

**Comment by hishamco** [comment]
I see, please follow up that issue ..
