### ISSUE TITLE
[Bug] Unable to run Microsoft.Extensions.Localization.Tests

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#171]

**Comment by DamianEdwards** [comment]
![image](https://cloud.githubusercontent.com/assets/249088/11802367/bf9bc0ba-a2a4-11e5-894c-119c9606f946.png)

And on the CI: https://travis-ci.org/aspnet/Localization

You'll need to provide more detail.

**Comment by hishamco** [comment]
What it made me crazy that it runs well on the CI, have a look to the exception
![capture](https://cloud.githubusercontent.com/assets/3237266/11810445/3ce336da-a33f-11e5-8171-0d40cf2e6b95.JPG)
```IOptionsMonitor<>``` not found, because there's no reference in the project.json

**Comment by DamianEdwards** [comment]
can you try `git clean -xdf` in the repo root then run `build.cmd`

**Comment by hishamco** [comment]
It works :smile: 
thanks
