### ISSUE TITLE
[Bug] Reacting to new Hosting API makes CI Tests fails

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#183]
After the last commit that react to Hosting APIs, seems AppVoyer & Travis fails in all the repos that this commit applied to

/cc @DamianEdwards @JunTaoLuo

**Comment by JunTaoLuo** [comment]
The updated packages have not been pushed to aspnetcidev. You can use the aspnetvolatiledev feed instead to get the newest packages.

**Comment by hishamco** [comment]
I see, thanks @JunTaoLuo
