### ISSUE TITLE
Resource file are case sensitive or wrong resource name is generated

### ISSUE THREAD

**Issue by Anderman** [aspnet/Localization#185]
I created this [repository](https://github.com/Anderman/Issue143) with 4 bugs
The resource search for is
`localize.Resources.localize.Controllers.HomeController.resources`
But if I check with Assembly.GetManifestResourceNames() only
`localize.Resources.Localize.Controllers.HomeController.resources` 
is available
see case problem in
localize
Localize

**Comment by DamianEdwards** [comment]
In this case, it's because you have inconsistent naming between your files and namespaces (your resx files have the uppercase "L", but your project folder name and namespace is lowercase "l").

**Comment by Anderman** [comment]
@DamianEdwards I known that that is the problem. But I thought that project files where not case sensitive in windows. Because the statement `T.WithCulture(new CultureInfo(""))["Hello"]` works.
This statement can find the file.
