### ISSUE TITLE
specific and neutral Resource files are missing 

### ISSUE THREAD

**Issue by Anderman** [aspnet/Localization#186]
I created this [repository](https://github.com/Anderman/Issue143) with 4 bugs
In this repsotiory are 3 .resx files

Only one is available in the application
 check with `Assembly.GetManifestResourceNames()` only
`localize.Resources.Localize.Controllers.HomeController.resources` is available

**Comment by DamianEdwards** [comment]
Did you run your application from Visual Studio or the command line? The resource embedding doesn't work correctly if you launch from VS directly.

**Comment by Anderman** [comment]
VS didn't create the designer.cs files for the other 2. Rename fixed it
