### ISSUE TITLE
Rename IRequestCultureStrategy to IRequestCultureProvider

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Localization#19]
'Cos it's more "us"

**Comment by hishamco** [comment]
This implies to rename the following classes as well ```RequestCultureStrategy```, ```AcceptLanguageHeaderRequestCultureStrategy```, ```QueryStringRequestCultureStrategy```, ```CookieRequestCultureStrategy``` and ```CustomRequestCultureStrategy```

**Comment by DamianEdwards** [comment]
:+1:
