### ISSUE TITLE
Custom IStringLocalizer and DataAnnotations strange behaviour

### ISSUE THREAD

**Issue by cspaniard** [aspnet/Localization#192]
Hello,
I don´t think it is a true dup, but I apologize if it is. 

I wrote a simple custom IStringLocalizer and it works fine. If I use it from the view via `@inject`, no problem at all.

The issue comes when tag helpers like `input` try to use it, from the DataAnnotations localization. I don't think it is the tag-helper's fault. I believe it is the DataAnnotations localization process.

My custom IStringLocalizer `public LocalizedString this[string name]` gets called during the data annotations localization process, however in the `name` parameter I get the name of the field it is trying to localize, but no hint on what the error message is. When used from the view, I get the message I need to localize in the `name` parameter.

Any ideas, why I get the name of field instead of the `ErrorMessage` string ?

I use the following in `Startup.cs` 

```c#
services.TryAdd(new ServiceDescriptor(
    typeof(IFileStringLocalizerCache),
    typeof(FileStringLocalizerCache),
    ServiceLifetime.Singleton));

services.TryAdd(new ServiceDescriptor(
    typeof(IStringLocalizerFactory),
    typeof(FileStringLocalizerFactory),
    ServiceLifetime.Singleton));

services.TryAdd(new ServiceDescriptor(
    typeof(IStringLocalizer),
    typeof(FileStringLocalizer),
    ServiceLifetime.Transient));

services
    .AddMvc()
    .AddViewLocalization()
    .AddDataAnnotationsLocalization(o => 
        o.DataAnnotationLocalizerProvider = (t, f) => f.Create(typeof(IStringLocalizer)));
```

Futhermore, and I think the following has been talked about in other issues, the behaviour is not consistent across different data annotations.

I get called with
```c#
[Required(ErrorMessage = "some message")]
[StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
```
and I do not get called for localization with
 ```c#
[Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
```

Am I doing something wrong ? Should I wait until things settle down with dev ? I know there is a lot going on with Localization in general.

Any help will be greatly appreciated.

TIA,
David

**Comment by hishamco** [comment]
Can you refer to this issue #175

**Comment by Eilon** [comment]
@cspaniard is this with the latest RC2 bits? We think all the issues around this have been fixed.

BTW `IStringLocalizer` does not itself come from DI, so there is no use in registering it there. Just keep the factory registration and it will manufacture the localizers.

Also, this code looks wrong:

```c#
 o.DataAnnotationLocalizerProvider = (t, f) => f.Create(typeof(IStringLocalizer)));
```

It's always passing in the same type to the localizer factory - and beyond that, it's passing in the `IStringLocalizer` itself, which is never itself localized.

There's probably no need to set this property at all - the default behavior will create a localizer for whatever type is being localized.

**Comment by cspaniard** [comment]
Wow @Eilon, thanks for the explanation... I appreciate it. However, I am not sure I understand it all... ;)

Your 1st question: I tried it in RC1. I have not done anything with RC2 yet.

Your comment: 
>BTW `IStringLocalizer` does not itself come from DI, so there is no use in registering it there. Just keep the factory registration and it will manufacture the localizers.

Do you mean in things like:
```c#
services.TryAdd(new ServiceDescriptor(
    typeof(IStringLocalizer),
    typeof(FileStringLocalizer),
    ServiceLifetime.Transient));
```
I thought that was needed (along with the factory) when you want to provide a custom `IStringLocalizer` implementation. Somehow the system needs to know to use your custom implementation vs. default one. If not, how does it know?  I must admit I am a little lost here. ;)

About your last comment, since docs are not yet done I was not sure. I assumed it was needed for the `DataAnnotationsLocalization` know again what provider implementation to use. But if it is not needed, even better.

Having said all that, I am looking forward to trying all this in RC2. I hope all this "strange/inconsistent" behaviour with Data Annotations gets better.

Thanks,
David

**Comment by Eilon** [comment]
Sorry for the delay. Right, you do not customize `IStringLocalizer` itself, but rather just the factory - that's what goes in DI. The system knows that in order to create an `IStringLocalizer` it needs to go to the registered factory (which you can customize) and create whatever it wants.

For Data Annotations you can check out the sample project at https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/, which is the default MVC project but with a lot of localization enabled.
