### ISSUE TITLE
LocalizationSample doesn't work as expected on RC1-update1

### ISSUE THREAD

**Issue by zibzib** [aspnet/Localization#193]
Hi,
When I play with LocalizationSample on RC1-update1 (I tried with RC1-final1 too), I can see that CultureInfo.CurrentCulture and CultureInfo.CurrentUICulture are set correctly whenever I change the language.
However, the string returned by ResourceManager is always "Hello". I suspect it doesn't load or know about the satellite resource assemblies. I don't know how to debug that since everything is built in-memory. But when I check "Produce outputs on build", I see the satellite assemblies generated correctly.

Can you please confirm this issue? Any idea on what might be going on here?

Thanks.

**Comment by hishamco** [comment]
This is duplicate to issue #163

**Comment by zibzib** [comment]
I can confirm.
Thanks!

**Comment by ThomasKold** [comment]
I can also confirm this problem
