### ISSUE TITLE
Resources files is not working 

### ISSUE THREAD

**Issue by chemitaxis** [aspnet/Localization#197]
Hi, I have tested the example using QueryString and Cookie, and all works fine except the "Hello" message, is always showing "English version".

I have tested with RC1.

Thanks.

**Comment by hishamco** [comment]
Are you using VS or command line tools?

**Comment by chemitaxis** [comment]
Hi, I'm using VS, Right click in Example Project, and Debug New Instance. Thanks!

**Comment by hishamco** [comment]
This is a common issue in VS if i'm not wrong, let me find the issue that you can track to solve this ..

**Comment by hishamco** [comment]
Can you have a look to this #163

**Comment by chemitaxis** [comment]
Ok, thanks!! ;)

**Comment by Eilon** [comment]
Yup, known issue that will be fixed in the next release. For now you can run from the command line to get the right resources to load.
