### ISSUE TITLE
Switch from System.Resources.ReaderWriter package to new separate Reader and Writer packages

### ISSUE THREAD

**Issue by Eilon** [aspnet/Localization#199]
The System.Resources.ReaderWriter was split into two packages: System.Resources.Reader and System.Resources.Writer.

We need to switch to use the new packages (or just one of them, if we need only one). It's currently in use here:
* https://github.com/aspnet/Localization/blob/489250a8e1c97d2b415b1c8994f1943b6d229d73/src/Microsoft.Extensions.Localization/project.json#L23

This appears to be the only real usage of this assembly. (It's also used in DNX, but that won't be an issue in the near future.)

Separately, we'll have to update the [NuGetPackageVerifier list](https://github.com/aspnet/Coherence-Signed/blob/c5c5ce686e33a5d683e36a8ea15217e9ecb339b9/tools/NugetPackageVerifier.json#L938) to change the metadata for this, but we'll presumably see that failure once we accept the new bits.

**Comment by hishamco** [comment]
I think this should be closed after merge

**Comment by ryanbrandenburg** [comment]
Ah, thanks for the reminder @hishamco
