### ISSUE TITLE
Custom Cultures not working with RequestLocalizationMiddleware

### ISSUE THREAD

**Issue by mmoron** [aspnet/Localization#203]
### Title
Custom Cultures not working with `RequestLocalizationMiddleware`

### Functional impact
It is impossible to use custom settings for Cultures when using `RequestLocalizationMiddleware`

### Minimal repro steps
- Create custom CultureProvider
```
public class SampleCultureProvider : RequestCultureProvider
{
    public override Task<ProviderCultureResult> DetermineProviderCultureResult(HttpContext httpContext)
    {
        var providerResultCulture = new ProviderCultureResult("en-US");
        return Task.FromResult(providerResultCulture);
    }
}
```
- Create custom localization options (changed CurrencySymbol in this example)
```
private RequestLocalizationOptions CreateLocalizationOptions()
{
    var supportedCulturesList = new List<CultureInfo>
    {
        new CultureInfo("en-US", true) { NumberFormat = { CurrencySymbol = "kr" } }
    };

    var localizationOptions = new RequestLocalizationOptions
    {
        SupportedCultures = supportedCulturesList,
        SupportedUICultures = supportedCulturesList
    };
            
    localizationOptions.RequestCultureProviders.Clear();
    localizationOptions.RequestCultureProviders.Add(new SampleCultureProvider());
    return localizationOptions;
}
```
- Add RequestLocalizationMiddleware using these options
```
public void Configure(IApplicationBuilder app)
{
    app.UseIISPlatformHandler();

    var globalizationOptions = this.CreateLocalizationOptions();
    app.UseRequestLocalization(globalizationOptions, new RequestCulture(new CultureInfo("en-GB")));

    (...)
}
```
- display text using currency formatting
```
public void Configure(IApplicationBuilder app)
{
    (...)
    app.Run(async (context) =>
    {
        await context.Response.WriteAsync(123.ToString("C"));
    });
}
```
Sample solution reproducing this bug attached: [RequestLocalizationMiddlewareBug.zip](https://github.com/aspnet/Localization/files/98886/RequestLocalizationMiddlewareBug.zip)

### Expected result
Changed currency symbol should be displayed: **kr123.00**

### Actual result
Default currency symbol is used: **$123.00**

### Further technical details
Problem is - most likely - caused by `CultureInfoCache`. When `GetCultureInfo` is called `supportedCultures` are checked to see whether requested culture is supported. 

```
if (name == null || supportedCultures == null ||
    !supportedCultures.Any(supportedCulture => string.Equals(supportedCulture.Name, name, StringComparison.OrdinalIgnoreCase)))
{
    return null;
}
```
Later on, however, instead of adding provided culture to the cache new culture is created with a given name and added
```
var entry = _cache.GetOrAdd(name, n =>
{
    try
    {
        return new CacheEntry(CultureInfo.ReadOnly(new CultureInfo(n)));
    }
    catch (CultureNotFoundException)
    {
        (...)
    }
});
```
I guess that using
```
var culture = supportedCultures.Single(supportedCulture => string.Equals(supportedCulture.Name, name, StringComparison.OrdinalIgnoreCase));
return new CacheEntry(CultureInfo.ReadOnly(culture));

```
instead of
```
return new CacheEntry(CultureInfo.ReadOnly(new CultureInfo(n)));
```
should fix this

**Comment by hishamco** [comment]
@mmoron have you look to this https://github.com/aspnet/Localization/blob/dev/test/Microsoft.AspNet.Localization.Tests/CustomRequestCultureProviderTest.cs
and I'll try to have a look to your source later ..

**Comment by mmoron** [comment]
@hishamco I did. This test is not trying to change default settings for a given culture. I need to change some culture specific settings (currency symbol for example).

**Comment by hishamco** [comment]
The test will provide a culture like what you did before, and it will reflects to everything related to culture including currency. I will check your app soon ..

**Comment by mmoron** [comment]
the test provides a culture like I do but it is not trying to change anything in this culture:
```
SupportedCultures = new List<CultureInfo>
{
   new CultureInfo("ar")
}
```
it will use whatever is default for "ar" culture. I want to deliberately change currency symbol for "en-US":
```
var supportedCulturesList = new List<CultureInfo>
{
   new CultureInfo("en-US", true) { NumberFormat = { CurrencySymbol = "kr" } }
};
```

**Comment by hishamco** [comment]
I think you are forget to add ```services.AddLocalization();``` in ```ConfigureServices``` method

**Comment by mmoron** [comment]
I don't think it matters. I just added it now to my test solution and result is the same.

**Comment by hishamco** [comment]
@mmoron ```services.AddLocalization()``` if very important in case to use underlying localization API's, furthermore i notice you are using **en-GB** as default culture while it's not declared in supported culture. Nothing but if you make the **en-US** you will not see any change in the currency symbol, so that's why I will debug and trace the app with disabling the caching to see if it is the reason behind this issue

**Comment by Eilon** [comment]
@DamianEdwards ?

**Comment by DamianEdwards** [comment]
Yeah I think we don't handle this case at all. We just don't consider that a culture name may map to a completely custom culture. I'd like to think more deeply about how we should go about supporting this so it's too late for now, but the workaround for apps is pretty trivial (just add your own middleware that stamps the custom culture on to the thread/request).

**Comment by rubenprins** [comment]
@DamianEdwards, What do you mean with "it's too late now"? And how is one to "stamp the custom culture" when you erase any trace of the custom culture? This is nowhere near trivial.

If I add a culture like `en-NL` to `SupportedCultures`, it will get replaced by the default `en` culture `en-US`, even when my culture is explicitly provided via `SupportedCultures` **and** it is read only? What if both cultures are registered as supported? Which one was selected?

It simply does not make sense to blindly call `CultureInfo.ReadOnly(new CultureInfo(name))`, even for explicitly provided read only cultures. Why even route `SupportedCultures` via `CultureInfoCache`? I have provided you with the culture already! I'd call this broken.

Or do you mean: don't use `AddLocalization()` at all and reimplement/fork the package if you want to use custom cultures? The fix seems to be a nobrainer to me, but I might be missing something.

**Comment by hishamco** [comment]
@rubenprins it's too late because now we 're in RC, and it's rare to add a new feature or fix a bug without break something else. FYI this has been moved to backlog

**Comment by gzak** [comment]
@rubenprins I think you're not really supposed to modify the properties of existing cultures on the fly (could be wrong on that). You can, however, register "overrides" in advance, as outlined in [this article](https://msdn.microsoft.com/en-us/library/system.globalization.cultureandregioninfobuilder.aspx?f=255&mspperror=-2147217396#Anchor_5).

**Comment by rubenprins** [comment]
@gzak, First of all, AFAIK *CultureAndRegionInfoBuilder* does not exist on .NET Core, and is very Windows-specific anyway. Second, registering a culture that way requires administrative privileges and installs the culture globally, for all applications, and I do not know of a way you can do this when you deploy a single web application either. So it's a _really_ awful way to handle application-specific overrides and additions to the cultures infrastructure.

Finally, CultureInfos created this way work just fine. It's this specific API that chooses to not allow them. There's nothing in the CultureInfo infrastructure that requires you to globally register a culture to be able to use it. (Although a runtime-only CultureInfo.Register would be even better.)

**Comment by Eilon** [comment]
Let's take another look at this, e.g. by writing a console app and seeing how custom cultures work in .NET Core.

**Comment by macgyver76** [comment]
In my case I need to change the `ShortDatePattern` for specific culture. What's the solution for this?

**Comment by mmoron** [comment]
For now you could write your own `RequestLocalizationMiddleware` and skip using `CultureInfoCache` in it. That's (more or less) what I've done and it worked.
