### ISSUE TITLE
[Bug] Unable to locate Dependency

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#204]
![capture](https://cloud.githubusercontent.com/assets/3237266/12485239/ee01df24-c06e-11e5-814d-68afa5704775.PNG)
It's related to #200 
/cc @ryanbrandenburg @Eilon

**Comment by pranavkm** [comment]
This will get fixed when the packages get published to aspnetcidev. We should have them published by EOD.

**Comment by hishamco** [comment]
@pranavkm what is the suitable feed that i should use to make this run locally?

**Comment by pranavkm** [comment]
`https://www.myget.org/f/aspnetvolatiledev/api/v3/index.json` has these packages, but I'd recommend using it since it doesn't necessarily have a coherent set of packages.

**Comment by hishamco** [comment]
Thanks

**Comment by Eilon** [comment]
Please use https://www.myget.org/f/aspnetvnext in general.

**Comment by hishamco** [comment]
@Eilon aspnetvnext is already there in nuget.config, but after i added the feed that @pranavkm suggest the previous exception is gone, but the app can't recognize ```WebApplicationBuilder``` and ```WebApplicationConfiguration```

**Comment by hishamco** [comment]
Still not working?!!

**Comment by ryanbrandenburg** [comment]
@hishamco what isn't working and what feeds are you currently using? If you removed a feed did you clean out your dnu cache afterward?

**Comment by hishamco** [comment]
@ryanbrandenburg unable to locate ```System.Resources.Reader``` and ```System.Resources.Writer```, the feeds that i'm using shown in the pictures above, but I didn't clear out the dnu cache .. i will do it now ..

**Comment by hishamco** [comment]
@ryanbrandenburg the previous errors are gone but i'm getting another error when I run ```dnx web```
![capture](https://cloud.githubusercontent.com/assets/3237266/12651619/4db40ecc-c5f8-11e5-9dd8-da38ef1a20b4.PNG)

**Comment by ryanbrandenburg** [comment]
Your first error looks like a straightforward missing "using" but I assume you already checked that. Your second one is a bit more interesting, my best guess without seeing it is that you're getting mismatched versions of IApplicationBuilder somehow? It sounds like you cleared the dnu cache, did you also get the .dnx/packages stuff? If so could you build me a minimum repro and send it my way?

**Comment by hishamco** [comment]
It works fine after dnx/packages .. thanks
