### ISSUE TITLE
ResX Public Code Generator

### ISSUE THREAD

**Issue by YZahringer** [aspnet/Localization#206]
Is it possible to continue to use the ResX code generation? I prefer it because there intellisense and compile-time error if missing ressource.

The problem is that we can not change "Access Modifier" to put the public code generation. The views can not access the "internal" properties of generated code.

The correction of this is planned? Or use of the ResX generated code is no longer supported?

**Comment by hishamco** [comment]
I think this is a known issue in VS if I'm not wrong

**Comment by Eilon** [comment]
@YZahringer this is being fixed in VS:
* https://github.com/aspnet/Tooling/issues/339
* https://github.com/aspnet/Tooling/issues/270
