### ISSUE TITLE
Remove application path ifdefs used to locate tests once CoreCLR tests are run using dotnet

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Localization#210]
https://github.com/aspnet/Localization/blob/dev/test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationSampleTest.cs#L14-L19
https://github.com/aspnet/Localization/blob/dev/test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs#L15-L19

**Comment by pranavkm** [comment]
Self assigning it as follow up https://github.com/aspnet/Localization/issues/198

**Comment by Eilon** [comment]
:+1:

**Comment by pranavkm** [comment]
Unfortunately switching to CLI for tests didn't solve this issue. The location where we publish tests in full desktop and CoreCLR is different and consequently the differences persist. An alternative would be to walk up to sln dir and figure relative paths from there (which would be less brittle). I'm going to work on making that change here + Mvc.
