### ISSUE TITLE
Resources not working in MVC 6 application

### ISSUE THREAD

**Issue by chemitaxis** [aspnet/Localization#215]
I have tested the example using an empty ASP.NET 5 web app and it's not working. The resources files is not working. I have tested using dnx web and not VS debug.

The problem is DI controller, the resources files is not working. In Razor Views you can't translate like you did in MVC5.

Please upgrade the example for a complete MVC 6 web app, a lot of question in stackoverflow about it. Very confused right now.

Thanks.

**Comment by hishamco** [comment]
Which example you mean? because the sample attached with the source working fine

**Comment by chemitaxis** [comment]
Ok, I solved it... I will update my example on GitHub tomorrow (https://github.com/chemitaxis/Localization.StackOverflow) . In this example you can use the localization on RC1 on Razor Views. 

I have created a _ViewImports, and add it:

@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
@using System.Threading.Tasks
@using AspNet5Localization
@using AspNet5Localization.Resources
@using Microsoft.AspNet.Mvc.Localization
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<AmazingResource> SR
After, I have created a HomeController and Views/Home/Index.cshtml file.

Like I have injected in my Views in _ViewImports the IStringLocalizer SR I can use it in my Razor Views using just:

@SR["Name"]

I don't know if it the best way to do that, but it works. If someone can explain the best way to do that, please answer here.

Thanks.

**Comment by hishamco** [comment]
Please refer to the following examples [LocalizationSample.Web](https://github.com/aspnet/Mvc/tree/dev/samples/LocalizationSample.Web) and [Localization.StarterWeb](https://github.com/aspnet/Entropy/tree/dev/samples/Localization.StarterWeb)

**Comment by Eilon** [comment]
Closing because this looks like it was answered.
