### ISSUE TITLE
Azure localization not working like with VS compilation

### ISSUE THREAD

**Issue by chemitaxis** [aspnet/Localization#218]
Hi, I have tested Localization in Azure, and it's not working like when you compile in VS.

If I run in local, with _dnx web_ it's working fine, but when I upload my project to Azure like Web App, it not working.

Any ideas? Maybe other Repository Issue? Thanks

**Comment by chemitaxis** [comment]
Sorry, cache errro, close the issue please.  Thanks.

**Comment by hishamco** [comment]
Strange!! it should work

**Comment by hishamco** [comment]
Cache error .. it happens :smile:
@chemitaxis can you please close the issue

**Comment by chemitaxis** [comment]
Closed ;)
