### ISSUE TITLE
Thinking about Culture Caching

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#224]
Storing the entire ```CultureInfo``` object may it causes some issues such as Number & DateTime Formats. IMHO caching the culture name may enough to avoid such issues, hope to heard your thoughts

**Comment by Eilon** [comment]
What exactly is the issue? What doesn't work?

**Comment by hishamco** [comment]
Try to change the number or date format in supported culture list, you will notice that nothing will change because the current cache mechanism store the entire culture object based on its name, have a look to this line https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs#L43, I think caching name enough to solve this issue because we can't guarantee no one will change a piece of information in the supported list

**Comment by Eilon** [comment]
Are you talking about changing the format of an existing CultureInfo object? Is that even a thing? Even if it's possible (and I don't see how exactly), I would say that changing CultureInfo properties *while the app is running* is not supported.

**Comment by hishamco** [comment]
After checking the issues, issue #203 is one of the cases that I mean

**Comment by Eilon** [comment]
Is this an exact dup of #203? If it's different, how is it different?

**Comment by hishamco** [comment]
The issue #203 shows one case (currency) of what i'm talking about, if the fix will cover all the formats dates, numbers .. etc, of course i will close this

**Comment by Eilon** [comment]
Currency was just an example. I'm sure if we fix this it would be a complete fix, not for just one property.

**Comment by hishamco** [comment]
Sure, hopefully if this will got fix in V1

**Comment by Eilon** [comment]
That is not currently planned.
