### ISSUE TITLE
Unable to run Unit Tests

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#226]
I'm trying to run a unit tests with no luck, after that I looked to the project.json seems there is a lot of changes in unit tests such as **"testRunner": "xunit"** it's long time for me to use the unit tests. i don't know if there's a way to run them, what I tried are **dnx test** and **dotnet test** with no luck

FYI when I ran the latest command i got this error **Could not resolve coreclr path**

**Comment by pranavkm** [comment]
Does running `build` succeed?

**Comment by hishamco** [comment]
![capture](https://cloud.githubusercontent.com/assets/3237266/13650821/9235dc42-e655-11e5-9e77-73e159e754f8.PNG)

**Comment by pranavkm** [comment]
That looks like you haven't run restore. What does running `build.cmd` from the repo root look like?

**Comment by Eilon** [comment]
And remember to run `git clean -xdf` first.

**Comment by hishamco** [comment]
I already restore the dependencies of the test project, but I want to know when shall i execute ```build.cmd```?
Now I 'll follow these steps:

1. ```git clean -xdf```
2. Remove dnx packages
3. Remove dnu cache
4. Run ```build.cmd'``

and I will give you the result

**Comment by pranavkm** [comment]
That sounds about right. FYI - all our repos now use dotnet-cli to build. Consequently it'll use `%UserProfile%/.nuget/packages` as the packages dir on your machine and `%LocalAppData%/nuget/v3-cache` as the HTTP cache.

**Comment by hishamco** [comment]
Fetching the latest source updates and running the ```build.cmd``` solve the issue with ```dotnet test```, i think ```dnx test``` is gone Am i right?
Please let me know when shall i run ```build.cmd``` because I suffered many times from such things

**Comment by hishamco** [comment]
Thanks @pranavkm

**Comment by hishamco** [comment]
Another related question, how can i run the tests in vs (netstandardapp1.5), because i'm getting an error

**Comment by Eilon** [comment]
You can't run them in VS until the new tooling comes out.

**Comment by hishamco** [comment]
I expect that :smile: , thanks a lot
