### ISSUE TITLE
IStringLocalizer.GetAllStrings should support an arg to specify culture walk behavior

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Localization#23]
Depends on #18

Currently, `IStringLocalizer.GetAllStrings` will return the union of all strings for the current culture and all ancestors of the current culture. E.g. if the current culture is "en-US" and it contains a single string "Hello", and the culture "en" contains a single string "Goodbyte", the call to `IStringLocalizer.GetAllStrings` for "en-US" will return both the "Hello" and "Goodbye" strings.

This behavior may not always be desirable (e.g. it differs to how `ResourceManager.GetResourceSet` works). As such, we should support a way to specify the behavior during the call, e.g. `GetAllStrings(includeAncestorCultures: false);`

The default behavior should still be to include strings from ancestor cultures.

**Comment by DamianEdwards** [comment]
Interested in your thoughts @davidfowl @muratg @Eilon @lodejard

**Comment by muratg** [comment]
I like it.

**Comment by glen-84** [comment]
So if you have "colour" in "en", and nothing in "en-US", the translation for "en-US" would be "colour", which is not correct until such time as you "override" it as "color" in "en-US"? Perhaps it should be off by default to avoid unexpected behaviour?

(sorry, I know my feedback was not requested :fearful:)

**Comment by DamianEdwards** [comment]
@glen-84 this behavior is in line with the existing `ResourceManager.GetString` behavior, that walks the culture graph until it finds a string. We're simply adding that same behavior to the `GetAllStrings` scenario. People can call the overload with the behavior they desire.

**Comment by glen-84** [comment]
Okay, fair enough. I guess.
