### ISSUE TITLE
Sample Code in master branch is is not localizing

### ISSUE THREAD

**Issue by israelito3000** [aspnet/Localization#240]
Hello, I was attempting to localize strings but seems like the resource files are not proper loaded, even your sample which have a localized string "Hello" always shows Hello, I attempt to change the Thread Culture In an ActionFilter, in a Middleware but nothing seems to work. The localized resources are not loaded: "Filename.es-ES.resx" it only loads the default resource file Filename.resx

**Comment by hishamco** [comment]
Use the dev branch, because the master branch is 107 commits behind dev

**Comment by israelito3000** [comment]
Ok, the problems is related to Visual Studio, in order to any localization works we have to run the project using the command line: dnx web.

I have another question, I see that in the dev branch everything is migrating from Microsoft.AspNet to Microsoft.AspNetCore, I am working in a prerelease now and my concern is if all Microsoft.AspNet.* is going to be renamed to Microsoft.AspNetCore and the older is going to disappear?? Seems like there is a ton of breaking changes on a Release Candidate that make me feel nervous, could you tell me anything about this? 

Thank you.

**Comment by hishamco** [comment]
@israelito3000 I was using the old bits too, don't worry the rename break change is happened in RC2, but if you have the RC1 tools for Visual Studio you can play with the bits nothing but you will miss some of the new changes and fixes. BTW if you track the latest changes the team is moving to use DotNet CLI instead of DNX Commands for cross-platform scenario.
FYI couple weeks ago Damian Edwards mentioned the new ASP.NET Core tools for Visual Studio, so you try the latest bits in the VS itself

**Comment by hishamco** [comment]
Is the sample work with you?

**Comment by Eilon** [comment]
@israelito3000 if you're running the `dev` or `release` branches from VS you could certainly have issues. But they should work completely if running from the command line.

The `master` branch is for RC1, which should work in VS, except that there's a bug in that build that prevents non-English cultures from showing up.

**Comment by Eilon** [comment]
@ryanbrandenburg can you take a look at this for RTM to see if there's some issue in the samples here?

**Comment by ryanbrandenburg** [comment]
@israelito3000 I don't see this behavior locally against dev, but I have the latest RC2 tooling installed. There was a known bug in VS for RC1 where non-default resources wouldn't be found, but as far as I can tell it's fixed in RC2, so it should be all good once we release.

**Comment by israelito3000** [comment]
How can i get the RC2 tooling?

**Comment by Eilon** [comment]
@israelito3000 it will be released very, very soon! Stay tuned!

**Comment by ryanbrandenburg** [comment]
Hey @israelito3000, [here's](https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-net-core-rc2/) the announcement of RC2 and tooling Preview 1. That should solve your problem. If you find any problems or have trouble getting it set up let us know.
