### ISSUE TITLE
Consider moving RequestLocalizationOptions to Microsoft.AspNetCore.Localization

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Localization#243]
This follows Mvc's pattern (for e.g. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/MvcOptions.cs) and makes it easier to discover types configurable via options (for instance adding a custom `RequestCultureProvider`

**Comment by hishamco** [comment]
IMHO the ```Microsoft.AspNetCore.Builder``` namespace is a proper one while we have this in many repos, please refer to ```SessionOptions``` and ```CookieAuthenticationOptions``` and much more, it makes sense to have them in that namespace because they are essentially used by ```IApplicationBuilder```

**Comment by Eilon** [comment]
@pranavkm can you show what it is that would be easier if this type were moved? We normally have builder-time types that are referenced in Startup.cs in the Builder namespace, as @hishamco says.

**Comment by pranavkm** [comment]
In my sign off sample, I tried adding a modified `QueryStringRequestCultureProvider` to the list. Having the option in `Microsoft.AspNetCore.Localization` namespace would allow for importing it when I do `new RequestLocalizationOption()` and consequently searching for `RequestCultureProvider` yields autocompletion for types in that namespace. If we plan on keeping this, it would be nice to follow up in Mvc and move options to `Builder` namespace to keep the convention consistent across repos.

**Comment by hishamco** [comment]
While the ```QueryStringRequestCultureProvider``` is already in the providers list, you can add your modified once using
```csharp
options.RequestCultureProviders.Insert(0, new ModifiedQueryStringRequestCultureProvider());

**Comment by Eilon** [comment]
I think whichever namespace we put it in, one scenario or the other will have to import an extra namespace, no?

**Comment by pranavkm** [comment]
The builder ones are already in the startup template. Anyway, this issue is totally not worth the amount of discussion we're having here :joy_cat:

**Comment by Eilon** [comment]
Ok 😄
