### ISSUE TITLE
Localization throwing System.Resources.MissingManifestResourceException since RC2

### ISSUE THREAD

**Issue by GarageWeb** [aspnet/Localization#245]
I have created a simple console app here: https://github.com/GarageWeb/ResourceTest  to demonstrate the issue.

**Comment by GarageWeb** [comment]
Moving to home

**Comment by hishamco** [comment]
I'm not sure why you move this to home repo?!! while it related to localization. BTW I will have a look to the sample soon, but I need to know did you run it from the console or VS?

**Comment by hishamco** [comment]
What I have seen that the project doesn't use the localization APIs that's shipped with ASP.NET Core, you are using the resource class that created in VS, i'm not sure either this repo or home repo suited for this issue
/cc @Eilon

**Comment by hishamco** [comment]
I run the app and I got the same exception whenever I moved the resource file to sub folder. I'm not sure the exact reason, again I don't find any package that using ASP.NET Core!! probably the issue may related to .NET Core, hopefully to hear from other folks about the exact reason for this bug

**Comment by GarageWeb** [comment]
OK, I re-opened it here. I just had someone say I should file it on Home. Just FYI, this works as expected if the resx files are at the root and not in a sub-folder. Thanks

**Comment by hishamco** [comment]
Yep I already test it, but as I mentioned before this may related to .NET Core, because I never see any reference to ASP.NET Core packages

**Comment by BrennanConroy** [comment]
@GarageWeb How did you create this Resource? It was created incorrectly, in Resource.Designer.cs L41 it should say "TestApp.Resources.Resource" instead of "TestApp.Resource"

**Comment by glatzert** [comment]
I can also reproduce that Problem with Resources in `ProjectRoot/Resources/SharedResources.en.resx`
Also the factory produces different results for the BaseName, if the Default Namespace of your Project is not in sync with the Project Name.

**Comment by stefan505** [comment]
I've logged a similar issue here: https://github.com/dotnet/cli/issues/3234

It doesn't appear to be ASP.NET specific.

**Comment by stefan505** [comment]
Came across [this](http://stackoverflow.com/questions/33007969/put-translated-resx-files-in-a-different-folder-in-visual-studio) on SO. Was scanning the project,json schema without any luck to try and mimic the accepted solution.

**Comment by stefan505** [comment]
@BrennanConroy you are right about line 41, if I add the subfolder name into it, it works. Only issue is, as soon as you update any resource key/value, the designer file is regenerated and the subfolder is removed from the string.

**Comment by BrennanConroy** [comment]
Looks like a tooling issue then?

**Comment by Eilon** [comment]
@BrennanConroy yeah sounds like it. Can we get a new bug logged in https://github.com/aspnet/Tooling/issues/?

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Tooling/issues/532
