### ISSUE TITLE
Localization Options builds odd ResourceBaseName

### ISSUE THREAD

**Issue by glatzert** [aspnet/Localization#248]
If we use `services.AddLocalization(opt => opt.ResourcesPath = "Resources");` and try to get a localizer with `_localizer = localizerFactory.Create(typeof(SharedResource));` 
the resulting ResourceBaseName will be something like `<AssemblyName>.Resources.<NamespaceOfSharedResource>.SharedResource` which should probably be `<NamespaceOfShareResource>.SharedResource`

**Comment by hishamco** [comment]
Why you didn't use ```IStringLocalizer<T>``` in DI instead of ```localizerFactory.Create```? If you have an online repo please share the link to investigate ..

**Comment by hishamco** [comment]
@glatzert  is this duplicate for issue #247?

**Comment by glatzert** [comment]
I use the localizerFactory.Create() since IStringLocalizer<T> did not work either and I thougt, it might work with the more "Basic" Version - but that ain't right.
@hishamco It _might_ be an duplicate - at least it Looks similar.

**Comment by hishamco** [comment]
If it's duplicate please close this and put the link of your repo and I will look for it, ```IStringLocalizer``` should work fine

**Comment by glatzert** [comment]
Closing this as duplicate or related to #246 #245 and https://github.com/dotnet/cli/issues/3234
