### ISSUE TITLE
Propagation across async/await boundaries

### ISSUE THREAD

**Issue by gzak** [aspnet/Localization#250]
I noticed that the detected locale is ultimately simply [persisted on the current thread](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L127) for subsequent use. Thus, I would have expected there to be a `SynchronizationContext` of some kind which knows how to propagate the value from the current thread onto a new thread in case an `await` operator resumes the operation on a different thread than where the request began. However, to my surprise `SynchronizationContext.Current` is null, and I see no signs of an analogous mechanism anywhere else.

How is the detected locale's value getting propagated to new threads after `await` operators resume on different threads? Or is it not getting propagated?

**Comment by Muchiachio** [comment]
Yes this is most likely related to https://github.com/aspnet/Mvc/issues/4692. I saw this too, that threads don't share the culture.

**Comment by pranavkm** [comment]
We rely on the CLR to take care of this. https://github.com/dotnet/coreclr might be a better place to ask this question

**Comment by gzak** [comment]
In the case of NET451, my understanding is that you need a SynchronizationContext in order to propagate this. Perhaps CoreCLR has a built-in mechanism for propagation, but to my knowledge NET451 does not. Correct me if I'm wrong though...

**Comment by pranavkm** [comment]
@gzak - you're right - this does not work out of the box in NET45. However NET46 adresses this. I was told @davidfowl has a snippet to make this work in NET451.

**Comment by davidfowl** [comment]
Yes we don't have or want a `SynchronizationContext` in ASP.NET Core. You need to use .NET Framework >= 4.6 or .NET Core to get this behavior for free. We can provide a sample to wire this up for .NET <= 4.6.

**Comment by Eilon** [comment]
Closing because there are no plans to add this support to older versions of .NET Framework.

**Comment by gzak** [comment]
Any chance @davidfowl has that snippet for pre 4.6?

**Comment by davidfowl** [comment]
@gzak is there a reason you can't use .NET 4.6? I ask because the *way* code is more intrusive.

**Comment by Eilon** [comment]
Also, I believe older versions of .NET Framework aren't even supported, so it is highly recommended to update.

**Comment by gzak** [comment]
Mostly because I'm curious to see what it would look like without using a `SynchronizationContext`, for my own edification. If it's as intrusive as you say, then I bet we'd prefer an upgrade at the end of the day (depends on bureaucracy of course).

**Comment by davidfowl** [comment]
Without a custom sync context, you need to write an app domain manager and an execution context manager. 

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Host.Clr/DomainManager.cs#L76

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Host.Clr/DnxHostExecutionContextManager.cs

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Host.Clr/ThreadContext.cs
