### ISSUE TITLE
Do not compile resx files

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/Localization#251]
Hi 
With prevision version of ASP.NET we had option to deliver non-compiled resx file. That was great when you need a way to change OOB strings at already installed site: customers was able to do that by they own.
With ASP.NET Core looks like there is no way avoid compiling of resx files. Am I wrong?

**Comment by joeaudette** [comment]
I think I have just what you are looking for
https://github.com/joeaudette/cloudscribe.Web.Localization

also be sure to see the ASP.NET Core localization docs if you haven't already
https://docs.asp.net/en/latest/fundamentals/localization.html

**Comment by antonGritsenko** [comment]
Well, I did (almost) the same, but still I think what compiling of resources is not always needed, so will be great to have this as an option.
PS and offtopic. Removing \bin folder turns folder structure to mess ((( I know, who cares in case of Cloud, but in IIS it looks really like a mess.

**Comment by antonGritsenko** [comment]
@joeaudette btw, am I wrong, or in your project resx file will be compiled and published to server?

**Comment by joeaudette** [comment]
@antonGritsenko I am embedding the resx files in my class library and overriding them if needed with resx files in a folder in the main web app.
in any case I think ultimately resx files always get compiled, if they are on disk then they are JIT compiled

**Comment by antonGritsenko** [comment]
@joeaudette  Not really. In old ASP.NET you can have just App_GlobalResources folder and set all resx files as "Content". No *.resource.dll will be created, only the proxy class in main assembly.

**Comment by joeaudette** [comment]
@antonGritsenko I don't think that is true, if you add more resx files to App_GlobalResources folder it slows startup time because it does JIT the files, you don't see the dll because it is down in the windows temporary files

**Comment by antonGritsenko** [comment]
@joeaudette we talking about little bit different things. You talking about JIT compiler (when site starting), I'm talking about "main" compiler and publishing. I don't care how long my site starting - two seconds or three :)

**Comment by joeaudette** [comment]
if you pre-compile the resx then it does not need to be jit compiled, if you don't then it does I think

**Comment by joeaudette** [comment]
same with .aspx files .ascx files etc

**Comment by antonGritsenko** [comment]
but in case of pre-compiled I can't change them.

**Comment by joeaudette** [comment]
correct. because resx files must be compiled either pre-compiled or jit compiled, it is best to only include resx files for languages you are actually using in the App_GlobalResources folder, because those files do need to be jit compiled and if you have lots of them it can slow down startup a lot.

**Comment by antonGritsenko** [comment]
I know that :) And that's what talking about - I don't want to pre-compile resx file. At all. Because I have to change them later. And I know about performance issue, so those file are not very big and I'm using one file per language, so no real penalty (may be about 2 or 3 seconds).
And again, with old ASP.NET I has option - pre-compile or not. Now I don't have such option. All resx pre-compiled, no matter where are they in project structure.

**Comment by antonGritsenko** [comment]
Moreover, customer may want to add new language later by they own, or create new sub-language (en-UK or whatever). In case of old ASP.NET they needs only to copy one file. How to do that in new ASP.NET - have no idea.

**Comment by joeaudette** [comment]
that does not appear true to me, in the main web app you can add resx files into a folder

    services.AddLocalization(options => options.ResourcesPath = "GlobalResources");

raw resx files there can be edited at any time, I believe they are JIT compiled

when it comes to the case of class library projects, if I embed the resx files I'm not sure they get pre-compiled, they might still get jit compiled because I did not specifically configure them to be compiled.

but the thing is there are 2 different resx models now. There is still the old way for static resources where you create a default resx file like MyResources.resx and that one gets a designer file and the keys can have no spaces. The designer file will definitely get compiled.

the new resx model where you don't create a default resx files, you only create ones for specific languages like MyResources.fr.resx, no designer file is created at all and the keys are allowed to have spaces. This is the model I'm using and the one needed for IStringLocalizer. If I embed those files I'm not sure they get pre-compiled unless I specifically indicate to do that in project.json. 

Maybe someone on the team can confirm or shed light about it

**Comment by antonGritsenko** [comment]
> raw resx files there can be edited at any time
On IIS, after a site was published?
And you don't have all those "en-US", "de" etc folders in published site(or in \bin folder of VS studio project)?

**Comment by joeaudette** [comment]
note also that I don't think you can use the old static resource way with resx files in a folder in the main web app. I think that only works for the new way with IStringLocalizer an dnot using a default resx file

I have not yet fully tested publishing, but from initial test, I can make my raw resx files be in the published out put like this:

        "publishOptions": {
        "include": [
          "wwwroot",
            "Views",
            "GlobalResources",
          "appsettings.json",
          "web.config"
        ]
      },

where GlobalResources is the folder with my resx files. I do still see the folders for languages with dlls in them, I tried to exclude that like this but it did not work

        "buildOptions": {
            "emitEntryPoint": true,
            "preserveCompilationContext": true,
            "compile": {      
                "exclude": [ "GlobalResources/**" ] 
           }
       },

I have not yet tested deployment to see if I can still edit those resx files after deployment

**Comment by antonGritsenko** [comment]
I have same experience - publishing is not a problem, but no way to exclude them from compile.

**Comment by joeaudette** [comment]
have you tried editing a resx file after publishing or adding a new one for another language? I have not tried it yet, hope it works or my goals will not be met

**Comment by antonGritsenko** [comment]
Not yet, have some issues with my implementation of IString* :) and don't have time right now to fix it ) Will check this today later.

**Comment by joeaudette** [comment]
crap! I just tried it and editing the resx file after deployment did not work. this sucks!

**Comment by joeaudette** [comment]
so I guess my solution does still allow clients to add languages or override resx from class libraries, but it requires them to re-publish the app if they do that. still useful but not ideal

**Comment by joeaudette** [comment]
now that I've had some time to process this, I think my initial anger at my cheese being moved has given way to acceptance. after all, adding a new language to a site is an infrequent activity, and I guess the framework should not be optimized for infrequent activity. If someone wants to add a new language, they will need to re-publish and I will give up on the idea of deploying raw resx files. the benefit is that since the resx files don't need to be jit compiled since they are pre-compiled means better performance even if there are a lot of languages included.

**Comment by Eilon** [comment]
Hi folks, there are no plans to have this built-in, but with the extensibility in the system it's certainly possible to build such a system. We see some of the linked projects above offer some solutions to this, so perhaps check those out.

**Comment by antonGritsenko** [comment]
@Eilon , can you please review the thread. The issue was not about ADD such function to Core. The issue (even with custom solution) is that we can't disable compilation of a resx file.

**Comment by Eilon** [comment]
Oh, oops, of course 😄 A few of us met and we focused too much on the overall scenario and not the actual problem! 😄

**Comment by Eilon** [comment]
Ok I think the way to do this is to add something like this to your `project.json` file:

```json
  "resourceExclude": "**/*.resx",
```

This (or something similar to it) should instruct the .NET compiler to not process the RESX files in any folder as *resources*. You might also need to then add them back as "content" files in the `publishOptions/include` section:

```json
  "publishOptions": {
    "include": [
      "**/*.resx",
      ...
     ]
  },
```

But that's mostly just from memory 😄 If you're seeing issues with the options in `project.json`, please file an issue at https://github.com/dotnet/cli/issues/.

**Comment by antonGritsenko** [comment]
@Eilon  thanks a lot!
For history, the right way to exclude resources is using embed:
`"embed": {
      "exclude": [ "Resources/**/*.resx" ]
    }`

**Comment by Eilon** [comment]
Ah, yes, that looks right 😄

**Comment by vameszar** [comment]
Hi there!

I've been trying to disable the resx compilation (we want to be able to swap in new resx files to provide custom string support for our clients), and I cannot get @antonGritsenko 's solution to work, despite trying multiple ways to disable them in my project.json.

I am using @joeaudette 's solution to use Shared Resource files ([https://github.com/joeaudette/cloudscribe.Web.Localization](https://github.com/joeaudette/cloudscribe.Web.Localization))

If someone could please point me in the right direction I would be very grateful! 

Here's some excerpts from my project.json:
```

"dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },  
"tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net452": {
      "frameworkAssemblies": {
        "System.ServiceProcess": "4.0.0.0"
      }
    }
  },
"embed": { "exclude": [ "GlobalResources/**/*.resx", "GlobalResources" ] },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "platform": "x86",
    "compile": {
      "excludeFiles": [
        "GlobalResources\\AdministrationSharedResources.en.resx",
        "GlobalResources\\AdministrationSharedResources.es.resx",
        "GlobalResources\\AdministrationSharedResources.fr.resx",
      ],
      "exclude": "GlobalResources"
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "**.cshtml",
      "appsettings.json",
      "web.config",
      "GlobalResources"
    ]
  },
```

Here's excerpts from my Startup.cs:

```
 public void ConfigureServices(IServiceCollection services)
        {

            services.Configure<GlobalResourceOptions>(Configuration.GetSection("GlobalResourceOptions"));
            services.AddSingleton<IStringLocalizerFactory, GlobalResourceManagerStringLocalizerFactory>();

            services.AddLocalization(options => options.ResourcesPath = "GlobalResources");
            services.Configure<RequestLocalizationOptions>(options =>
            {
                var supportedCultures = new[]
                {
                new CultureInfo("en"),
                new CultureInfo("fr"),
                new CultureInfo("es"),                
            };
                options.FallBackToParentCultures = true;
                options.FallBackToParentUICultures = true;
                options.DefaultRequestCulture = new RequestCulture(culture: "en-US", uiCulture: "en-US");
                options.SupportedCultures = supportedCultures;
                options.SupportedUICultures = supportedCultures;
            });

            services.AddMvc()
                .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
                .AddDataAnnotationsLocalization();

        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {

            var locOptions = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
            app.UseRequestLocalization(locOptions.Value);
}
```

Thank you again!

**Comment by antonGritsenko** [comment]
@vameszar here is my preject.json snippet:
`  "buildOptions": {
    "emitEntryPoint": true, // change this to false to build assembly
    "preserveCompilationContext": true,
    "compile": {
      "include": [ "../SharedCode/**/*.cs", "**/*.cs" ],
      "exclude": [
        "wwwroot",
        "node_modules",
        ".bower",
        "App_GlobalResources",
        "**/*.resx"
      ]
    },
    "embed": {
      "exclude": [ "Resources/**/*.resx" ]
    },
    "define": [ "DEBUG", "netfx4" ],
    "defines": [ "DEBUG", "netfx4" ]
  },`

**Comment by vameszar** [comment]
Hmmm... I've altered my project.json to be closer to yours and still no dice. I am going to try making a sample project and see if I can get it working there.  I'll check in later if I still cannot figure it out.

Thank you for the help!

**Comment by alfred-zaki** [comment]
please consider re-adding the option to leave resx files un-compiled, customers for a web app require different message langue for the same error or information message a web app pops.

think about this as an added value to allow customers to sort of customize their web app after delivery.
which dosen't mean a new language.

**Comment by hishamco** [comment]
@alfred-zaki you can file an issue in [Home](https://github.com/aspnet/home) repo, the issues in this repo were moved there
