### ISSUE TITLE
Problem with german

### ISSUE THREAD

**Issue by seriouz** [aspnet/Localization#255]
Hello folks!

I have a problem to design a german page (culture de-DE), because my customers should be allowed to switch between a "sub-culture" of the german language:
You can address people with "Du" or "Sie" formality. But how can i distinguish between both in the de-DE culture of asp.net localization?

**Comment by hishamco** [comment]
@seriouz you can easily support sub cultures in ASP.NET Core as the following:
```csharp
var supportedCultures = new [] 
{ 
     new CultureInfo("de-AT"),
     new CultureInfo("de-DE"), 
     new CultureInfo("de-CH"), 
     new CultureInfo("de-LI"), 
     new CultureInfo("de-LU"), 
}; 

options.SupportedCultures = supportedCultures; 
options.SupportedUICultures = supportedCultures; 
```
and you can know the selected culture using
```csharp
var selectedCulture = ViewContext.HttpContext.Features.Get<IRequestCultureFeature>().RequestCulture.Culture;
```
