### ISSUE TITLE
_localizer.GetAllStrings() throw MissingManifestResourceException: No manifests exist for the current culture.

### ISSUE THREAD

**Issue by thiennn** [aspnet/Localization#257]
In my project, I try to get all the localized strings to be used in javascript. But it's throw exception when I  call _localizer.GetAllStrings().ToList(); although the _localizer.GetAllStrings("Some string"); work fine.

Am I missing something?

**Comment by Eilon** [comment]
@ryanbrandenburg can you investigate?

**Comment by hishamco** [comment]
@thiennn can you share an online repo that cause the issue

**Comment by thiennn** [comment]
https://github.com/thiennn/localizationTest. The Controller LocalizationController, the TestGetAll, and TestGetAllShared throw that exception, two others work fine.

**Comment by hishamco** [comment]
The issue raised from ```GetResourceNamesFromCultureHierarchy``` method which throws a ```MissingManifestResourceException```, I'll try to dig into why no manifests exist for the current culture

**Comment by hishamco** [comment]
Seems there's a bug when we call ```GetAllStrings().ToList()``` I try it in another project, nothing but the same exception was thrown

**Comment by hishamco** [comment]
I'm still surprising why ```GetManifestResourceNames``` return an empty array?!!

**Comment by ryanbrandenburg** [comment]
@hishamco thanks for asking for the reproduction repo, and @thiennn thanks for providing it, that was a big help.

I've debugged this and determined that you get this error when you don't have a default resx. So @thiennn if you were to add a `Controllers.LocalizationController.resx` to your Resources folder, it would start to work (even for non-default languages). I have not yet figured out why that is or produced a fix, but I figured I'd let you know the workaround ASAP so you can get unblocked.

**Comment by hishamco** [comment]
After long digging into this, I thinks the issue occurs during compilation process, because whenever you add a resource it will not be a part of the final assembly except the default resx, so that's why if you add that resource file it will works fine where the culture is empty **{}**

**Comment by ryanbrandenburg** [comment]
Currently blocked by dotnet/corefx#9766

**Comment by hishamco** [comment]
I expect that, thanks @ryanbrandenburg

**Comment by ryanbrandenburg** [comment]
We implemented a temporary fix in #264. We'll do a more permanent fix after dotnet/corefx#9766 is solved, but that should all be transparent to users.
