### ISSUE TITLE
appEnvironment is null  in the Program ctor.

### ISSUE THREAD

**Issue by TelWang** [aspnet/Localization#26]
When I run the CultureInfoGenerator directly , exception is thrown, appEnvironment is null.
maybe, the tool  will be integrated into vs, but shall we give a default value when appEnvironment is null?
code change to :
       _appName = appEnvironment != null ? "CultureInfoGenerator" : appEnvironment.ApplicationName;
       _appPath = appEnvironment != null ? "" : appEnvironment.ApplicationBasePath;

another issue, in the Main method, the outputFilePath need changed from "../Microsoft.Framework.Globalization.CultureCache/CultureInfoList.cs" to 
"../Microsoft.Framework.Globalization.CultureInfoCache/CultureInfoList.cs"

**Comment by hishamco** [comment]
@TelWang the CultureInfoGenerator works fine if we change the ```outputFilePath``` as you mentioned above, I don't face an issues with ```appEnvironment```

@DamianEdwards we need to change the ```outputFilePath``` because it causes a ```DirectoryNotFoundException```
