### ISSUE TITLE
Track Assembly and Resource issues

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Localization#263]
This is a tracking issue for dotnet/corefx#9766 and dotnet/coreclr#6123 which were found due to #257 and had work arounds in #262.

**Comment by Eilon** [comment]
@ryanbrandenburg , parking this on your plate. No action required at this time.

**Comment by hishamco** [comment]
@ryanbrandenburg if I'm not wrong the issues that you mentioned before are closed, so i'm not sure if we need this open anymore

**Comment by ryanbrandenburg** [comment]
You're correct that those issues are closed, but I'm leaving this open to track the fact that we need to go back and undo the workarounds we had in place for them.

**Comment by hishamco** [comment]
Are we still need this, seems all the mentioned issues got fixed?!!

**Comment by rynowak** [comment]
Nothing is broken here so moving this out

**Comment by hishamco** [comment]
@rynowak the permenant fix that I made in PR #384 may has a breaking-change

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2648
