### ISSUE TITLE
Shared Resource does NOT work when set ResourcePath property of LocalizationOptions:

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/Localization#268]
Currently, I am using one shared resource file RESX to centrally implement localization. 
For cshtml views, I am using IStringLocalizer<SharedResource> for localization. And I have one folder "Resources" in the project root with one empty "SharedResource.cs" file and one "SharedResource.zh.resx" file in it.
Problem is: When I configure "StartUp.cs"'s "ConfigureService" with code `services.AddLocalization(options => options.ResourcesPath = "Resources");`, localization does NOT work! But when I removed the options `options => options.ResourcesPath = "Resources"`, it WORKS!
I am doing everything following aspnet core online docs.
Shouldn't I set the resource path when using shared resource?
How could I mix share resource and view-local resource together in one project?

**Comment by hishamco** [comment]
Can you have a look to the [Localization.Web](https://github.com/aspnet/Entropy/tree/dev/samples/Localization.StarterWeb) sample in the entropy repository

**Comment by kennywangjin** [comment]
@hishamco Thanks. Got the point. The ResourcesPath property is just for aspnet core's localization style, not for traditional .net style localization.
close it.

**Comment by MormonJesus69420** [comment]
What did you do to make it work? I have the same problem but I cannot find a solution. And looking at the project does not give me any idea on how to resolve that issue.

Sorry if it's obvious to you, but it's my first time using resources and localizing asp.net apps.
