### ISSUE TITLE
localization fallback issues:

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/Localization#269]
I use IStringLocalizer and IViewLocalizer to localize my web page. 
If I have no resx files, the page will just show the English KEY string, just a expected.
When I provide localized zh-HANS resource files and set culture to zh-Hans, it will show Chinese, as expected.
Problem is: If I provider only  Chinese resource, the page will always show Chinese even I set culture to en-US. 
I want it to show the original English KEY string if no culture-related resource is found, without add a duplicate en-US resource.
Is it possible to set it?

**Comment by hishamco** [comment]
@kennywangjin can you check the localization sample, it doesn't have a default resource and it works fine.
Please create a repo and provide the link, so we can investigate

**Comment by kennywangjin** [comment]
@hishamco if there is just one localization resource file provided, aspnet will always use that resource to render page no matter the requested culture matches the localization resource or not. I think localization should turn back to the IStringLocalizer-KEY if no matched culture resource file found.

**Comment by hishamco** [comment]
Nope .. please try to remove all the resource files from the localization sample except **Startup.fr-FR.resx** for instance. Run ```dotnet run``` and check the result you will see the English key show up except in France culture which it will replaced by the value in the french resource file

**Comment by kennywangjin** [comment]
@hishamco please see my project: [https://github.com/kennywangjin/OfficeAutomation](url), WebApi as the service and WebPage as the UI project.
The top navbar always shows Chinese only even I set language to en-US (no resources provided for en-US because the default KEY is English.)
And for the sub area: /IT/Home/Index, it works and shows the correct English texts when I change back to English culture (via top right select).
But for the sub area: /HR/Home/Index, it always shows Chinese no matter what language I set (via url or cookie).
Both sub areas and default area are using "_ViewImports.cshtml" to inject IViewLocalizer.
Thanks in advance.

**Comment by hishamco** [comment]
Seems everything works as expected after restoring the required packages, have a look to the top navbar

![capture](https://cloud.githubusercontent.com/assets/3237266/17292219/2cb91182-57f1-11e6-86a9-ed195e70ea1c.PNG)

It shows the right resource values, as well as the area: /HR/Home/Index

![capture1](https://cloud.githubusercontent.com/assets/3237266/17292399/727fd52e-57f2-11e6-8a77-ec30e99a2af1.PNG)

Please rebuild the project, clear the browser cache and try again ..

**Comment by hishamco** [comment]
@kennywangjin any updates?!!

**Comment by kennywangjin** [comment]
@hishamco thanks for your support. Now everything works fine. I don't know why. Anyway, it works. Maybe the cache problem. Thanks.

**Comment by kennywangjin** [comment]
@hishamco thanks for your support. Now everything works fine. I don't know why. Anyway, it works. Maybe the cache problem. Thanks.
