### ISSUE TITLE
Localization for default (entityframework) validators

### ISSUE THREAD

**Issue by stefanhendriks** [aspnet/Localization#271]
At the moment I have a working situation for localizing my custom (and default) attributes.

In general I do it like this:

```
[OnlyValidCharacters] // my own validator
[MaxLength(40, ErrorMessageResourceName = "MaxLength", ErrorMessageResourceType = typeof(MyProject))]
public string LastName { get; set; }
```

```
// my custom validator sets ErrorMessage like so (in its constructor)
public static readonly string InvalidCharacters = @"<>!@#$%^&*()";
...
ErrorMessage = string.Format(MyProject.FormInvalidCharacters, InvalidCharacters);
```

I have a `myproject.en.resx` and a `myproject.resx` file (with an equivalent `MyProject.Designer.cs` file. 

However, I feel that for the default validators (like `MaxLength`) it should be easier to override their default translation.

I would expect my code to be like this:

```
[OnlyValidCharacters] // my own validator
[MaxLength(40)] // do not use my own 'maxLength' thing but the default key 'MaxLengthAttribute_ValidationError'
public string LastName { get; set; }
```

And let the default key for validating being overridden in my project. (in this case, the key is `MaxLengthAttribute_ValidationError`).

I found a `resources.resx` [file](https://github.com/aspnet/EntityFramework6/blob/602bc779baa598fecf6f1ad9b94d76e8d30a9c15/src/EntityFramework/Properties/Resources.resx#L995) in the EntityFramework project and I tried to override the key `MaxLengthAttribute_ValidationError`.

I have tried to override this as following (non where successful):
- add `MaxLengthAttribute_ValidationError` to my own resource file (`myproject.en.resx`)
- create a file `resources.resx` in my project (root level), add MaxLengthAttribute_ValidationError` to override
- tried also with filename `resource.resx` - since a few MVC 4/5 projects where referring to such a filenaming structure.

None of this seems to work.

I feel this ought to be fairly easy to override. I can't seem to find anything using my google voodoo (neither on github, wiki's, asp.net documentation, etc). So perhaps anyone can enlight me?

**Comment by damienbod** [comment]
ErrorMessageResourceName  ErrorMessageResourceType don't work with this localization...

You're meant to use the new style.

**Comment by Eilon** [comment]
Correct, the old style and new style are both fine, but they don't talk to each other.

We have a complete sample of localizing a simple MVC app, including localizing Data Annotations validation attributes: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.LocalizationSample.Web

* The model: https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.LocalizationSample.Web/Models/Product.cs
* A localized resource: https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.LocalizationSample.Web/Resources/Models.Product.fr.resx
* The setup code: https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.LocalizationSample.Web/Startup.cs

**Comment by stefanhendriks** [comment]
This is not exactly the same. As i have to localize per model. 

I want to localize on validator level and override defaults.

If I understand correctly this seems to be not possible.

Btw the examples I posted are working scenario's. So messagetype/name do work there.

Any way to override on validator level? (Ie the resources.resx file of entityframework) without the need to override per model, nor providing "errorMessage" as key? Even that sollution is still requiring me to duplicate keys.

Thx for any advice.

**Comment by Eilon** [comment]
@stefanhendriks perhaps I'm not understanding what isn't working then? I'm pretty sure there was never a way to change the global default validation messages for the built-in data annotations validation attributes...

**Comment by stefanhendriks** [comment]
@Eilon perhaps this is a feature request then? ;-) - it would be very handy to have (from a maintenance standpoint).

I try to give a bit background information, write down a suggestion and perhaps this is something for the future. I hope it would be considered. It would make life really easier. 

**So, my use case is as following**

I have a bunch of models (quite a lot). They have a custom validators and default validators. I want to localize messages for both of them. For my custom validators I can set the `ErrorMessageResourceName` and `ErrorMessageResourceType` in my constructor and it works fine. (personally I find using the new way, ie `errorMessage` as a key for translations, an ugly hack tbh).

At this moment, it means when I add a validation attribute to a new property I have to explicitly set the `ErrorMessageResourceName` and `ErrorMessageResourceType` . This is not required for my custom validators. Even with the 'new' way of doing things I still have to explicitly set the `errorMessage`, which is the same thing maintenance-wise.

This means whenever I forget to do so I get a different (non-translated) error message. 

From a maintenance standpoint I would expect to not even have to set the localization properties, because there are ways to figure out the keys instead of having the 'set' them. 

But lets say you want this for all custom validators, it would not make sense to enforce this for the *default validator attributes* - from the moment you want to deviate from the default translations. 

I think it is not nescesary to enforce this, because I think this is accommodated for using the `resources.resx` file in the EntityFramework repository. 

I have worked in several languages and different MVC frameworks, and what I found very pleasing to use was this 'hierarchy' that was offered in some localization packages. But for this scenario it boils down to 2 levels:

- you have a model level (ie, `myModel.myField.MaxLength=Your myField cannot be longer than {0} chars`)
- there is an attribute level: (ie `string.maxLength=Your string cannot be longer than {0} chars`)

In the current situation, regardless of using the 'new' or the 'old' way: I always need to be very specific on the model level. This makes it very tedious to maintain the code, and it also feels very redundant, because the validator itself is not changed, and I only set the `ErrorMessageResourceType` and `ErrorMessageResourceName` because there does not seem to be a way to override in a more elegant way (see suggestion below).

**In short**:
It would be very handy to have an `attribute level` for localization.

In my case, I would expect to have the key `MaxLengthAttribute_ValidationError` to be defined in my own `<project>.resx` file, and whenever it is found it overrides the `default` one in the EntityFramework package.

This is because within EntityFramework itself there is a `resources.resx` file, and it contains a key `MaxLengthAttribute_ValidationError` with a value. 

And to make it play nice with the current 'new' way of working, I would suggest:

Once the code figures out what `key` to look for. Look in the following order (in the resources);

1. check the `<resourcesBasePath>/models/<mymodel namespace>/<mymodelname>.resx` file if key is present (which basically is what it does now)
2. when not found, go one level up in hierarchy of namespace until found (don't know if this is already working). Example, you go from `com.mycompany.models.account.registration` to `com.mycompany.models.account` to `com.mycompany.models.account` until `com.mycompany.models`
3. when still not found, fall back to `<projectname>.resx` and check for defaults.
4. when still not found, fall back to existing default behavior (fetch it from the library that offered this, in this case `EntityFramework` - whatever it always was doing)

This only applies when nothing is specified, meaning all the current scenario's (when specifying `errorMessage` or `ErrorMessageResourceType` and `ErrorMessageResourceName`) will still work.

I can imagine you don't want to be a default behavior (since it is 'new'), so perhaps a flag should be set when setting up the webapp. (ie, `UseDefaultHierarchyTraversingLocalization` thingy?)

**one more (other) thing**
Above that all, one thing that would be elegant (for the 'new' way of doing things):
- If `errorMessage` is not given, and `ErrorMessageResourceType` and ErrorMessageResourceName` are also not given, then assume the name of the `validate attribute` class (minus the word `attribute`). So `MaxLengthAttribute` is used as `MaxLength` on property, so I would assume `MaxLength` as key in my `resx` files.

I hope this clears a few things up. Sorry for the lengthy post. Thanks for the quick responses so far!

**Comment by ryanbrandenburg** [comment]
@stefanhendriks that's an interesting idea, but it's more of a feature request, would you mind creating a new issue to that effect?

In the mean time, you could prevent the repetitive ErrorMessage entering by sub-classing the attributes in question and setting the ErrorMessage to whatever you want. If you do that you'll have to implement `IValidationAttributeAdapterProvider` in such a way that it finds the new attributes.

Another option here would be for the more than the English resource to be included [here](https://github.com/dotnet/corefx/tree/master/src/System.ComponentModel.Annotations/src/Resources) so that at least in some languages you wouldn't need to localize these built-in's yourself if you were fine with the default phrasing.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
