### ISSUE TITLE
CultureInfoCache ignores custom supported cultures

### ISSUE THREAD

**Issue by fdaunizeau** [aspnet/Localization#272]
Hi all,
In some cultures, the academic decimal separator is comma.
For web users, it is nevertheless more convenient to use the numpad dot in decimal form inputs, but dots are rejected by form validator.

I tried to create an hybrid CultureInfo, based on the french one, except NumberFormat overridden by english culture NumberFormat.

Everything works fine when I only declare a default request culture with the hybrid culture, but it breaks when I add it to the lists of supported cultures.

```
            CultureInfo hybridCulture = new CultureInfo("fr");
            hybridCulture.NumberFormat = new CultureInfo("en").NumberFormat;
            services.Configure<RequestLocalizationOptions>(options =>
            {
                CultureInfo[] supportedCultures = new[]
                {
                    hybridCulture,
                    new CultureInfo("en"),
                };
                options.DefaultRequestCulture = new RequestCulture(hybridCulture);
                options.SupportedCultures = supportedCultures;
                options.SupportedUICultures = supportedCultures;
            });
```
The trouble seems to be in CultureInfoCache, which cache a brand new culture based on the same name, instead of the one passed in supportedCulture.

I fixed it in rewriting CultureInfoCache.GetCultureInfo static method like that
```
        public static CultureInfo GetCultureInfo(string name, IList<CultureInfo> supportedCultures)
        {
            if (name == null || supportedCultures == null)
            {
                return null;
            }
            CacheEntry entry = _cache.GetOrAdd(name, n =>
            {
                CultureInfo cultureInfo = supportedCultures.FirstOrDefault(supportedCulture => string.Equals(supportedCulture.Name, name, StringComparison.OrdinalIgnoreCase));
                if (cultureInfo != null)
                {
                    return new CacheEntry(CultureInfo.ReadOnly(cultureInfo));
                }
                return new CacheEntry(null);
            });

            return entry.CultureInfo;
        }
```
but I need to make a perfect local copy of the RequestLocalizationMiddleware, and a custom ApplicationBuilder extensions to be able to use it.

Is it possible to have this kind of modification in the future version ?

This is my first contrib to Github, I don't really know how to use pull requests in the proper way...
Anyway, thank you for your great job !

**Comment by hishamco** [comment]
@fdaunizeau I think this is a duplicate for #203, I'm glad that you find a bug and trying to solve it, please be free to add a PR after reading [this](https://github.com/aspnet/Localization/blob/dev/CONTRIBUTING.md). It's better to discuss with the others before you submit your PR
Thanks

**Comment by Eilon** [comment]
Closing as a dup of https://github.com/aspnet/Localization/issues/203. We'll take another look at the other bug to see what we can do there.
