### ISSUE TITLE
Localization failed with the os specific runtimes in the project file

### ISSUE THREAD

**Issue by branciat** [aspnet/Localization#276]
I have generated a web appplication with yo aspnet for the reproduction error easily.

an example is better a thousand words, here the sample [LocalizationOrigin](https://github.com/branciat/LocalizationOrigin) where just added the localization to project generated.
And here [TestLocalization](https://github.com/branciat/TestLocalization) where i added some elements and dependencies of my real project.

you can see that the label "Action.Supprimer" and "Action.Valider" are not translate in the test version.

I think it not found the resource file in the os specific path.

**Comment by hishamco** [comment]
Is this issue with Debian OS only?
Have you try it in any Windows OS?

**Comment by branciat** [comment]
Yes, the same problem occur on windows 7 also. installed windows sdk aspnet core and git for windows only and clone the projects. it's alright with LocalizationOrigin and failed with TestLocalization.

**Comment by hishamco** [comment]
Both of them doesn't display the correct result, can you please add the following code to the beginning of the ```Configure``` method:
```csharp
var supportedCultures = new List<CultureInfo>
{
    new CultureInfo("en-US"),
    new CultureInfo("fr-FR")
};

var options = new RequestLocalizationOptions
{
    DefaultRequestCulture = new RequestCulture("en-US"),
    SupportedCultures = supportedCultures,
    SupportedUICultures = supportedCultures
};

app.UseRequestLocalization(options);
```
regarding the TestLocalization project I don't have debian OS nor windows 7, nothing but try to add the above code, and copy the ```project.json``` from the first project with adding the newly dependencies

**Comment by branciat** [comment]
This is what I have in my real project.
```
            var supportedCultures = new[] {
                new CultureInfo("en-US"),
                new CultureInfo("fr-FR")
            };
            app.UseRequestLocalization(new RequestLocalizationOptions{
                DefaultRequestCulture = new RequestCulture("fr-FR"),
                SupportedCultures = supportedCultures,
                SupportedUICultures = supportedCultures
            });
```
I copied in test projects, this does not change. The strings aren't translate.

**Comment by hishamco** [comment]
I surprised when I didn't see the localization setup, with that you need to copy the entire ```project.json``` to the other project, after that run ```dotnet restore``` and ```dotnet run```
I enforced to do that because the runtime doesn't match my runtime

**Comment by branciat** [comment]
I pushed the modifications of two projects. I don't understand the latest message. The TestLocalization is more simple that my real project, and more easy to compare with the LocalizationOrigin and track the source of bug.

What does it possible to show the trace of localization with the log level ? Or modified the source ?

**Comment by hishamco** [comment]
You can you console logger if you do so, regarding the latest changes that you pushed looks fine, one more thing can you copy the entire ```project.json``` from the LocalizationOrigin project and paste it to the new project. Don't forget ```dotnet run restore``` before you run the application, have a try please and let me know if you get the correct result

**Comment by branciat** [comment]
I modified the TestLocalization view which to show a error message, i loop on the LocalizationStrings and force the throw exception.

**Comment by hishamco** [comment]
Please let everything as it was before, and let me know if you got the correct localized strings or not. Don't forget to add the queryString **?culture=fr-FR&ui-Culture=fr-FR** to enforce the ```QueryStringCultureProvider``` to get the right culture

**Comment by branciat** [comment]
The project.json of LocalizationOrigin work fine, i know because i written :smile:  but it is not one that interests me because in my project i must to have the runtimes os, maybe with the database dependencies (entityframework, npgsql), it's the project.json of TestLocalization is interesting for me.

**Comment by hishamco** [comment]
I know there problem is I don't have the exact runtime, also I tried to figure out where's the line that break the localization, sadly I didn't find it :disappointed:

**Comment by branciat** [comment]
The url used http://localhost:5000/Home/Index?culture=fr-FR&ui-Culture=fr-FR
and the complete console trace

```
Request starting HTTP/1.1 GET http://localhost:5000/Home/Index?culture=fr-FR&ui-Culture=fr-FR  
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path /Home/Index does not match a supported file type
dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action TestLocalization.Controllers.HomeController.Index (TestLocalization)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method TestLocalization.Controllers.HomeController.Index (TestLocalization) with arguments () - ModelState is Valid
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method TestLocalization.Controllers.HomeController.Index (TestLocalization), returned result Microsoft.AspNetCore.Mvc.ViewResult.
dbug: Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine[2]
      View lookup cache hit for view 'Index' in controller 'Home'.
dbug: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[2]
      The view 'Index' was found.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
dbug: Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware[0]
      System.Resources.MissingManifestResourceException occurred, checking if Entity Framework recorded this exception as resulting from a failed database operation.
dbug: Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware[0]
      Entity Framework did not record any exceptions due to failed database operations. This means the current exception is not a failed Entity Framework database operation, or the current exception occurred from a DbContext that was not obtained from request services.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.Resources.MissingManifestResourceException: The manifest 'TestLocalization.Resources.Test.fr-FR.resources' was not found.
   at Microsoft.Extensions.Localization.ResourceManagerStringLocalizer.<GetAllStrings>d__13.MoveNext()
   at AspNetCore._Views_Home_Index_cshtml.<ExecuteAsync>d__39.MoveNext() in /Views/Home/Index.cshtml:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultFilterAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllResultFiltersAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResourceFilterAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 28.8897ms 500 text/html; charset=utf-8
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HKUB3G416622" completed keep alive response.
dbug: Microsoft.AspNetCore.Server.Kestrel[6]
      Connection id "0HKUB3G416622" received FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HKUB3G416622" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[7]
      Connection id "0HKUB3G416622" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[8]
      Connection id "0HKUB3G416622" sent FIN with status "0".
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HKUB3G416622" stopped.
```

**Comment by branciat** [comment]
I understand :wink:  and me without the localization source it's difficult to find the source of problem

**Comment by hishamco** [comment]
Can you check the ```TestLocalization.Resources.Test.fr-FR.resources``` in the bin\debug\runtime folder?

**Comment by branciat** [comment]
I have not runtime folder and not resources file, but i have a fr-FR folder with the TestLocalization.resources.dll file compiled. This fr-FR folder is bin/Debug/netcoreapp1.0 and in  bin/Debug/netcoreapp1.0/debian.8-x64 and i have the TestLocalization.deps.json in debian-8x64 folder which contain the setting localization.
```
"resources": {
          "fr-FR/TestLocalization.resources.dll": {
            "locale": "fr-FR"
          }
        }
```

**Comment by hishamco** [comment]
I forgot the culture folder :smile: I updated my latest comments.
Please push the latest change into your repo and I will try again in to check the exception in Windows environment

**Comment by branciat** [comment]
In Windows environment (win7), the same error occured.

**Comment by branciat** [comment]
i saw that we can debug vscode in Linux now, when i have a moment i will look into the sources of localization to detect the problem.

**Comment by branciat** [comment]
Well,

I cloned and added the TestLocalization into localization project. The resource assembly is found and retrieved the strings, but an manifest exception is throw from this [line in ResourceManager.cs](https://github.com/dotnet/corefx/blob/master/src/System.Resources.ResourceManager/src/System/Resources/ResourceManager.cs#L70) in the System.Resources of corefx.

I tried to add the part System.Resources.ResourceManager to continue the debugging without success, I encounter dependency problems aot. Probably must take all the corefx source :worried:

**Comment by hishamco** [comment]
@ryanbrandenburg any idea?

**Comment by ryanbrandenburg** [comment]
@branciat it seems there are more things different between those two examples than just including a runtime. [Here](https://github.com/ryanbrandenburg/TestLocalization) I've created a version of what you had which properly localizes. Of note is that in `project.json` you have:
`"tooling": { "defaultNamespace": "Mediagral"}`, which in older versions might have affected Resource generation and location, but now only determines the default namespace for File > New Class. I bring that up because I believe it might have lead to the next problem, that resx files weren't named in accordance with [this](https://docs.asp.net/en/latest/fundamentals/localization.html#resource-file-naming) guidance, namely that resources outside the base namespace must include their entire namespace. One final note was that Test.cs was in the `TestLocalization` namespace instead of `Mediagral` like the other resources were, so I moved it.

Can you confirm that that branch works for you and meets your requirements?

**Comment by branciat** [comment]
@ryanbrandenburg 
effectively after multiple changes, I added errors in the project, sorry. I tested your project after adding a file to myget because I use NuGet and 1.0.0 versions, this version 1.0.0 throw the same exception with your project. With version 1.1.0 it compiles and executes correctly only I still have the same behavior at the beginning with your project and my project modified, the field's name of the resource file appears correctly but not the translation value.

I updated the two projects to do well appear in a tag pre to see the difference between the 2. I put a screenshot in wwwroot/images of two projects and attach on issue.
I tested again under debian windows 7 and 8, the same problem with the 2 systems.

![localizationorigin](https://cloud.githubusercontent.com/assets/6303230/18481233/caa33894-79db-11e6-87e8-cbfd08c9a1d6.png)
![testlocalizationryan](https://cloud.githubusercontent.com/assets/6303230/18481237/cd0d1ee2-79db-11e6-8ced-f5243dd1c237.png)

I hope to have not added errors, I tried to change the least possible.

**Comment by branciat** [comment]
I simplified the project TestLocalization, modified the project file and deleted the namespace mediagral to respect the guidance. No exception but the texts are not translated as this image above.

**Comment by branciat** [comment]
@ryanbrandenburg 
Ok i found the origin of problem. If remove the language entry in the project.json of TestLocalization, all texts are translated, and if add the language in the project LocalizationOrigin that have always translate the texts, now they are no longer translated.
Why ? Is that really the source of problem ? i don't know.

**Comment by ryanbrandenburg** [comment]
@branciat I came to the same conclusion just moments ago. The problem is that when you set `"language": "fr-FR"` you're setting that as the default language for localization, so when our resource manager goes out to look for a fr-FR resource it looks for "TypeName" not "TypeName.fr-FR". If you were to rename your `*.fr-FR.resx` files to `*.resx` I believe they would localize and you would be able to leave in the language setting (in case it's important to you.)

Sorry for the delay in figuring that out, one of the tools I was using to analyse our resource dll's was broken and leading me down the wrong path.

I believe that should take care of this, feel free to reopen if not.
