### ISSUE TITLE
Decimal format not working with localization for French language

### ISSUE THREAD

**Issue by dpjain** [aspnet/Localization#285]
The decimal separator used for Euro currency is comma, while in other currency we have dot as a decimal separator. So when any model property is of Currency data type, it fires data annotation validation states that "The property must be a number". 

As while changing the culture to French the display format of decimal and currency datatype property becomes '0,00'. 

How can we set the default decimal format as 0.00 globally? And also how can we restrict not to change the culture for currency?

**Comment by hishamco** [comment]
If I'm not wrong this is a duplicate for issue #203

**Comment by dpjain** [comment]
No its different issue I think. In the issue #203, they are not getting the localization working for currency. in my case I am getting the appropriate Euro currency when I change the culture to French.
Due to Euro decimal format(using comma as decimal separator), the validation is fired as invalid number.

**Comment by hishamco** [comment]
Using `0.00.ToString("C")` should display 0,00 € in french culture.
Can you please print out `0.00.ToString("C", CultureInfo.InvariantCulture)` and check if you get the desired result.

**Comment by dpjain** [comment]
But we need to use decimal format (0.00) for Editor as well as for display dynamically.

**Comment by hishamco** [comment]
Do you get the expected result when you execute the above code? if yes, the main issue you 're facing is the editor shows you an error when you enter (0.00) format, Am I right?

**Comment by dpjain** [comment]
Yes, main issue is with Editor for a number data type

**Comment by hishamco** [comment]
I tried to change the `DataFormatString` in `DisplayFormatAttribute`, it works with date, but whenever you change the numbers format it shows comman instead of period even if the period symbol was set in the format.
I end up with setting `NumberFormat.NumberDecimalSeparator` of the current culture to period symbol, it works as expected.

**Comment by dpjain** [comment]
Sure, I will try this to resolve the issue.

**Comment by hishamco** [comment]
Exactly @ryanbrandenburg, the solution that you mentioned above is the easiest one after the fix of #203, but before that it needs a workaround to make this happen

**Comment by ryanbrandenburg** [comment]
@dpjain I'm going to assume that in this instance silence means success. Feel free to re-open if you still have trouble.

**Comment by dpjain** [comment]
@ryanbrandenburg 
I am still facing the issue after declaring the NumberFormat= { CurrencyDecimalSeparator = "."} in Startup.cs.

**Comment by hishamco** [comment]
@dpjain can you please upload your sample in a repo and share the link with us

**Comment by dpjain** [comment]
Sorry I was not able to provide you the sample. 

But the issue is resolved now. 
Thanks

**Comment by hishamco** [comment]
No problem, while the problem solved 😄
