### ISSUE TITLE
Localize default DataAnnotations validation messages languaje

### ISSUE THREAD

**Issue by airomero** [aspnet/Localization#286]
Hi, i want all built in validation messages (required, minlength, etc) in other languaje than english since my app is in spanish. I don´t want to add any param to my DataAnnotacion attributes. What i'm looking for is to override the default languaje (since all validation messages are in english), my messages will always be in spanish. Is there a way to configure the default languaje and specify the resource file?? Thanks.

**Comment by hishamco** [comment]
Please have a look to this sample https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Startup.cs#L59, don't forget to set the Spanish language as default culture here https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Startup.cs#L76

**Comment by airomero** [comment]
I have already looked at it.

For example the the required attribute in the model is:
[Required(ErrorMessage = "ProductName")]

I don`t want to specify that, i just want the Required attribute and the validation mesage in spanish. In mvc5 it was possible. I installed the language pack for the fwk 4.5 and the "Microsoft.AspNet.Mvc.es" nuget package and the built in validation messages were displayed in spanish. No need to touch the dataannotation attribute. I want to decorate mi property class with [Required] and get the validation message in spanish. Is this possible (without touching bussines code, only configuration). Thanks!

**Comment by hishamco** [comment]
`[Required(ErrorMessage = "ProductName")]` is fine what you 're missing to define a resource file for spanish language that contains ProductName as key.
The Localization.StarterWeb sample already have this in https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/ViewModels/Account/RegisterViewModel.cs#L12, https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Resources/ViewModels/Account/RegisterViewModel.fr.resx#L132

**Comment by airomero** [comment]
I think you don´t understand me. I don´t want to write `[Required(ErrorMessage = "ProductName")]`. I want to write `[Required]` and have the validation message in spanish. The required attribute has a built in message, which is in english. I want that message in spanish without writing (ErrorMessage = "ProductName"). My previous comment was very clear i think. I have all my classes already written and i don´t want to touch them, i just want to configure the app so that the built in validation messages are in spanish. Is this possible?

**Comment by hishamco** [comment]
I think you need to create a Spanish resource file for those built-in messages

**Comment by ryanbrandenburg** [comment]
@airomero the innards of `RequiredAttribute` are actually part of [corefx](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/RequiredAttribute.cs) so it's a little bit out of my wheelhouse, but based on my prior knowledge and a brief reading of their files and code I believe that what you're asking is currently not possible because we only have english [resx files](https://github.com/dotnet/corefx/tree/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.ComponentModel.Annotations/src/Resources). I've reached out to the CoreFX team to confirm. In the mean time @hishamco's suggestion to use `ErrorMessage` is unfortunately the best alternative I know of.

**Comment by airomero** [comment]
@ryanbrandenburg  thanks for your answer. Too sad that we still have this problem. I my opinion, we should be able to override the default messages without touching code, only configuration. It´s ok that the default messages languaje is english, but maybe if there is a resource file in the project, and we configure the app to take that resx it'd be so much easier. I feel so frustrated when i see that resx file in english that can not be changed for another one. I really hope something can be done with this. Again, thanks and i hope i have news for this "issue" ;)

**Comment by airomero** [comment]
Also, one thing, if i have the required attribute in 100 entities and i want to translate it, it menas that i have to create 100 resx files for that? One for each class?? Tell me i'm wrong.

**Comment by hishamco** [comment]
Yep, unless you creating your own custom attribute that is using a custom `IStringLocalizerFactory`

**Comment by airomero** [comment]
Is there any design reason for that? Why the same attribute has to be translated over and over again for each class? This was so much easier before.......I'm sorry but i feel that the non english people is punished with this kind of implementation.

**Comment by hishamco** [comment]
AFAIK almost the repos in ASP.NET Core has English version of the resx file out of the box, So what I know is you need to create a resource per class to get the localized version

**Comment by airomero** [comment]
Don't you think that it has no sense to translate the same attribute over and over again in each class i need it? From my perspective is an awful and rigid implementation. I really hope that localization would be more important for the development of netcore :(

**Comment by hishamco** [comment]
The localization in ASP.NET Core is very flexible and extendable, but the `DataAnnotation` once is from the early days of .NET, and this is how works since years ago. I know you and I as a non English people suffer sometime when we localize out apps (no choice :smile: )

**Comment by hishamco** [comment]
One more thing if your application using one language you can write your translation directly in the data annotation attributes, so the localization APIs if doesn't found the your localization resource of course will pick up the one that you wrote

**Comment by airomero** [comment]
Ok,you are wright, the problem here is DataAnnotations. In this case speaking only about the `[Required]` attribute, i have to write in every entity, in every required field:
`[Required(ErrorMessage = "El campo {0} es requerido.")]`
It's a madness. And that is only for `[Rquired]`, imagine all of the others attributes. If it's the same message it would be better to translate it only in one place (resx file). This is a step backward, in previous versions this was solved with the fwk languaje package. :( :( :( :( :( :(

**Comment by hishamco** [comment]
This is why I told you before you need to write your own with using a custom `IStringLocalizerFactory`, BTW the compiler will not care if you are using the same message or not , so probably you can subclass the `Require` attribute and write your error message once in the subclass, problem solved :)

**Comment by airomero** [comment]
I didn't follow you on this one with the subclass. Is there any sample here in the repo of `IStringLocalizerFactory`?

**Comment by hishamco** [comment]
Of course, there's a sample I built long time back in the [entropy repo](https://github.com/aspnet/Entropy/tree/dev/samples/Localization.EntityFramework)

**Comment by ryanbrandenburg** [comment]
@airomero I don't believe you do need to make 100 resx's. Instead, you can do something like this:

```
.AddDataAnnotationsLocalization(options => {
    options.DataAnnotationLocalizerProvider = (type, factory) => 
        factory.Create(typeof(SharedResource));
});
```
in your startup. That allows you to use a different resource based on your type, or just use a single resource for every type, or whatever suits you.

Let me know if I've misunderstood your ask or if you have any trouble with that.

**Comment by airomero** [comment]
Yes, i need a single resource file for every type so that every `[Required]` field uses the same message just like it works by default, but instead of getting a message in english, it would be in other languaje.
In the code above: `factory.Create(typeof(SharedResource))`, **SharedResource** would be the path to a resx file? How do i tell the config what resx file to pick up?? Thanks!!

**Comment by ryanbrandenburg** [comment]
I think I may have misunderstood your question, were you asking about multiple resources for the case of `[Required]` or for `[Required(ErrorMessage = "El campo {0} es requerido.")]`? My comment was addressing the second case. For the first case I'm still working with the CoreFX team to get you an authoritative answer.

**Comment by ryanbrandenburg** [comment]
@airomero the consensus between the CoreFX team and ours seems to be that it may be hypothetically possible for you to accomplish what you're asking by adding satellite assemblies, but that isn't something we would recommend you try to do, and certainly not something we would support, as it would rely on implementation details and generally complicate your build process.

For now `[Required(ErrorMessage = "El campo {0} es requerido.")]` is the best solution we can offer. If you feel strongly about the `[Required]` scenario you may open an issue against the CoreFX repo and see how much community support there is for this.

**Comment by airomero** [comment]
Maybe i did not explain it well enough. In my web app i have the '[Required]' attribute in many classes (entities, view models, etc). My app is in spanish. The error message i get in the browser for those fields is: "The field XXX is rquired". I want that message to be: "El campo XXX es requerido". As far as i read, and as you told me i should make a resx file for each class that has the `[Required]` in order to translate the message for that class. That means that if i have 100 classes with the required field, i should have 100 resx files. What i want is to have only one resx file in my web app, with only one entry for the `[Required]` attribute. All the `[Required]` attributes in all classes should use the resx file in my web app. I think it is well explained this time.

**Comment by airomero** [comment]
@ryanbrandenburg thanks for trying to help me and give me an answer. I think it should be easier to replace the default resx file that is embedded into corefx, i didn't think it would be so complicated. I must say i'm a little dissapointed. Anyway, thanks a lot for your help.

**Comment by ryanbrandenburg** [comment]
For posterity, the solution we recommend for using the same resource string on validation attributes across multiple classes is to do 
```
.AddDataAnnotationsLocalization(options => {
    options.DataAnnotationLocalizerProvider = (type, factory) => 
        factory.Create(typeof(SharedResource));
});
```
in your startup, where `SharedResource` is the class corresponding to the resx where your validation messages are stored (data annotations will then only use that resource, rather than the resource for each class). Then decorate the properties with `[Required(ErrorMessage = "RequiredError")]`.

Sorry I wasn't able resolve the situation to your liking, hope it turns out well for you.

**Comment by audacity76** [comment]
I have managed to change the validation messages at a global level. I use the AttributeAdapter for this. Example:

1. Create RESX File as already described above, I called it DataAnnotationResource.resx and added a string resource "ValueRequired".

2. Create a LocalizedRequiredAttributeAdapter like:
    ```
public class LocalizedRequiredAttributeAdapter : RequiredAttributeAdapter
    {
        public LocalizedRequiredAttributeAdapter(RequiredAttribute attribute, IStringLocalizer stringLocalizer) : base(attribute,stringLocalizer)
        {
            if (attribute.ErrorMessageResourceType == null)
                attribute.ErrorMessageResourceType = typeof(DataAnnotationResource);
            if (attribute.ErrorMessageResourceName == null)
                attribute.ErrorMessageResourceName = nameof(DataAnnotationResource.ValueRequired);
        }
    }
```

3. Create a LocalizedValidationAttributeAdapterProvider like:
    ```
public class LocalizedValidationAttributeAdapterProvider : IValidationAttributeAdapterProvider
    {
        // based on Mvc/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/ValidationAttributeAdapterProvider.cs
        public virtual IAttributeAdapter GetAttributeAdapter(ValidationAttribute attribute, IStringLocalizer stringLocalizer)
        {
            if (attribute == null)
            {
                throw new ArgumentNullException(nameof(attribute));
            }

            IAttributeAdapter adapter;

            var type = attribute.GetType();

            if (type == typeof(RequiredAttribute))
            {
                adapter = new LocalizedRequiredAttributeAdapter((RequiredAttribute)attribute, stringLocalizer);
            } else if
 
            ... look here: Mvc/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/ValidationAttributeAdapterProvider.cs

            return adapter;
        }
    }
```

4. Register LocalizedValidationAttributeAdapterProvider in Startup.cs:

    `services.AddSingleton<IValidationAttributeAdapterProvider, LocalizedValidationAttributeAdapterProvider>();
`

That's it. Note: You don't have to add MvcOption AddDataAnnotationsLocalization nor AddLocalization to provide translation of the validation messages.

**Comment by simon25608** [comment]
@ryanbrandenburg 

I have your solution working perfectly locally with version 1.1.0, but in the test environment does not work, with the same version does not work.

` services.AddMvc().AddDataAnnotationsLocalization(options =>
            {
                options.DataAnnotationLocalizerProvider = (type, factory) => factory.Create("RecursosGenericos", location: null);
            });`

**Comment by ryanbrandenburg** [comment]
@simon25608 please create a new issue with expected vs actual results, a detailed description of what you're trying to accomplish and how you're going about it, and especially an explaination of what your test environment is and how it differes from your development environment. As a suggestion to get you started, you might want to check that both versions of dotnet are the same (run "dotnet --info") and that you're drawing from the same nuget sources in both places.

**Comment by Ciantic** [comment]
I think there is something odd about RequiredAttribute, with EmailAddressAttribute it works correctly.

E.g.

With dummy localizer:

```C#
    public class TestLocalizer : IStringLocalizer
    {
        public LocalizedString this[string name]
        {
            get
            {
                return new LocalizedString(name, name + "test localizer");
            }
        }

        public LocalizedString this[string name, params object[] arguments]
        {
            get
            {
                return new LocalizedString(name, name + "test localizer");
            }
        }

        public IEnumerable<LocalizedString> GetAllStrings(bool includeParentCultures)
        {
            return new List<LocalizedString>();
        }

        public IStringLocalizer WithCulture(CultureInfo culture)
        {
            return this;
        }
    }
```

and this:

```
.AddDataAnnotationsLocalization(options =>
                {
                    options.DataAnnotationLocalizerProvider = (type, factory) =>
                    {
                        return new TestLocalizer();
                    };
                })
```

The models such as: 

```
        public class RegisterAction
        {
            public RegisterRole Role { get; set; }

            [EmailAddress] // Goes to to TestLocalizer
            [Required(ErrorMessage = "goes to TestLocalizer")]
            public string Email { get; set; } = "";

            [Required] // Does NOT go to TestLocalizer
            public string Password { get; set; } = "";
        }
```

It works just fine with bare `[EmailAddress]`  but does not work with bare `[Required]`.

This is bit annoying, since I can't provide a default for the Required.

**Comment by hishamco** [comment]
@Ciantic can you move this to another issue to make it easy for tracking

**Comment by Ciantic** [comment]
@hishamco okay. #313

**Comment by christiankersten** [comment]
**Entity class:**

```
[Required(ErrorMessageResourceName = "ErrorPassword", ErrorMessageResourceType = typeof(Translations))]
[Display(Name = "UserPassword", ResourceType = typeof(Translations))]
[DataType(DataType.Password)]
[Column("Wachtwoord")]
public string Password { get; set; }
```

I use resource files (.resx) for my localized strings. 
I have one file for every language I want. 
Like:
Translations.resx ( the standard selected file and your prefered language )
Translations.en-US.resx
Translations.pl-PL.resx

If you put them in a different project in your solution you can retrieve them from every other project.

**Comment by PH-Lars** [comment]
For me the following works fine for now:

`[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
    public class AppRequiredAttribute : RequiredAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var stringLocalizer = validationContext.GetService(typeof(IStringLocalizer<SharedDataAnnotationRecources>)) as IStringLocalizer<SharedDataAnnotationRecources>;
            ErrorMessage = stringLocalizer["The {0} field is required."]?.Value ?? "The {0} field is required.";

            return base.IsValid(value, validationContext);
        }
    }`

And to use it: 

`[AppRequired]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email address")]
        public string Email { get; set; }`

**Comment by os1r1s110** [comment]
@PH-Lars I tried your proposed workaround, but it seems to break all client-side validation because the [Required] attribute is not on the properties anymore... so you have to be careful with that. (maybe it's just on my side that it does that, but I'm wondering if it would not be the same for everyone)

**Comment by ramons03** [comment]
Why no one suggest web.config option?
`<globalization culture="es-AR" uiCulture="es" />`

**Comment by shinjiDev** [comment]
@airomero I found this resx https://github.com/Microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/System.ComponentModel.DataAnnotations/DataAnnotationsResources.resx , It's used by attributes like Required and others, maybe implementing a new resx for spanish language could work.

Best regards
