### ISSUE TITLE
Unable to run the sample

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#295]
Yesterday I was playing with dotnet CLI bits to add new command, suddenly when I was trying to run the localization sample I got this error

The specified framework 'Microsoft.NETCore.App', version '1.1.0-preview1-001100-00' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.0.0-rc2-3002392
      1.0.0-rc2-3002702
      1.0.1
  - Alternatively, install the framework version '1.1.0-preview1-001100-00'.

FYI the dotnet version shows the latest version in the "sdk" folder but what I see before are the once in the "shared" folder
/cc @pranavkm @ryanbrandenburg

**Comment by pranavkm** [comment]
If you run build.cmd \ build.sh, it should grab the new shared runtime for you. That said, given that these sort of build changes aren't repo specific work items, I'd highly recommend using https://github.com/aspnet/Home as a place to start a discussion about it.

**Comment by hishamco** [comment]
I already did that, but it fails before it complete, ok I will close it and move it to home repo
thanks
