### ISSUE TITLE
[BREAKING CHANGE] Parameter changed on ResourceManagerStringLocalizer constructor

### ISSUE THREAD

**Issue by javiercn** [aspnet/Localization#297]
V1:
`public ResourceManagerStringLocalizer(ResourceManager resourceManager, AssemblyWrapper resourceAssemblyWrapper, string baseName, IResourceNamesCache resourceNamesCache)`
V2:
`public ResourceManagerStringLocalizer(ResourceManager resourceManager,             IResourceStringProvider resourceStringProvider, string baseName, IResourceNamesCache resourceNamesCache)`

[ACTION for 1.1]: Undo the constructor change.
[Action for 2.0]: Take the change if is what we want to do.

**Comment by javiercn** [comment]
@Eilon

**Comment by BrennanConroy** [comment]
The tool looks broken
The V1 constructor still exists https://github.com/aspnet/Localization/blob/f650de8cdf5214bcbb2e88210baac0f99ce3d053/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L34

**Comment by javiercn** [comment]
@BrennanConroy You are looking at the wrong constructor
**AssemblyWrapper resourceAssemblyWrapper** not **Assembly resourceAssembly**

**Comment by javiercn** [comment]
https://github.com/aspnet/Localization/blob/1.0.0/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L51
https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L57

**Comment by hishamco** [comment]
@javiercn I'm not sure why it's a breaking change, while the constructor intended for testing purposes only?!!

**Comment by Eilon** [comment]
@ryanbrandenburg can you get the fix in ASAP?

@hishamco it's a source-code breaking change in case someone used named parameters to call the constructor.

**Comment by hishamco** [comment]
I'm with you @Elion, but still wonder, because the constructor is intended for Testing purpose (nothing else), correct me if I'm wrong

**Comment by ryanbrandenburg** [comment]
I believe I discussed this with either @rynowak or @dougbu at the time and we decided it was ok to change this one because it's labeled as for testing only.

**Comment by Eilon** [comment]
Yeah that's a no-go, it's still a breaking change.

**Comment by hishamco** [comment]
As I said before it's for testing only, so that's why `internal` modifier is preferable for internal classes, I remembered long time back I posted an issue regarding this, but @Eilon said this is how we design it for almost the aspnet repos

**Comment by ryanbrandenburg** [comment]
I recall now the other justification for changing that constructor. `AssemblyWrapper` is in the namespace `Microsoft.Extensions.Localization.Internal`, so we reasoned that the constructor was internal due to needing the internal `AssemblyWrapper` class. If that doesn't change your opinion I've made #299 to get this rolling.

**Comment by Eilon** [comment]
O I C, those are fair points, but let's just avoid the breaking change - less headache in the long run.
