### ISSUE TITLE
`IApplicationBuilderExtensions` has incorrect name

### ISSUE THREAD

**Issue by dougbu** [aspnet/Localization#30]
This class should be named `ApplicationBuilderExtensions` according to [guidelines](https://github.com/aspnet/Home/wiki/Engineering-guidelines#extension-method-patterns):
> When writing extension methods for an interface the sponsor type name must not start with an `I`.

**Comment by hishamco** [comment]
@dougbu Nice catch :+1:

**Comment by dougbu** [comment]
113fa6d
