### ISSUE TITLE
Re-design IStringLocalizerFactory

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#302]
As we know in almost the ASP.NET repos, that the abstraction APIs in way that be applicable and implemented in various ways, but what I have seen from awhile that `IStringLocalizerFactory` is designed to support resx files which the only one implementation shipped with ASP.NET Core.

I have look to different implementation of it, all of them they should implement two `Create` method with parameters that's not need at all.

If we looked into the [EFStringLocalizerFactory](https://github.com/aspnet/Entropy/blob/dev/samples/Localization.EntityFramework/EFStringLocalizerFactory.cs) as example you will notice what I mean, and this unfortunately sort of tightly coupled, I have never ever seen an interface that designed for a specific implementation, that's the fact that we should realize, may need we think twice to improve this. I know it's breaking change!! but this should be fixed as long term.

My humble opinion is to change the above interface to something like this:
```csharp
public interface IStringLocalizerFactory
{
    IStringLocalizer Create();
}
```
Now it make sense for any kind of implementation to override the `Create` function easily without extra stuff

/cc @DamianEdwards @Eilon

**Comment by Eilon** [comment]
The Create method needs parameters for the common case where there are multiple locations to load resources. E.g. it is common to have per-page or per-area resources, and then another place with common/global resources.

It is perfectly fine for a factory to not use those parameters if all resource for the entire app are located in the same place.

**Comment by hishamco** [comment]
You presume that the resources are in .resx files, but I'm talking about something independent from underlying source, it may be file system, database, web APIs .. etc. In case that the common used are file-based resources such as resx, po .. etc I'm agree that the `location` parameter is needed, what about the `baseName` and the other overload https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization.Abstractions/IStringLocalizerFactory.cs#L19 because we enforced to implement it and make it empty, because it's originally tightly coupled on `ResourceManager` implementation which is the thing that I argue about, but if you looked to the Configuraton APIs as sample at least it is source independent

**Comment by Eilon** [comment]
@hishamco the interfaces have to be broad enough to support any possible implementation, such as EF, PO, RESX, etc. But it's fine for implementations to ignore parameters that aren't relevant to them.

**Comment by hishamco** [comment]
Yep, may be I don't have doubt about the second overload, because it can handle such source, my doubt about the first one https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization.Abstractions/IStringLocalizerFactory.cs#L19, because the resource type intend to serve `ResourceManager`
