### ISSUE TITLE
The (OS) language resx files are ignored and keys are returned

### ISSUE THREAD

**Issue by WGroenestein** [aspnet/Localization#304]
Scenario: I don't want my translation keys to be very lengthy especially in case of explanatory text bodies. Having keys as "Given name", "Is required" etc are fine (i.e. they can just be hard coded  and have the keys returned), but you should be able to override them through a resx file (or any other provider). Especially for lengthy text bodies, which are not desirable hard coded.

### Functional impact
The default (OS) language is not using the values defined in the resx file

### Minimal repro steps
1. Create a new (Web API) asp.net core project.
2. Add the following to Startup.ConfigureServices
```
services.AddLocalization(x => x.ResourcesPath = "Resources");
```
3. Add the following to Startup.Configure
```
CultureInfo[] supportedCultures = new CultureInfo[]
{
    new CultureInfo("en"),
    new CultureInfo("nl")
};

RequestLocalizationOptions requestLocationOptions = new RequestLocalizationOptions
{
    DefaultRequestCulture = new RequestCulture(supportedCultures[0]),
    SupportedCultures = supportedCultures,
    SupportedUICultures = supportedCultures
};

app.UseRequestLocalization(requestLocationOptions);
```
4. Create the folder "Resources"
5. Create "Controllers.ValuesController.en.resx"
```
_Key1: "Key one"
_Key2: "Key two"
```
6. Create "Controllers.ValuesController.nl.resx"
```
_Key1: "Sleutel één"
_Key2: "Sleutel twee"
```
7. Replace the ValuesController with
```
[Route("api/[controller]")]
public class ValuesController : Controller
{
    private readonly IStringLocalizer _localizer;

    public ValuesController(IStringLocalizer<ValuesController> localizer)
    {
        _localizer = localizer;
    }

    // GET api/values
    [HttpGet]
    public IEnumerable<string> Get()
    {
        return new string[] {
            _localizer.GetString("_Key1"),
            _localizer.GetString("_Key2"),
        };
    }
}
```
8. Run kestrel
9. Execute /api/values?culture=nl
```
["Sleutel één","Sleutel twee"]
```
10. Execute /api/values?culture=en 

### Expected result
```
["Key one","Key two"]
```

### Actual result
```
["_Key1","_Key2"]
```

### Further technical details

- VS2017 RC (msbuild)
- Dotnet 1.1

I'm not sure what is causing the issue, removing "en" from supported languages result in the correct "Controlls.ValuesController.nl.resx" always being returned so it seems not related to the DefaultRequestCulture. I'm suspecting it has something to do with my OS language? I've followed https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization. Did I miss something?

**Comment by hishamco** [comment]
Your explanation is very clear, but it would be nice if you create an online repo that produce the issue, sometime the issue come from `project.json`, `AssemblyInfo.cs` .. ect.

Also let me know your OS language.

**Comment by WGroenestein** [comment]
My OS language is "en" (since that the one being ignored).

I've create a repro repo at WGroenestein/aspnetenlocalization@06c3760f23f3398d3a1affbf448c905f5e17dc43

I've also added a "shared" localizer as proposed in the docs. Both local and shared localizers give the same result.

**Comment by hishamco** [comment]
I'm not sure if the docs updated till now, anyhow let me check it now

**Comment by hishamco** [comment]
> Further technical details

    VS2017 RC (msbuild)

Unfortunately I don't have 2017 RC installed yet. @ryanbrandenburg can you please have a look to this

**Comment by ryanbrandenburg** [comment]
@WGroenestein this doesn't appear to be specific to VS 2017 but to a specific version of dotnet. I was able to reproduce this issue and filed it at dotnet/cli#4781.

**Comment by Eilon** [comment]
It looks like this was a bug in the default build process where the '`AssemblyNeutralLanguage`' attribute was erroneously (and incorrectly) included in default projects. There was a PR recently to remove that from the build and so this issue should go away: https://github.com/dotnet/sdk/pull/466/files
