### ISSUE TITLE
Travis Error

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#306]
I notice after the commit https://github.com/aspnet/Localization/commit/681e2e0329d7a2909c5d0b28346f0479524ba9bb the Travis status showed Error instead of Passed

/cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
That was due to Mono not fetching correctly. Will wait for another build to pass but that failure was probably just a hiccup in the system.

**Comment by hishamco** [comment]
I see, because I notice that in other repos, @Eilon is there an issue that reported this? If it is yes I will close this

**Comment by NTaylorMullen** [comment]
Yup, all is good now. All the builds were probably failing to the Mono piece failing.

**Comment by hishamco** [comment]
Thanks
