### ISSUE TITLE
Localize DataAnnotations validation messages in v 1.1.0

### ISSUE THREAD

**Issue by simon25608** [aspnet/Localization#307]
I have the solution applied in #286 by @ryanbrandenburg,  specifically: 
In the class startup.cs 

```c#
services.AddLocalization(options => options.ResourcesPath = "Resources");
services.AddMvc().AddDataAnnotationsLocalization(options =>
            {
                options.DataAnnotationLocalizerProvider = (type, factory) => factory.Create("RecursosGenericos", location: null);
            });
```

And in the Resources folder I have messages with the same keys as those defined in the core:

![image](https://cloud.githubusercontent.com/assets/18722357/21042163/129dd9bc-bdf0-11e6-8036-c7501ac75815.png)

and works correctly on my local computer but in my test environment (Windows server 2012 r2 standard) does not work. It should be all like in local since to publish I use the vs.

Dotnet local version:
![image](https://cloud.githubusercontent.com/assets/18722357/21042257/9dc503f8-bdf0-11e6-882a-ca98edc12342.png)

Dotnet test version:
![image](https://cloud.githubusercontent.com/assets/18722357/21042311/dfaffde0-bdf0-11e6-8dd3-e84b32512924.png)

In the ISS the Resources folder is not created, but if the folder is created it is with the resources file dll
![image](https://cloud.githubusercontent.com/assets/18722357/21043199/04ee9a62-bdf6-11e6-9c47-5f766309dd0a.png)

**Comment by hishamco** [comment]
Is the Resources folder not creating after your changes or in specific RID?

**Comment by ryanbrandenburg** [comment]
When you say the Resources folder is not created, do you mean just that the folder named "Resources" isn't created and you have culture specific folders instead? Because that's expected from a publish folder, all the .resx files have been compiled into those culture specific .dll's.

If you clone your repo onto your test environment and build it there rather than publishing it, does it work then? What about if you publish into and run from your development environment?

I tested general resource files in publish by publishing samples/LocalizationSample and it worked just fine, so there must be something more to this scenario. I assume you've double checked that the iteration of your project that's working on your dev box is the same as the one that's failing on the test box?

**Comment by simon25608** [comment]
> When you say the Resources folder is not created, do you mean just that the folder named "Resources" isn't created and you have culture specific folders instead? 

Yes

> I tested general resource files in publish by publishing samples/LocalizationSample and it worked just fine, so there must be something more to this scenario. I assume you've double checked that the iteration of your project that's working on your dev box is the same as the one that's failing on the test box?

I have also tested and it works on my test server.

I've tried replicating the example project code in my project and my development environment works, but in the test environment it does not work. The strange thing is that in version 1.0.1 if it works.

This is my
[project.json.txt](https://github.com/aspnet/Localization/files/646535/project.json.txt)

**Comment by ryanbrandenburg** [comment]
Yes, you must provide `SupportedUICultures` and `SupportedCultures` in order for things to be properly looked up from their resources. [This issue](https://github.com/dotnet/corefx/issues/1669)might shed a little light on the history of that decision. As for compatibility between 1.0.1 and 1.1.0 have you confirmed that when you revert your references to 1.0.1 while changing minimal other code the behavior reverts to what you expect? If so it would be great if you could throw a simplified version of your project up on a github repo so we could look into it.

**Comment by Eilon** [comment]
As best we can tell the issue is that the server has a different default locale than the local machine. By default .NET will choose the OS's language. It is always best to explicitly specify the expected language/locale in startup.cs.
