### ISSUE TITLE
Questions about localizing model metadata and validation messages

### ISSUE THREAD

**Issue by glen-84** [aspnet/Localization#31]
I'm interested to know how the new `IStringLocalizer` interface will tie into metadata and validation localization.

I'll get straight to the point: I have a prototype for an `IStringLocalizer` that allows you to swap out both the provider (of localized strings) as well as the formatter (used to format the localized string given zero or more arguments). What I'd like to know is, how easy or difficult will it be to replace the default validation messages with my own versions (because the string formatting may be different, to support pluralization, etc.). I would like to do this in one place, and not in each attribute.

I'm also curious to know if `System.ComponentModel.DataAnnotations` will be updated to work with the new localization features, as you (Damian) mentioned something about not being able to change things that are part of the framework. Will you just change the `DataAnnotationsMetadataProvider` so that it uses the attribute properties directly, instead of calling methods like `GetName()` (which do localization)? (example [here](https://github.com/aspnet/Mvc/blob/320507604a7045110ebf0b64f669cccddb6d9123/src/Microsoft.AspNet.Mvc.Core/ModelBinding/Metadata/DataAnnotationsMetadataProvider.cs#L87)).

Random: The name `IMetadataDetailsProvider` seems wrong for some reason. Is there a reason why it couldn't just be `IMetadataProvider`?

Great work so far. :wink:

**Comment by hishamco** [comment]
What if we call localizer["key"] in the data annotation attributes to localize the display name, error messages .. etc or creating localized ```DataAnnotationsModelMetadataProvider``` and  intercept ASP.NET MVC to analyzes the model metadata and retrieve the error messages from the subclass that supposed before

@DamianEdwards can you please share your thoughts about this

**Comment by Eilon** [comment]
Kind of related: http://haacked.com/archive/2011/07/14/model-metadata-and-validation-localization-using-conventions.aspx/

**Comment by c1rus** [comment]
In beta8 is ```AddDataAnnotationsLocalization```, but it seems its only for custom error messages. Would it be possible to localize the default validation messages?
And would it be possible to localize DisplayName?

**Comment by DamianEdwards** [comment]
This is tracked in aspnet/Mvc#3518 as it needs to be implemented in MVC, not here.
