### ISSUE TITLE
Investigating allowing any culture to be used (i.e. don't have to set Supported[UI]Cultures)

### ISSUE THREAD

**Issue by Eilon** [aspnet/Localization#312]
We were previously concerned about the cost of creating new `CultureInfo` objects (which at one point were prohibitively expensive to create), and also concerned about having an infinite-sized cache.

**Comment by ryanbrandenburg** [comment]
I wrote a small app to test out `CultureInfo` creation performance [here](https://github.com/ryanbrandenburg/CultureInfoPerf/blob/master/src/CultureInfoPerf/Program.cs). Creating a `new CultureInfo(string name)` takes ~1-2 ticks (that is, 1/10,000th of a millisecond) so long as the name exists. If the culture isn't recognized (and it thus throws an exception which we catch and drop) it takes ~250 ticks, definitly much larger, but at 2% of a millisecond not exactly huge. This also bore out in a quick and dirty removal of Supported[UI]Cultures I tried, the performance seems to be roughly the same with or without Supported[UI]Cultures on [the Localization sample](https://github.com/aspnet/Localization/tree/dev/samples/LocalizationSample).

Is there another scenario I should test out here?

**Comment by Eilon** [comment]
I think one of the scenarios we were most interested in for perf is what happens if you create a million non-existent CultureInfos. That is, `for(var i in 1..1,000,000) { var ci = new CultureInfo($"fake-locale{i}") }`.

The concern is that some underlying cache might grow indefinitely even though we're not caching anything ourselves.

Also, for the perf app you created, is there any reason to store everything in a `List<CultureInfo>`? Does that mimic anything we do in the Localization package?

**Comment by ryanbrandenburg** [comment]
Your milllion non-existent CultureInfos test gives the same result (~250 ticks/culture) as one culture being wrong a million times.

As far as the `List<CultureInfo>` "cache", I was just playing around with it to see if I COULD make perf bad, it doesn't mimic anything we do in Localization.

**Comment by Eilon** [comment]
Got it. And the test you ran was on .NET Core, right? Also I think it's worth doing extra due diligence and running on Linux as well. (Don't need to run on MacOS because that's dev-only.)

So, assuming all that goes well, and if the code in question was meant as an optimization, but is clearly not optimizing anything in practice, we can just get rid of it...

**Comment by ryanbrandenburg** [comment]
Good idea running this in Linux, creating a non-existant culture in linux is MUCH slower. It takes ~40ms/culture on Linux vs the same test on Windows taking 161ticks (much less than a ms). That seems like a deal-breaker to me.

**Comment by Eilon** [comment]
Sad. I guess that means we continue to restrict based on the developer-specified list?

**Comment by ryanbrandenburg** [comment]
Yeah, the current system is designed to avoid exactly these kinds of costs so I think we can just close this out and re-evaluate if Linux CultureInfo performance ever gets better.
