### ISSUE TITLE
RequiredAttribute's default message is not localizable

### ISSUE THREAD

**Issue by Ciantic** [aspnet/Localization#313]
I'm using 1.0.0 still.

It seems like the RequiredAttribute's default message is not localizable, but with EmailAddressAttribute it works correctly.

E.g.

With dummy localizer:

```C#
    public class TestLocalizer : IStringLocalizer
    {
        public LocalizedString this[string name]
        {
            get
            {
                return new LocalizedString(name, name + "test localizer");
            }
        }

        public LocalizedString this[string name, params object[] arguments]
        {
            get
            {
                return new LocalizedString(name, name + "test localizer");
            }
        }

        public IEnumerable<LocalizedString> GetAllStrings(bool includeParentCultures)
        {
            return new List<LocalizedString>();
        }

        public IStringLocalizer WithCulture(CultureInfo culture)
        {
            return this;
        }
    }
```

and this:

```C#
.AddDataAnnotationsLocalization(options =>
                {
                    options.DataAnnotationLocalizerProvider = (type, factory) =>
                    {
                        return new TestLocalizer();
                    };
                })
```

The problem in models such as: 

```C#
        public class RegisterAction
        {
            [EmailAddress] // Works: Goes thru TestLocalizer
            [Required(ErrorMessage = "works")] // // Works: Goes thru TestLocalizer
            public string Email { get; set; } = "";

            [Required] // Does NOT go thru TestLocalizer?
            public string Password { get; set; } = "";
        }
```

It works just fine with bare `[EmailAddress]`  but does not work with bare `[Required]`.

This is bit annoying, since I can't provide a default for the Required.

**Comment by hishamco** [comment]
@ryanbrandenburg is this a known issue in 1.0.0?

**Comment by dougbu** [comment]
@Ciantic what is the exact scenario? For example, are you looking at the attribute values controlling client-side validation or errors that end up in `ModelState`? A simple repro project hosted in a public GitHub repo would be ideal.

`ValidationAttribute`s with default `ErrorMessage` properties should _not_ be localized using an `IStringLocalizer`. So, the system overriding the message for `[EmailAddress]` would be a bug. (This is because .NET language packs already localize .NET classes. A realistic `IStringLocalizer` implementation would need to recognize the already-localized error messages.)

**Comment by Ciantic** [comment]
@dougbu exact scenario is that I have resx file but I can't localize `[Required]` cause it never comes to resx, only `[Required(ErrorMessage = "Required")]` comes to the resx file. Which means that the default text can't be translated. Above example is a simplified way to show that it can't come to resx file since it's not going to TestLocalizer either.

**Comment by dougbu** [comment]
@Ciantic as discussed in a few other issues, including aspnet/Mvc#5636, users need to explicitly opt into the new `IStringLocalizer` approach. If you don't opt in, regular .NET resources (in this case provided in .NET language packs) provide localization.

If you specifically want to use an `IStringLocalizer`, add an `ErrorMessage` value (either your default message or a key into your resource). If you just want to control messages for `ValidationAttribute`s, set `ErrorMessageResourceName` and `ErrorMessageResourceType` and use the traditional .NET resources approach.

If you prefer to leave the model types unchanged and do either of the above, @frankabbruzzese recently made a good [suggestion](https://github.com/aspnet/Mvc/issues/5636#issuecomment-273740151) to override `ValidationAttribute` properties in an `IValidationMetadataProvider` implementation.

**Comment by ryanbrandenburg** [comment]
Closing this, let us know if you still have questions.
