### ISSUE TITLE
Azure localization not working like in localhost

### ISSUE THREAD

**Issue by sanchapereira** [aspnet/Localization#318]
I have an ASP.NET Core Web App (version 1.1) using Resources files for Localization/Globalization. 
On localhost all resources are found, but on Azure the localizer only founds resources for Views.

For example, the resource file Controllers.HomeController.en-US.resx works ok in localhost but on Azure it only works if I rename it to Namespace.Controllers.HomeController.en-US.resx. On localhost the second name does not work.

**Comment by hishamco** [comment]
Strange!! @ryanbrandenburg did you face this before? or is it a new scenario that needs investigation?

**Comment by Eilon** [comment]
@ryanbrandenburg please take a look.

**Comment by Ponant** [comment]
@sanchapereira I am not having this issue with .Net Core 1.1 uploaded to Azure from VS 2017 RC. My resource file is
`Controllers.HomeController.en-US.resx` and the same file with `fr-FR`

**Comment by lasrol** [comment]
I tried to use "nb-no" and it failed after publishing to Azure. 

http://stackoverflow.com/questions/41851613/culture-is-suddenly-not-supported-anymore-on-azure-web-app

**Comment by ryanbrandenburg** [comment]
@sanchapereira it's hard to know without seeing your code, but I suspect you have the same (or a similar) problem as #314, namely that your namespace isn't matching the assembly name of your project. Please review #314 and the "Resource file naming" section of [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) documentation. If you're still having trouble after that then please upload a minimal reproduction app and link it here so I can take a look.

**Comment by ryanbrandenburg** [comment]
If that didn't fix it let us know, closing this out until then.
