### ISSUE TITLE
Add reference to Entropy samples to README.md

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Localization#338]
Since the samples in this repo aren't how we expect most people to use it we should explicitly reference the Entropy projects which demonstrate that usage (they can't live here because it would create a circular dependency).

We might also consider removing our "sample" in this repo since it doesn't demonstrate a scenario most people will need and might cause confusion (and the people who do need it are likely to have more domain knowledge).

**Comment by hishamco** [comment]
IMHO the simple in this is repo is trivial, it gives a basic idea of how localization works, also how we can use the various request culture providers

The only thing that I dislike is using tons of `WriteAsync` to generate the HTML content, It would be nice If we replace it with a simple `.cshtml` view

I'm agree with you that we may need to reference the 'Entropy` sample in the README.md

**Comment by Eilon** [comment]
Also we should either delete or move the samples in this repo at https://github.com/aspnet/Localization/tree/dev/samples/LocalizationSample and instead just point to the Entropy samples and docs.

**Comment by hishamco** [comment]
I'm totally agree with you @Eilon

**Comment by Eilon** [comment]
Thanks @hishamco !
