### ISSUE TITLE
Use Caching APIs

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#341]
I'm still wondering why we didn't use the Caching APIs that available in ASP.NET Core instead of creating new APIs that doing the exact same thing.

IMHO Memory Caching will be an equivalent to what's available now for caching the resource names, missing resources .. etc

/cc @Eilon @ryanbrandenburg

**Comment by Eilon** [comment]
No plans to change this. Even if this used the MemoryCache it would be as a private implementation detail and not from a service. Given that there's no known issue here, we're closing this issue.

**Comment by hishamco** [comment]
Perhaps no one use it for medium to large scale application, IMHO we need to add some performance test cases.

All of us know that the maintenance is hard, so why we didn't use the mature implementation that we have in ASP.NET Core

**Comment by Eilon** [comment]
@hishamco we will have perf investigations of this pending but we're just not there yet. So, unless there's already a known issue, we don't plan on changing the code. Because, for all we know, that might make the perf worse! 😄
