### ISSUE TITLE
[Suggestion] Add SessionRequestCultureProvider

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#344]
`Session` is one the important concepts in ASP.NET Core to keep track of the user info, culture is one of them. 

IMHO such provider would be a big plus, because the `Session` is backed by different cache mechanisms such as InMemory, Redis, SQL Server .. etc which will simplify the process instead of creating a new `RequestCultureProvider` to target any one of them

FYI I have seen a lot web apps and frameworks using the `Session` for localization purpose and NancyFx is one of them

**Comment by Eilon** [comment]
There are no plans to ship this in ASP.NET Core, but if you build one and release it as a NuGet package we'd of course be happy to link to it.

**Comment by hishamco** [comment]
Sure I will build one and share with you guys 😄

**Comment by hishamco** [comment]
FYI this is NuGet package link for [SessionStateRequestCultureProvider](https://www.nuget.org/packages/My.AspNetCore.Localization.Session), the source code available in my repo [My.AspNetCore.Localization.Session](https://github.com/hishamco/My.AspNetCore.Localization.Session)

Hope its helpful for those who are looking to use the Session-State to determine the culture information for their web applications in ASP.NET Core
