### ISSUE TITLE
Create Localization template for 'dotnet new'

### ISSUE THREAD

**Issue by Eilon** [aspnet/Localization#347]
With the new `dotnet new` extensibility, it would be nice to have an ASP.NET Core template that is fully localizable.

**Comment by Eilon** [comment]
cc @DamianEdwards

**Comment by hishamco** [comment]
Why we didn't add starter template like what we have in the [entropy](https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb) repo

**Comment by Eilon** [comment]
@hishamco that's essentially what we want in the template. Someone just has to do the work to wrap it in the structure that `dotnet new` uses (and make sure the content is appropriate).

**Comment by hishamco** [comment]
Sure, but in which repo shall we add this template, perhaps I 'll contribute to this if it's not assigned to anyone 😄

**Comment by Eilon** [comment]
@DamianEdwards where do you want this to live?

**Comment by DamianEdwards** [comment]
@Eilon can we just put it in the aspnet/Templates repo? As a new package?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2641
