### ISSUE TITLE
Add Localization cultures dynamically

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#351]
While we already have the `ResourceManager` implementation it's tough to add cultures dynamically at runtime, because resx needs msbuild i.e we need to restart the application.

I already saw many web applications & CMSs that have such feature, also there many folks asking for that with no luck 😞 

I already did a prototype to read resx using Xml APIs instead of `ResourceManager` which requires the application restart, but I ended up with how to replace the registered `RequestLocalizationOptions', is the MiddlewareFilter the best approach to accomplish this or is there any other idea?

Again we looking for a better solution for such scenario

/cc @DamianEdwards

**Comment by Eilon** [comment]
Hmm as you mention with ResourceManager, there are limitations of the underlying platform that make that difficult.

If you had your own system that dynamically loaded resources you should be fine. As far as the options go, yeah, you'd need to come up with your own pattern. The default request localization implementation probably doesn't deal with dynamic changes at all. But, fortunately, for the completely dynamic case, nothing else in ASP.NET Core cares how you decide the culture: as long as you add the `IRequestCultureFeature` to the system with whatever culture you choose, everything else in the system should just work.

**Comment by hishamco** [comment]
Such feature is requested a lot, because restarting the app is not a good solution at all, perhaps adding a new localization source such as PO may simplify this

**Comment by Eilon** [comment]
@hishamco right, with something like a PO-provider this gets a lot easier. The underlying limitation of loading DLLs is not something that can be changed or worked around in ASP.NET Core.
