### ISSUE TITLE
Default Supported(UI)Cultures should be all Cultures available

### ISSUE THREAD

**Issue by NCC1701M** [aspnet/Localization#352]
The default vaule for SupportedCultures and SupportedUICultures should be all Cultures available and not only the current one. I use a different approach for localization because I develop Intranet sites and I like to give administrators the possibility to translate the page on the fly. But with this concept you provide here it's way to complicated to add new languages.

 SupportedCultures and SupportedUICultures should only be there to restrict the cultures if set and not to ignore all cultures than current if not set.

**Comment by hishamco** [comment]
@NCC1701M this is back to an old discussion here issue #111

**Comment by hishamco** [comment]
FYI I already added an issue today #351 to think about the possibility to add a localization culture dynamically at runtime

Also there's another issue still open to support custom cultures #237, hope you follow those

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2640
