### ISSUE TITLE
IHtmlLocalizer parameter replacement stopped working.

### ISSUE THREAD

**Issue by julianpaulozzi** [aspnet/Localization#353]
IHtmlLocalizer parameter replacement stopped working.

`
@inject IHtmlLocalizer<SharedResource> SharedLocalizer
`
`
@{
    var subtitle = SharedLocalizer["Associate your {0} account.", ViewData["LoginProvider"]].Value;
}
`

Now subtitle print out literally:
**Associate your {0} account.**

**Comment by hishamco** [comment]
Could you please provide us with a repo to reproduce the issue?

**Comment by julianpaulozzi** [comment]
Unfortunately it's a private repo. I do not have another project with many languages to test.

But everything indicates that this occurred after upgrading many AspNetCore packages to 1.1.1.

Another change I made was to add Areas and [Feature Slices](https://msdn.microsoft.com/magazine/mt763233.aspx). I do not think it's the cause.

**Comment by hishamco** [comment]
Could you please create a new repo with minimal things to help us to reproduce the current issue

**Comment by hishamco** [comment]
Before that please have a look to the issue #343

**Comment by julianpaulozzi** [comment]
I could not reproduce the problem in other project. Soon as possible I will try to deconstruct the parts of project with trouble to see if I can.

**Comment by hishamco** [comment]
Seem naming issue, please check the issue that I mentioned [above](https://github.com/aspnet/Localization/issues/353#issuecomment-292370783)

**Comment by julianpaulozzi** [comment]
Yes, that may be it. But it should not replace the positional parameter in the same way (from inline text).

**Comment by julianpaulozzi** [comment]
Time has passed and I have not returned to this. I believe it was caused by the file's encoding format, I did not observe any more behavior like this when normalizing all files.

If I find something more relevant I return to the topic,
Thanks!
