### ISSUE TITLE
Run functional tests on InMemory server

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Localization#360]
Right now we're using `ApplicationDeployerFactory` to run our functional tests [as here](https://github.com/aspnet/Localization/blob/4c47065ae7716c2f480c41c135029875ceed1163/test/Microsoft.AspNetCore.Localization.FunctionalTests/TestRunner.cs#L61). We might want to do that for 2-3 tests just to ensure that there's no problems with Localization when run on Kestrel, but we want to move the rest of them to the InMemory server because it's faster and less prone to errors/flakiness.

**Comment by hishamco** [comment]
Totally agree 👍
