### ISSUE TITLE
Consider to use logging in the Request Culture Providers

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#372]
Based on the issue #370, I think it would be nice if we can add some logging into the default `RequestCultureProvider`s, specifically when the `CookieRequestCultureProvider` failed to parse the cookie, `QueryRequestCultureProvider` failed to parse the querystring

/cc @ryanbrandenburg @dougbu

**Comment by Eilon** [comment]
@ryanbrandenburg assigning this to you because I've assigned @hishamco 's PR at https://github.com/aspnet/Localization/pull/385 to you to review & merge.
