### ISSUE TITLE
Culture Provider selection order is not correct

### ISSUE THREAD

**Issue by dwloup69** [aspnet/Localization#375]
I am adding a QueryStrignRequestCultureProvider in my project. When I launch my app and load the site without the URL parameter but instead rely on the accept-language header the localization code always falls back to the default language. Does adding a custom culture remove all other standard providers?
In an attempt to have both I added the AcceptLanguageHeaderRequestCultureProvider in the list of RequestCultureProviders and this blocked the QueryStringRequestCultureProvider from working. 
I have not found a way to add a custom culture provider and still let a request fall back to one of the other providers. Any help would be appreciated.

After further testing. The order of selection for the culture is not as specified in the code. I'm using the Chrome browser. My custom provider has been inserted into the first element of the RequestProviderCultures list. Yet the language being selected is the second language in the AcceptLanguage header everytime. Removing the second language and then relying on the Accept-Language culture provider fails, it drops into the default language. I've even added the culture and uiculture parameters and they too are ignored. 

my localization options:
{Microsoft.AspNetCore.Builder.RequestLocalizationOptions}
    DefaultRequestCulture: {Microsoft.AspNetCore.Localization.RequestCulture}
    FallBackToParentCultures: true
    FallBackToParentUICultures: true
    RequestCultureProviders: Count = 4
    SupportedCultures: Count = 109
    SupportedUICultures: Count = 109
    _defaultRequestCulture: {Microsoft.AspNetCore.Localization.RequestCulture}

my RequestCultureProviders:
Count = 4
    [0]: {Microsoft.AspNetCore.Localization.QueryStringRequestCultureProvider}
    [1]: {Microsoft.AspNetCore.Localization.QueryStringRequestCultureProvider}
    [2]: {Microsoft.AspNetCore.Localization.CookieRequestCultureProvider}
    [3]: {Microsoft.AspNetCore.Localization.AcceptLanguageHeaderRequestCultureProvider}

Accept-Language is en-US
mkt parameter de-DE
default language it-IT

I am using aspnetcore version 1.1.1 and localization version 1.1.1 and localization.routing version 1.1.1.

Surprisingly the only language that is not being selected by either the custom provider, the query provider, the accept language provider is en-US. All others seem to be working. I have an en-us specific resx file in my project so that is not the issue.

**Comment by hishamco** [comment]
The localization is already have three request culture providers setup in the `RequestLocalizationOptions`:

1. `AcceptLanguageHeaderRequestCultureProvider`
1. `QueryStringRequestCultureProvider`
3. `CookieRequestCultureProvider`

The localization will fallback to the default culture if the current culture is not present in the winning provider

> Does adding a custom culture remove all other standard providers?
Not at all, but if you insert the custom one at the first item in the list it will be come the winning provider

Could you please show me the localization setup that you are using?

**Comment by dwloup69** [comment]
sorry I now realize that the non-market resx file is not 'en-US' once I created a specific resx file with Resource.en-us.resx then this corrected my problem. I was assuming it would do the same as older versions of .net and fallback to the non-market specific resx file.
