### ISSUE TITLE
Fallback to neutral culture if specific culture is not provided

### ISSUE THREAD

**Issue by kdaveid** [aspnet/Localization#376]
If SupportedCultures are provided as this
```
var supportedCultures = new CultureInfo[]
{
    new CultureInfo("de-DE"),
    new CultureInfo("en-GB")
};

services.Configure<RequestLocalizationOptions>(s =>
{
    s.SupportedCultures = supportedCultures;
    s.SupportedUICultures = supportedCultures;
    s.DefaultRequestCulture = new RequestCulture(culture: "en-GB", uiCulture: "en-GB");
});
```
and a browser with locale set to "de-CH" is hitting the page, the user gets an English localization by `AcceptLanguageHeaderRequestCultureProvider`.

The same goes for `QueryStringRequestCultureProvider`. If the user changes the `culture` parameter in URL from `?culture=en-GB` to `?culture=de` the provider would not pick it up either. 

Now, we could specify for each specific culture ("de-DE") the neutral culture ("de") but this is not very intuitive and hard to discover. At least it should be in the docs. :)

I've put together a [very basic playground](https://github.com/kdaveid/LocalizingTest) for testing.

**Comment by hishamco** [comment]
I download your sample and I tried both cases:
1. I set the language in browser with `de-CH`, when I run the page I got the right culture
2. I added the querystring `?culture=de` again I got the right culture

Could you please let us know which version of `dotnet` you are using?

**Comment by kdaveid** [comment]
Wow, wasn't expecting a feedback that fast! 

I should have noted that I expected a browser setting without specific culture. If you 
1. clear all locales in your browser 
2. add "German" (neutral culture "de", just the language)
3. reload page 
- Result: NO request culture provider is going to be hit and default lang ("en" in my example) will be chosen 
- Expected Result: `AcceptLanguageHeaderRequestCultureProvider` should accept `HTTP Header Accept-Language: de` as language

Same behavior goes for `QueryStringRequestCultureProvider`. This is particularly bad because: 
In case a user sits on a browser with preset culture "en-US" (Accept-Language header) but wants to manually override the culture (by changing the culture parameters in URL) `QueryStringRequestCultureProvider` will only be hit with the very specific culture defined in startup. 

Further, in scenarios where you have a route like `http://foo/{culture}/controller/action` with neutral cultures it would not work - although I have not looked into `RouteDataRequestCultureProvider`.

### Discussion
Chrome (58...) and Firefox (53.0.3) both allow the user to just select a neutral culture. Now this might be a rare case but after all the [spec says](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) a [language tag](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.10) only _may_ include a subtag like "-US". 

### Environment
I was testing on win with VS2017.2 and now on macOS, first 1.0.1 and now updated to 1.0.4
$ dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

david at dkmb in ~/Projects/
$ dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4

**Comment by hishamco** [comment]
@kdaveid let me check it now ..

**Comment by hishamco** [comment]
I follow the instructions above in Firefox `53.0.3`, it works as expected on `2.0.0-preview2-005905`, perhaps it was an bug in the version `1.0.1`

Could you please try your sample with the latest bits? Also I will try it the scenario on `1.0.1`

**Comment by hishamco** [comment]
Unfortunately seems `1.0.1` isn't installed in my laptop, hope you try the latest bit and it should works 😄

**Comment by kdaveid** [comment]
Hi Hisham

I've updated my 
- CLI tools -> `2.0.0-preview2-006127` 
- .NET Core Shared Framework Host to `2.0.0-preview2-25406-03`
- SDK to `2.0.0-preview2-006127`

You can not get any later bitwise ;)

I get the same behavior. Please confirm that you have the following settings in your browser:
1. German "de"
1. German (Switzerland) "de-CH"
1. English "en"
1. English (United States) "en-US"

If you run the app on `http://localhost:5000` you should get 
```
    Request culture provider: <none>
    CurrentCulture: en-GB | CurrentUICulture: en-GB
```

because there is no fall through. 

Changeing to `http://localhost:5000/?culture=de-DE` _OR_ `adding a culture "de-DE"` in browser settings you should get 
```
Request culture provider: QueryStringRequestCultureProvider
CurrentCulture: de-DE | CurrentUICulture: de-DE
```

Even if the user has "German" _AND_ "German (Switzerland)" as locale it will not be picked up. 

Are you running in VS 15.3 preview?

Please check out my repo on [master](https://github.com/kdaveid/LocalizingTest) and try again.

**Comment by hishamco** [comment]
@kdaveid every time you come with new steps 😄, I will download your repo again and I will follow the above instructions

BTW I'm using VS 15.3

**Comment by kdaveid** [comment]
No new steps. Just more detail for clarification.

If you have trouble restoring packages see [issue](https://github.com/dotnet/cli/issues/6763). ;-)

**Comment by hishamco** [comment]
Yep I don't have that version 😄

**Comment by hishamco** [comment]
I faced some issues while restoring your version, but it the sample works fine with version that I mentioned above

**Comment by kdaveid** [comment]
I re-created the sample app in VS15.3 and facing issues with RESX files. Just adding a new string in a file and VS blows up. 
I get back to you with a working sample once I have it.
**postboned**

**Comment by hishamco** [comment]
Could you please try the version that I'm using?

**Comment by kdaveid** [comment]
I tried to install `2.0.0-preview2-005905` but unfortunately I can't get it to run. 

Is it enough to install [this package](https://dotnet.myget.org/feed/dotnet-cli/package/nuget/Microsoft.DotNet.Cli.Utils/2.0.0-preview2-005905#targetframeworks), right? 
I tried to install via Nuget and Chocolatey but no success.

**Comment by Eilon** [comment]
From what I've understood in this thread, I think the observed behavior is how the design is supposed to work.

For each requested culture that the client (i.e. browser) sends, ASP.NET Core's system will look up:
1. The exact culture
2. The parent culture
3. The default site's language

If you want something like `de-DE` (language+locale) to be the "default German" then I think it should be registered as `de` (language only), so that other German locales (such as `CH`) would fall back to it.

**Comment by hishamco** [comment]
Exactly, registering `de` is enough, so the other German locales would fallback to it

**Comment by kdaveid** [comment]
Well, thank you for confirming what I already mentioned when opening this issue:
> Now, we could specify for each specific culture ("de-DE") the neutral culture ("de") but this is not very intuitive and hard to discover. At least it should be in the docs. :)

I tried to picture different scenarios and implications for you, _not asking a question_. 

In case I find the time, I'll create a pull request for updating the docs. This should be mentioned somewhere. It is frustrating to just try-and-error through it.

**Comment by Eilon** [comment]
@kdaveid sorry I misunderstood your initial post.

The "Adding Other Cultures" section at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization#resource-file-naming does mention adding culture-neutral languages:

> Each language and culture combination (other than the default language) requires a unique resource file. You can create resource files for different cultures and locales by creating new resource files in which the ISO language codes are part of the file name (for example, en-us, fr-ca, and en-gb). These ISO codes are placed between the file name and the .resx file name extension, as in Welcome.es-MX.resx (Spanish/Mexico). To specify a culturally neutral language, you would eliminate the country code, such as Welcome.fr.resx for the French language.

Do you have a suggestion on what we can do to improve that text?

**Comment by Rick-Anderson** [comment]
>Do you have a suggestion on what we can do to improve that text?

To specify a culturally neutral language, you would eliminate the country code, such as ~Welcome.fr.resx for the French language.~  as *Welcome.es.resx*  for Spanish.
