### ISSUE TITLE
Culture and Resource File seems to be compared case-sensitive

### ISSUE THREAD

**Issue by TsengSR** [aspnet/Localization#379]
In my Startup class I had the following setup

```
            services.AddLocalization(options =>
            {
                options.ResourcesPath = "Resources";
            });

...
            var localizationOptions = new RequestLocalizationOptions
            {
                SupportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("de-de"),
                    new CultureInfo("en-us"),
                    new CultureInfo("en-gb")
                },
                SupportedUICultures = new List<CultureInfo>
                {
                    new CultureInfo("de-de"),
                    new CultureInfo("en-us"),
                    new CultureInfo("en-gb")
                },
                DefaultRequestCulture = new RequestCulture("de-de")
            };
```

and a resource file in `Resources/SharedResource.de-DE.resx` and the text wasn't translated when I injected `IStringLocalizer<SharedResource> _localizer` and resolved it via `_localizer["sometext"]`.

After changing the `CultureInfo` above to the correct casing, it started to work. 

```

            var localizationOptions = new RequestLocalizationOptions
            {
                SupportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("de-DE"),
                    new CultureInfo("en-US"),
                    new CultureInfo("en-GB")
                },
                SupportedUICultures = new List<CultureInfo>
                {
                    new CultureInfo("de-DE"),
                    new CultureInfo("en-US"),
                    new CultureInfo("en-GB")
                },
                DefaultRequestCulture = new RequestCulture("de-DE")
            };
```

**Comment by hishamco** [comment]
You 're right about the key name it is case sensitive, AFAIK the `ResourceManager.GetString()` in previous versions of ASP.NET was case insensitive

@ryanbrandenburg is this a known bug
/cc @pranavkm @dougbu

**Comment by Eilon** [comment]
I believe that this is how localization works with .NET's Resource Manager. In System.Web the story was a bit different because ASP.NET compiled the RESX files itself, so it could do the case-insensitive matches.

However, in ASP.NET Core the resource culture lookup is done by .NET Core itself, and it based around loading satellite resource DLLs from disk. If the app is running on a case-sensitive file system, I think it makes sense for .NET Core's resource loader to try to locate the DLL using the file system's native behavior, which requires an exact case match.

**Comment by TsengSR** [comment]
Should have noted, it happened on my Windows 10 developer machine, if that makes any difference.
