### ISSUE TITLE
Fallback to wrong language preference when the top preference is unavailable

### ISSUE THREAD

**Issue by ChengTian** [aspnet/Localization#38]
I have the following configuration in my `Startup.cs`
```
var options = new RequestLocalizationOptions
{
    SupportedCultures = new List<CultureInfo>
    {
        new CultureInfo("zh-Hans"),
        new CultureInfo("en-US")
    }
};

app.UseRequestLocalization(options);
```
Then I set my language preference in IE with the following priorities (from highest to lowest):
1. ja (Japanese)
2. zh-Hans (Simplified Chinese)
3. en-US (English, United States)

However, the page fallback to en-US even when zh-Hans is available and has higher priority:

![capture](https://cloud.githubusercontent.com/assets/1383883/8263308/2fc9d2bc-168e-11e5-9761-6b7450181e97.PNG)

**Comment by hishamco** [comment]
This is happen because if the requested culture is not available in the supported cultures that you already define then the current implementation is looking for the ```DefaultRequestCulture``` which is the ```CultureInfo.CurrentCulture```, BTW i'm trying to get a fix for this issue ASAP

**Comment by hishamco** [comment]
@ChengTian can you try the fix that I made in my fork https://github.com/hishamco/Localization and let me know if it's solve the issue

**Comment by hishamco** [comment]
@ChengTian I'm asking if the issue got fixed or not

**Comment by ChengTian** [comment]
@hishamco , if you already test your changes, please send a PR. The owner of this repo will do some verification before merging your PR.

**Comment by hishamco** [comment]
Ok @ChengTian, I will send it ASAP

**Comment by hishamco** [comment]
I made this PR #50 to solve this issue

**Comment by Eilon** [comment]
@kirthik can you re-verify the fix in https://github.com/aspnet/Localization/pull/50, merge it, and add any extra tests that we need?

**Comment by DamianEdwards** [comment]
I actually think this should be fixed in `AcceptLanguageHeaderRequestCultureProvider`. Essentially, after it validates a culture, it should compare the result and if it's not using the culture that was passed in, it should move on to the next culture in the list (it already loops through the cultures, it just isn't doing the check).

https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNet.Localization/AcceptLanguageHeaderRequestCultureProvider.cs#L58

**Comment by kirthik** [comment]
merged 7b53bdd43e2e605a8eb686f22ceb558f46a1c4f5

**Comment by Eilon** [comment]
@kirthik mark as 3 - Done?

**Comment by kirthik** [comment]
Changed it.
