### ISSUE TITLE
Adding resource file in .Net Core 2.0 Preview 1 crashes VS 2017!

### ISSUE THREAD

**Issue by Ponant** [aspnet/Localization#388]
Did anyone experience this issue or has a workaround for it?
https://developercommunity.visualstudio.com/content/problem/73457/adding-resource-file-in-net-core-20-preview-1-cras.html

**Comment by Ponant** [comment]
repro https://github.com/Ponant/ResourceFileCrashCore20-preview1

**Comment by Ponant** [comment]
same issue (closed by VS Team while people continue complaining)
https://developercommunity.visualstudio.com/content/problem/22058/crash-when-editing-resource-resx-files.html

**Comment by hishamco** [comment]
Try to move the issue to the [Home](http://github.com/aspnet/home) repo

**Comment by Ponant** [comment]
done
