### ISSUE TITLE
ResX  support in vNext assembly

### ISSUE THREAD

**Issue by YZahringer** [aspnet/Localization#39]
Hello,

How to manage the translations in a vNext project? There is not "ResX Item Template" when adding files to project... The ResX files are no longer supported? There is a replacement?

Thank you,
Best regards,
Yann

**Comment by hishamco** [comment]
@YZahringer it's in progress, you can have a look to @DamianEdwards repo https://github.com/DamianEdwards/i18nStarterWeb

**Comment by DamianEdwards** [comment]
Yep, in progress. RESX will be supported, we're building out the support now.

**Comment by hishamco** [comment]
@DamianEdwards i think issue should be closed

**Comment by YZahringer** [comment]
The support of code generation for ResX is not expected?

With PublicResXFileCodeGenerator resources were named and it allowed to view errors (eg. missing resource) at compile time.
