### ISSUE TITLE
Advice performance issues with shared vs non-shared resources

### ISSUE THREAD

**Issue by Ponant** [aspnet/Localization#391]
I have around 20 resource files for each culture and I am covering 4 cultures. This totals to a bunch of resource files embedded in folders etc, so that it gets a bit uneasy to navigate through. 

I came across the docs and read about SharedResources, where we would create a dummy class and dump in "global resources". I tested it and it works, which makes me think that I could now, for each culture, put all entries of the 20 resource files into a SharedResource.XX.resx (XX=culture). That would simplify a lot my resources folder; however, the files get bigger, with each having around 200 entries, so I wonder if there are any lookups/performance penalties to be expected? Or any other limitation? 
I always thought that resx's are somewhat indexed like a db, in which case I would expect to have no loss of performance. Please advise if possible. Thanks!

**Comment by hishamco** [comment]
AFAIK localization cache the resource entries as well as missing entries too, which will improve the performance. You could have a look to `ResourceNamesCache` and `ResourceManagerStringLocalizer` for more details.

**Comment by hishamco** [comment]
Also you could look to this issue #162

**Comment by Ponant** [comment]
.Sorry @hishamco , I did not get quite well whether you answered the question, namely if reducing the number of resx files but with a larger number of entries would kill performance, improve it or have no impact?

**Comment by hishamco** [comment]
I didn't the answer your question 100% but I give you some information that I knew 😄, did you make a benchmark for your current working project?!!

**Comment by Ponant** [comment]
No, no benchmark, this is why I ask before transferring a bunch of values and refactoring of resx's....

**Comment by hishamco** [comment]
BTW @ryanbrandenburg did a benchmark for localization long time back and the result was very good, hope he reply to you ASAP

But i'm not sure if he was using a shared resources or not

**Comment by Ponant** [comment]
Hi @ryanbrandenburg ,
I would appreciate your advice on that. Do you expect a loss of performance if I put all entries of all my resx files into a global resource for each culture? That simplifies drastically my resources folder! But I am not sure I will pay heavily in performance as now we query large files. Thanks

**Comment by ryanbrandenburg** [comment]
@Ponant we don't have numbers on that one way or another. Is there a particular reason you're concerned this scenario will be non-performant? Your files don't sound particularly large, so my instinct is that even if that scenario WERE slower, it wouldn't be particularly apparent to you.

**Comment by Ponant** [comment]
@ryanbrandenburg , I am concerned that each resx file gets large with circa 500 entries. If you think that is not an issue, then what would be a limitation of using a global resource? If there is no limitation, then I will clearly head for this because the resources folder is much cleaner.

**Comment by Ponant** [comment]
Also, I am wondering if the resx files are somewhat indexed like a database, or not?

**Comment by ryanbrandenburg** [comment]
I do not know of any limitations of global resources over per-class resources. I don't know abou "indexed like a database", but I believe there are caches at a couple levels which should make for quicker resource returning.
