### ISSUE TITLE
I18n, localization roadmap, features

### ISSUE THREAD

**Issue by brgrz** [aspnet/Localization#397]
I was wondering if the current feature set will be expanded in any way given that i18n support is rather basic  (the only thing new being the two interfaces) and most of the features the same as they were in MVC 5 (Data annotations, resx files).

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization

Also, how come MS is staying with resx files which are a 20 year old technology and have never evolved to cover more complex i18n scenarios.

It'd be nice to see some advances in the field of i18n, simple string replacement methods are not enough or something that would suffice in 2017.

I was thinking something along the lines of Angular.io i18n features, which is based on XLIFF and supports pluralization, genders, selections, etc.

https://angular.io/guide/i18n

What is Microsoft's take on this?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2635
