### ISSUE TITLE
Localization & Output Caching

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#40]
I'm wondering if the **Output Caching** will block the localization APIs from retrieving the right values for the current culture, or shall we need sort of `VaryByCustom` to update the correct values based on the current culture

/cc @DamianEdwards

**Comment by hishamco** [comment]
@kirthik please your thoughts about this

**Comment by Eilon** [comment]
There are no features currently planned for directly solving this. The correct approach at this time is to set the appropriate VaryBy headers on the response.

**Comment by hishamco** [comment]
Thanks @Eilon, is there a plan to support such thing

**Comment by Eilon** [comment]
It needs to be done by the user manually.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2652
