### ISSUE TITLE
Support for async create methods in IStringLocalizerFactory and IHtmlLocalizerFactory

### ISSUE THREAD

**Issue by cruikshj** [aspnet/Localization#405]
I have not found a good way of implementing custom localizer factories that load resources with async methods, such as from a database or from a file on the file system.  I understand these implementations could use synchronous methods, but that seems counter intuitive in a web application.

Is there some way of doing this that I have missed?

**Comment by hishamco** [comment]
AFAIK localization support synchronous version, you can refer to my [sample](https://github.com/aspnet/Entropy/tree/dev/samples/Localization.EntityFramework)

**Comment by Eilon** [comment]
There is no support for async loading of resources at this time.

cc @DamianEdwards

**Comment by hishamco** [comment]
The good thing about the current implementation is the resources are cached, so you could do similar thing, but you need sort of refreshing the cache if a new resource was added

**Comment by Eilon** [comment]
Closing because there are no plans to implement this. Resources can be pre-loaded, or you can do synchronous calls to get the data on-demand.
