### ISSUE TITLE
ResourceManagerStringLocalizer._missingManifestCache is empty after calling IStringLocalizer.WithCulture

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Localization#408]
In `ResourceManagerStringLocalizerFactory` we have a `_localizerCache` that holds and reuse the different `ResourceManagerStringLocalizer` so if we run below code we always should get the same instance of `IStringLocalizer` as `localizer`.
```c#
public HomeController(IStringLocalizer<HomeController> localizer) { }
```
If we call the [`IStringLocalizer.WithCulture(...)`](https://github.com/aspnet/Localization/blob/42a87b383daaa998fb524b2c17786c073c277840/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L150) on the injected `IStringLocalizer` we are always getting a new instance of the `IStringLocalizer` with or without culture. 

In each instance of `IStringLocalizer` we are creating the [`_missingManifestCache`](https://github.com/aspnet/Localization/blob/42a87b383daaa998fb524b2c17786c073c277840/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L22) as a field. 

In the [`GetStringSafely`](https://github.com/aspnet/Localization/blob/42a87b383daaa998fb524b2c17786c073c277840/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L203) we are checking with the [`_missingManifestCache`](https://github.com/aspnet/Localization/blob/42a87b383daaa998fb524b2c17786c073c277840/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L216).

Either the `IStringLocalizer.WithCulture(...)` or the `_missingManifestCache` need to be adjusted so the `_missingManifestCache` will be reused between executions of `IStringLocalizer.WithCulture(...)`.

**Comment by Eilon** [comment]
@kichalla can you take a look?

cc @ryanbrandenburg in case you have some prior knowledge about this.

**Comment by kichalla** [comment]
> In ResourceManagerStringLocalizerFactory we have a _localizerCache that holds and reuse the different ResourceManagerStringLocalizer so if we run below code we always should get the same instance of IStringLocalizer as localizer.

Yes, this is correct and it does create a single instance as expected.

> If we call the IStringLocalizer.WithCulture(...) on the injected IStringLocalizer we are always getting a new instance of the IStringLocalizer with or without culture.

As far as I can tell, this is expected. Here `WithCulture` acts like a factory for creating localizers which use a different version of culture than the culture of the current thread.

#### Example scenario
An application is designed for en-US (so the culture and currentuiculture on the thread would be en-US), but there is a page in the application where you would like to show text for different cultures. In this scenario instead of modifying the current thread cultures, you could just create new localizer instances with the supplied culture.

@Tasteful Curious, how are you using `WithCulture` in your scenario?

**Comment by Tasteful** [comment]
@kichalla if you take a look in this https://github.com/aspnet/Localization/issues/156 issue the singleton cache was created in the factory so the `_missingManifestCache` instance will be the same for the same culture during application lifecycle.

If we call the `WithCulture` we are creating a new stringlocalizer for every call, example
```
public class XyzController : Controller
{
    public XyzController(IStringLocalizer<XyzController> localizer)
    {
        var otherCulture = new CultureInfo("otherCultureName"); //replace with culture name
        var otherCultureLocalizer = localizer.WithCulture(otherCulture);
        var localizedString = otherCultureLocalizer["resource-key-that-not-exists"];
    }
}
```
In the above `XyzController`:
* injected the same instance of localizer in ctor, this instance is comming from the cache in the factory
* variable `otherCultureLocalizer` will always be reconstructed as a new instance. For each instance of `otherCultureLocalizer` we have a private instance of the `_missingManifestCache` field. In the `GetStringSafely`-method check if we have a missing resource and if that is the case we return `null` directly to not request the string from `ResourceManager` for resources that not exists more than once, I think that asking `ResourceManager` is an expensive operation for keys that not exists, otherwise the `_missingManifestCache`-cache should not be needed.

>Curious, how are you using WithCulture in your scenario?

I found this when I checked the code for the implementation to be able to create an own stringlocalizer/stringlocalizerfactory that reading the resx-files with the `IFileProvider` from a folder in the website instead of bundle them inside the assembly.

**Comment by kichalla** [comment]
@Tasteful Sure, I understand what the code is doing and yes here each instance of localizer created by `WithCulture` creates one cache instance of the `_missingManifestCache` and it seems unnecessary. The performance of this piece of code is not efficient as it was meant to be (in the `WithCulture` scenario) but this scenario is also rare which brings up the question of whether we need to worry about changing anything here. The most common scenario is still using the localizer which uses the culture on the thread.

**Comment by kichalla** [comment]
Closing this issue now as we do not plan to take any action here.
