### ISSUE TITLE
After upgrate to Net Core 2.0 Localization in View (Inject) is not Working

### ISSUE THREAD

**Issue by lucianparvu** [aspnet/Localization#410]
Hello,
After upgrate to Net Core 2.0 Localization in View is not Working, but In Controller works .
I tried to create a default project in Net Core 2.0 and is not working too .
ConfigureServices
-  services.AddLocalization(options => options.ResourcesPath = "Resources");
- services.AddMvc()
            .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
            .AddDataAnnotationsLocalization();
- In Folder Resource I have SharedResource.fr-FR.resx
- Shared Resource Class :
namespace PL
{
    public class SharedResource
    {
    }
}
- @inject Microsoft.Extensions.Localization.IStringLocalizer<PL.SharedResource> SharedResource
-  @SharedLocalizer["Add"]
public IStringLocalizer<SharedResource> _SharedResource;
 public HomeController(IStringLocalizer<SharedResource> sharedResource)
        {
            CultureInfo uiCulture = new CultureInfo("fr-FR");
            CultureInfo.CurrentUICulture = uiCulture;
            CultureInfo.CurrentCulture = new CultureInfo("fr-FR");
            _SharedResource = sharedResource;
        }
But I I test with a ViewData from controller is working
 ViewData["Message"] = _SharedResource["Add"];
Thank's

**Comment by Eilon** [comment]
@kichalla another investigation.

**Comment by kichalla** [comment]
@lucianparvu I was unable to repro the problem at my end, but to be sure, can you try finding out what the culture is on the view?

For example, you can try printing them out in the view:
```
<h1>CurrentCulture: @System.Globalization.CultureInfo.CurrentCulture.ToString()</h1>
<h1>CurrentUICulture: @System.Globalization.CultureInfo.CurrentUICulture.ToString()</h1>
<h1>@SharedResource["Add"]</h1>
```

**Comment by kichalla** [comment]
Based on your code, looks like you were following this article. I wasn't able to repro the issue, so closing it for now. If you can still repro it, could you share a small repro app
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization
