### ISSUE TITLE
FileExtension localization problem

### ISSUE THREAD

**Issue by Stefanone91** [aspnet/Localization#412]
Hello everyone,
I'm trying to localize the error message of "FileExtension" attribute but it seems not working.
I've successfully implemented the localization for "Required" attribute as explained in the official ASP.NET core guide.
I've created a simple project to reproduce the issue:
Inside the "registration" page i've added an input elemente for file upload wich is linked to RegisterViewModel, containing the "Immagine" IFormFile variable.
This IFormFile has the Required attribute and the FileExtension attribute. They are working well but not the translation of FileExtension's ErrorMessage .

Link to GIT:
https://github.com/Stefanone91/LocalizationFileSizeIssue

**Comment by Eilon** [comment]
Hmm, it looks like we simply never added support for this attribute! Not sure why.

@dougbu @rynowak @danroth27 - any guesses as to why we never did it? We just forgot?

**Comment by Eilon** [comment]
BTW by "never added support" I mean in MVC - I'll move the bug.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#6771
