### ISSUE TITLE
Localization in JSON file

### ISSUE THREAD

**Issue by Jenan** [aspnet/Localization#414]
Hello,

is it possible to create a localization in JSON files, like this:

```
App.json
App-fr.json
```

With content like this:

```
{
	"culture": "en",
	"texts": {
		"HomeTitle": "Home page welcome"
	}
}
```

For example in View call - `@Localize("HomeTitle")`

It's single file per application and per language.

Is it some way how configure localization module to do this approache?

Thank you.

**Comment by hishamco** [comment]
Of course you can, I already did that long time back, I think it's a time to write a useful blog post that explaining how you can implement `JsonConfigurationRequestCultureProvider` as well as `JsonStringLocalizer`

Hopefully I'll refer to the link ASAP

**Comment by hishamco** [comment]
FYI this would be easier with ASP.NET Core Configuration APIs

**Comment by Eilon** [comment]
There is no built-in JSON-based provider for localization, but @hishamco wrote an Entity Framework Core one that you can see here: https://github.com/aspnet/Entropy/tree/dev/samples/Localization.EntityFramework. You could try modifying that to work with JSON files instead.

Closing because there are no plans to implement this.

**Comment by hishamco** [comment]
@Jenan it has been awhile from my latest comment, but I didn't forget to reply on this, I created two repos one for [Localization JSON Request Culture Provider](https://github.com/hishamco/My.AspNetCore.Localization.Json) and another one for [JSON Localization Resources](https://github.com/hishamco/My.Extensions.Localization.Json)

Hope this answer you & many other folks questions 😄

@Eilon perhaps we need to add this to Localization `README.md`, if you don't mind while the 'JSON` is very important for many

**Comment by Jenan** [comment]
Thank you. :)
