### ISSUE TITLE
FallBackToParentCultures does not respect zh-CN and zh-Hans

### ISSUE THREAD

**Issue by yufeih** [aspnet/Localization#415]
When `FallBackToParentCultures` is set, *zh-CN* will not be fallback to *zh-Hans*.

Locale fallback simply trim the last section after dash, this is incorrect:

https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L206

*zh-Hans* should be a parent locale of *zh-CN*

**Comment by hishamco** [comment]
Could you please refer to issue #273, seems `zh-{cultures}` are more complicated than I knew 😄

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2634
