### ISSUE TITLE
Organize Microsoft.Extensions.Localization

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#419]
As we knew `ResourceManagerStringLocalizer` is the default `StringLocalizer` for localization in ASP.NET Core, but the needs for Pluralization or adding a new localizer such as `POStringLocalizer` required the namespace to be organize to have namespace per `StringLocalizer`, this is common in other ASP.NET Core repos such as Configuration, Security .. ect

IMHO it would be nice if we add resource management classes to `Microsoft.Extensions.Localization.ResourceManager` namespace, so each upcoming `StringLocalizer` will be placed to a separated namespace which makes the things more organized than what we have right now

I knew perhaps it's too late, but may be we can consider it for upcoming next release

/cc @Eilon

**Comment by Eilon** [comment]
Hi @hishamco , if I understood correctly, is this a breaking change? If so, there usually has to be an *extremely high* value to the change to justify making a breaking change.

I agree there could be better ways to organize the namespaces, but, at this time I don't see a value that is high enough.

Can you share more info on this?

**Comment by hishamco** [comment]
Yep it's a breaking change, that's why I suggest it would be suitable for 3.0.0, perhaps the main issue that we don't think about this, because we have only one resource provider which is `ResourceManager`, IMHO this will have great value if we planned to support `POStringLocalizer` which is asked a lot by the community, FYI this is already done in the past, but the PR is closed for unknown reason

So supporting `POStringLocalizer` and pluralization #17 #305 in 3.0.0 alongside with the namespaces organization will add a value, and makes me happy too 😄

**Comment by Eilon** [comment]
Closing because there are no plans to implement this. Moving just a few types to a new namespace is just too small a change to make it worth doing a breaking change. We can add new types to new namespaces if there's enough to justify it.

**Comment by hishamco** [comment]
As I said before it will have a good value if we support a new `StringLocalizer`
