### ISSUE TITLE
Localization in Html Strings

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#42]
@DamianEdwards is there a plan to localize HTML strings in the following
`HtmlString,
MvcHtmlString,
HttpServerUtility.HtmlEncode,
HttpUtility.HtmlEncode` and **<%: %>**  Code Nugget Syntax

**Comment by DamianEdwards** [comment]
We're working on that right now over in the MVC repo

**Comment by hishamco** [comment]
Thanks ..
