### ISSUE TITLE
ResourceManagerWithCultureStringLocalizer bug (or by design?)

### ISSUE THREAD

**Issue by hikalkan** [aspnet/Localization#421]
Hi,

https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerWithCultureStringLocalizer.cs#L126

Shouldn't this be:

````C#
return new LocalizedString(name, value ?? name, resourceNotFound: value == null);
````

**Comment by hishamco** [comment]
It should be
```csharp
return new LocalizedString(name, value ?? name, resourceNotFound: value == null, searchedLocation: _resourceBaseName);
```

In case of logging the missing resources

**Comment by Eilon** [comment]
@ryanbrandenburg can you take a look at @hishamco 's PR at https://github.com/aspnet/Localization/pull/422?

**Comment by ryanbrandenburg** [comment]
Thanks for the report @hikalkan and the fix @hishamco.

**Comment by hikalkan** [comment]
Thank you all :)
