### ISSUE TITLE
Why we need UseRequestLocalization with no localization option?

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#427]
I don't see any use of this overload anywhere. Also the supported cultures in the `app.UseRequestLocalization()` will null (if I'm not wrong)

So is there any use of empty overload that I don't know?!!

/cc @pranavkm @ryanbrandenburg

**Comment by Eilon** [comment]
It's used when all the options come from DI. The middleware constructor takes the options from DI: https://github.com/aspnet/Localization/blob/f650de8cdf5214bcbb2e88210baac0f99ce3d053/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L33

**Comment by hishamco** [comment]
@Eilon could you show me where is the `IOptions<RequestLocalizationOptions>` injected in DI?

**Comment by Eilon** [comment]
@hishamco you would add it in ConfigureServices in your app. There might not be an extension method specifically for this, but you call something like `services.Configure<RequestLocalizationOptions)(o => { o.X = "x"; o.Y = "y"; });

**Comment by hishamco** [comment]
This is similar to Localization.StarterWeb in entroy repo [here](https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Startup.cs#L67), but again we should pass the option to the localization middleware `app.UseRequestLocalization()` as shown [there](https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Startup.cs#L109)

**Comment by Eilon** [comment]
@hishamco both ways are valid.

**Comment by hishamco** [comment]
Yep, but if you look closely both way need to pass the localization options to the `app.UseRequestLocalization()`, so my question is why we need the empty overload?!!

**Comment by hishamco** [comment]
Seems you didn't get my point 😄, I'm talking about adding a new middleware, I was talking about `RequestLocalizationMiddleware` [here](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/ApplicationBuilderExtensions.cs#L51) where the options is need, again I don't see any value for [this](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/ApplicationBuilderExtensions.cs#L21) overload

**Comment by Eilon** [comment]
If you call this method:

https://github.com/aspnet/Localization/blob/8ca523466cc053688116f9164aa94c5e1e3210c0/src/Microsoft.AspNetCore.Localization/ApplicationBuilderExtensions.cs#L21

It will work just fine, as long as in `ConfigureServices` you set up the required options.

I don't think that overload has *much* value, but it does work.

**Comment by hishamco** [comment]
> It will work just fine, as long as in ConfigureServices you set up the required options

Again we come back and forth to the same point, that we need to setup the required options, as you mentioned before

Even if we called `app.UseRequestLocalization()` without configuring the localization options it will works with the default cultures, this because the `IOptions<RequestLocalizationOptions>` injected from DI as shown [here](https://github.com/aspnet/Localization/blob/8b03ee8c81b61a852a586740c4db7b09c17f5e76/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L37)

So this will conclude that the empty constructor doesn't have a great value unless the user rely on the default supported cultures & supported UI cultures which doesn't make sense to me at all

I'm not sure if this by design or is there a secret behind this 😄, hope you open this for discussion unless there's a proper reason to close. Perhaps we may need to remove it in the future if i doesn't has any value .. who knows

**Comment by Eilon** [comment]
The overload is harmless, and removing it would be a breaking change. We reserve breaking changes only for cases where there is an important business value, and I don't think there's enough value here.

**Comment by hishamco** [comment]
I don't wanna introduce a breaking-changes right now, but we can consider it in the upcoming major release. 

I will be waiting for the other team members, may be there's something behind this overload
