### ISSUE TITLE
DomainRequestCultureProvider 

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#43]
It's quite often to detect the localization culture based on domain or sub domain, this provider may support various formats such as:

en.domain.com
domain.com.en
domain.com.au
domain.com/en-au/default.aspx

**Comment by hishamco** [comment]
@kirthik can I start to make a PR to support ```DomainRequestCultureProvider```?

**Comment by miloush** [comment]
Even most of the Microsoft's web sites use path segment for localization and I would expect it to be one of the built-in providers. It is also easier to provide links to specific localizations in that case.

On the other side I don't think the host names - especially the TLD - are good idea, as you would basically need a lookup table for most of them (.at) and there are tricky cases too (.in) ...

**Comment by hishamco** [comment]
@miloush the basic idea that I mentioned before is all about segements :smile: , regarding the .it, .in .. etc they are parent cultures so no need to lookup table

**Comment by miloush** [comment]
@hishamco No these are not parent cultures. .it is, but you have en-IN, ta-IN, sa-IN where parent cultures are en, ta resp. sa. The same with China (parent is zh) and Arabic cultures (parent is ar) and pretty much all others where the culture neutral name differs from the culture specifier (.at .nz .cz ...). And don't forget there are cultures that differ by script (like sr-Cyrl-RS vs sr-Latn-RS).

**Comment by hishamco** [comment]
anyway it's in a Backlog, and may it need a good design
thanks @miloush

**Comment by Eilon** [comment]
Closing because we have no plans to ship this.

**Comment by hishamco** [comment]
This could be done easily now after shipping `RouteDataRequestCultureProvider` as well as middleware as filter 😄
