### ISSUE TITLE
StringLocalizer cannot be created when default namespace for assembly doesn't match the assembly name

### ISSUE THREAD

**Issue by dmitrykolchev** [aspnet/Localization#431]
Invalid name of localization resources created when default namespace for assembly doesn't match the assembly name.
1. Create new assembly (Sample.SharedComponents)
2. Change default namespace that wouldn't match assembly name (Sample)
3. Add view components (Shared/Components/Toolbar/ToolbarViewComponent.cs, Shared/Components/Toolbar/Default.cshtml  as embedded resource)
4. Add localization resources (Resources/Shared/Components/Toolbar/ToolbarViewComponent.en.resx and Resources/Shared/Components/Toolbar/ToolbarViewComponent.de.resx)
5. Add attribute [assembly: ResourceLocation("Resources")]
ResourceManagerStringLocalizerFactory will create base name:
Sample.SharedComponents.Resources.Sample.Shared.Components.Toolbar.ToolbarViewComponent because assembly name doesn't match default namespace. 

It will be nice to add DefaultNamespace property in ResourceLocationAttribute and use this property when defined instead of assembly name to override default behavior of ResourceManagerStringLocalizerFactory 

Thank you

**Comment by hishamco** [comment]
I think this is a duplicate for #398 #340

**Comment by mkArtakMSFT** [comment]
Closing this as a dupe to https://github.com/aspnet/Localization/issues/340
