### ISSUE TITLE
Should I write all "ErrorMessage" for all "RequiredAttritue"?

### ISSUE THREAD

**Issue by 717009629** [aspnet/Localization#432]
![111](https://user-images.githubusercontent.com/16289643/33814721-332c7e0c-de67-11e7-946e-1f65d22e5214.png)
![112](https://user-images.githubusercontent.com/16289643/33814733-40373fba-de67-11e7-9de7-ec6b48ca0b85.png)

If I have 100 [Required], should I write  100 "ErrorMessage"?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, is there a way to simplify this?

**Comment by ryanbrandenburg** [comment]
I believe this is a dup of https://github.com/aspnet/Localization/issues/286#issuecomment-249046258. Specifically you can find our recommendation for this scenario [here](https://github.com/aspnet/Localization/issues/286#issuecomment-249632215). A more comprehensive solution would have to come from the corefx team.

Do those resources answer your question?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2631
