### ISSUE TITLE
Sugesstion for AssemblyWrapper

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#48]
While I'm digging into the **Localization** repo, I notice that ```AssemblyWrapper``` is hosted into **Microsoft.Framework.Localization.Internal** namespace. My suggestion as the following:

1- If ```AssemblyWrapper``` intend to be used internally, so why it's used here https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Framework.Localization/ResourceManagerStringLocalizer.cs#L51 i.e. why it has been passed into a public constructor, so I made this PR #45. Also we should change the access modifier into ```internal``` instead of ```public``` here https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Framework.Localization/Internal/AssemblyWrapper.cs#L10 

2- If ```AssemblyWrapper``` intend to be used in public, i think the namespace **Microsoft.Framework.Localization.Internal** doesn't make sense, it will be nice if we rename it to a meaningful namespace

**Comment by Eilon** [comment]
The `.Internal` namespace is for types that are for internal use only, but are left as `public` because often other people want to call them but they are "use at your own risk."

**Comment by hishamco** [comment]
Thanks for clarification
