### ISSUE TITLE
Investigate adding back ResourceCulture caching (without the allocations)

### ISSUE THREAD

**Issue by justinvp** [aspnet/Localization#52]
I see commit d22adcbef022291fd87eff4d28179e952ea480c4 removed ResourceCulture caching because "perf testing shows it has no benefit".

@DamianEdwards, do you still have the perf tests?

I see a lot of unnecessary heap allocations in the old caching code that may have skewed the perf results (e.g. it was more expensive caching with all the extra allocations than not doing caching):

 - `CacheKey` is allocated because it is a class. Fix: change to struct
 - `CacheKey`'s constructor allocates an anonymous object to get a combined hashcode. Fix: don't allocate an anonymous object to get the combined hashcode
 - A closure is allocated for the `GetOrAdd` to pass the two cultures. Fix: avoid the closure by getting the two cultures from the key.
 - A delegate instance is allocated for the factory passed to `GetOrAdd`. Fix: avoiding the closure allows the C# compiler to cache and reuse a single static delegate instance.

I'd like to look into whether there are any perf wins by adding back the caching without these allocations.

Alternatively, it might be worth considering making `ResourceCulture` a struct instead of a class, as its just a holder for the two cultures (similar to `KeyValuePair<TKey, TValue>` which is a struct). Then there really wouldn't be a need to cache `ResourceCulture` as it wouldn't be allocated on the heap at all.

**Comment by DamianEdwards** [comment]
@justinvp I tested by generating load on the sample app in the solution and looking at the throughput rate. I used WCAT to generate the load but any load gen tool would be fine. We welcome any investigation you might do! Please share the results here and/or send a PR if there are tangible gains.

**Comment by danroth27** [comment]
@justinvp Any update on this investigation?

**Comment by Eilon** [comment]
We're not aware of any changes required here. If new info arises, we can reconsider.
