### ISSUE TITLE
Rename ResourceNotFound property in LocalizedString 

### ISSUE THREAD

**Issue by kirthik** [aspnet/Localization#53]
One of the comments in this PR - https://github.com/aspnet/Mvc/pull/2701 was that `ResourceNotFound` name is confusing and negative naming should we avoided. LocalizedHtmlString class in MVC localization follows the same pattern. We should re-name both properties to something more appropriate

**Comment by dougbu** [comment]
[Comments](https://github.com/aspnet/Mvc/pull/2701#discussion_r33599530) also suggested the property may not be necessary at all. In a similar [vein](https://github.com/aspnet/Mvc/pull/2701/files#r33599401), should revisit whether `LocalizedString.Key` and `LocalizedHtmlString.Key` are needed.

**Comment by DamianEdwards** [comment]
Going to keep this the way it is.
