### ISSUE TITLE
How can I get the DefaultRequestCulture from my CustomRequestCultureProvider?

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Localization#54]
My `RequestLocalizationOptions` are configured like this:

```c#
new RequestLocalizationOptions
{
    // Set options here to change middleware behavior
    SupportedCultures = new List<CultureInfo>
    {
        new CultureInfo("en-US"),
        new CultureInfo("sv-SE")
    },
    SupportedUICultures = new List<CultureInfo>
    {
        new CultureInfo("en-US"),
        new CultureInfo("sv-SE")
    },
    DefaultRequestCulture = new RequestCulture(new CultureInfo("en-US"))
};
```
Then in my custom `IRouter` I need to know the `DefaultRequestCulture`.

If I use
```c#
var requestCultureFeature = Context.GetFeature<IRequestCultureFeature>();
```

then `requestCultureFeature.Provider.Options` is null for my `CustomRequestCultureProvider`?

**Comment by hishamco** [comment]
@marcuslindblom why you need ```DefaultRequestCulture``` in the your custom ```RequestCultureProvider``` while its responsibility to provide a way to determine the culture information. Second thing i'm not sure where you put your code, because the base class ```RequestCultureProvider``` gives us one method to override ```DetermineRequestCulture``` where the requested culture should provider here, have a look to the following
```csharp
    public class MyCustomRequestCultureProvider : RequestCultureProvider
    {
        public override Task<RequestCulture> DetermineRequestCulture([NotNull] HttpContext httpContext)
        {
            var currentCulture = "ar-SA";
            var culture = CultureInfoCache.GetCultureInfo(currentCulture);
            var requestCulture = new RequestCulture(culture);
            return Task.FromResult(requestCulture);
        }
    }
```
the request culture provided from simple variable in the above example, you can provide it from the route if you do so.

**Comment by marcuslindblom** [comment]
@hishamco I determine the current culture based on the url e.g. `/en/a-page`, `/sv/en-sida` and this is how I have set things up.
```c#
var requestLocalizationOptions = new RequestLocalizationOptions
{
    // Set options here to change middleware behavior
    SupportedCultures = new List<CultureInfo>
    {
        new CultureInfo("en-US"),
        new CultureInfo("sv-SE")
    },
    SupportedUICultures = new List<CultureInfo>
    {
        new CultureInfo("en-US"),
        new CultureInfo("sv-SE")
    },
    DefaultRequestCulture = new RequestCulture(new CultureInfo("en-US"))
};

requestLocalizationOptions.RequestCultureProviders.Insert(0, new CustomRequestCultureProvider(async context =>
{
    var requestCulture = requestLocalizationOptions.DefaultRequestCulture;
    string cultureName;
    if (context.Request.Path.DetectCultureSegment(requestLocalizationOptions.SupportedCultures, out cultureName))
    {
        var culture = CultureInfoCache.GetCultureInfo(cultureName);
        requestCulture = new RequestCulture(culture);
    }
    return await Task.FromResult(requestCulture);
}));

app.UseRequestLocalization(requestLocalizationOptions);
```
Now, if a visitor types in the url `/en/a-page` I need to create a proper redirect to `/a-page` to avoid duplicate content and therefore, in this case I need to know if `en-US` is the `DefaultRequestCulture` because it's only then I'll make the redirect.

So, based on that, is it possible for me to request the configuration that I made for `RequestLocalizationOptions` in my `Startup.cs`?

**Comment by hishamco** [comment]
Seems you are working on one of my old suggestions ```DomainRequestCultureProvider``` #43 :smile: 
Your code looks good and there's no need to get ```DefaultRequestCulture``` from the ```CustomRequestCultureProvider```, what you are missing is couple lines of code inside ```app.Use```
```csharp
 var requestCultureFeature = context.GetFeature<IRequestCultureFeature>();
 var requestCulture = requestCultureFeature.RequestCulture;
 if(requestCulture.Culture.Name==requestLocalizationOptions.DefaultRequestCulture.Culture.TwoLetterISOLanguageName)
 {
     // Redirect code goes here ..
     context.Response.Redirect("/a-page"); // according your sample
 }
```

**Comment by marcuslindblom** [comment]
@hishamco Of course, that is a more appropriate place to put the redirect :)

Thanks!

**Comment by hishamco** [comment]
Need to be closed
/cc @Eilon @kirthik

**Comment by hishamco** [comment]
@kirthik can you close this if you don't mind
