### ISSUE TITLE
Remove 'CustomRequestCultureProvider'

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#55]
While we can create a custom culture provider by subclass the ```RequestCultureProvider```, so I think there's no need to have the ```CustomRequestCultureProvider``` implementation out of the box anymore

**Comment by danroth27** [comment]
@DamianEdwards 

The `CustomRequestCultureProvider` is intended to be a light weight option without requiring derivation. We could also consider adding an extension method that allows you to specify a delegate so you don't have to instantiate it directly.

**Comment by hishamco** [comment]
You are right @danroth27, but my intend to remove the heavy lifting from ```Startup.cs``` and isolate it on it's own class such as ``` CookieRequestCultureProvider``` or ```QueryStringRequestCultureProvider``` ... etc
