### ISSUE TITLE
Route localization

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Localization#57]
I was trying to write a culture change middleware which loaded culture from the route data
```
/{language}/{controller}/{action}/{id?}
/en/home/index
/fr/home/index
```
```C#
public async Task Invoke(HttpContext context)
{
    // var controller = RouteData.Values["controller"];
    // var language = RouteData.Values["language"];
    // var action = RouteData.Values["action"];

    await Next(context);
}
```
But I looked through ```HttpContext``` class properties and I could not found any way to reach ```RouteData``` from within ```HttpContext```. Will this localization scenario will be supported in initial release?

**Comment by hishamco** [comment]
You can get the segment from ```Request``` property, also you can have a look to the issue #54, which I solve something like what you are looking for ..

**Comment by Muchiachio** [comment]
Sorry, but I couldn't understand how are you getting culture from just the request path in that issue :disappointed:
Because even ```/en/home/index``` could be mapped to ```{language=fr}/{area}/{controller}/{action}``` and would result in incorrect results then parsed by hand.

**Comment by hishamco** [comment]
If you notice he built an extension method names ```DetectCultureSegment``` that uses ```context.Request.Path``` to get the culture segment

**Comment by Muchiachio** [comment]
Closing per aspnet/mvc#2884.

**Comment by hishamco** [comment]
@Muchiachio why the above the solution doesn't fix you need?

**Comment by Muchiachio** [comment]
> ... you can access the HttpContext from DetermineRequestCulture method.

I can access http context from middleware's invoke method too
```C#
public async Task Invoke(HttpContext context)
{
}
```
but I didn't find how to reach route data from that. And rynowak said it's not possible now.
Or am I missing something?

**Comment by hishamco** [comment]
I told you please have a look to issue #54, or you can use ```QueryStringRequestCulture``` or wait until localization APIs fully integrated with MVC, because you can do a cool stuff such as localize views
