### ISSUE TITLE
[bug] I can't run the unit tests

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#60]
While i'm writing a unit tests for ```RequestCultureProvider``` implementations, I faced an issue when i run **dnx . test** i'm not sure if this happen after react to Dnx renames, nothing but everything still the same after i upgrade the dnvm to the beta7

/cc @DamianEdwards  @kirthik

**Comment by kirthik** [comment]
What error are you seeing?

**Comment by hishamco** [comment]
I got ```NullReferenceException``` at ```Xunit.Runner.Dnx.Program.Main```

**Comment by kirthik** [comment]
Have you tried cleaning up your project? `git clean -xdf` and tried again?

**Comment by hishamco** [comment]
Same thing!!

**Comment by Eilon** [comment]
Show the stack trace. I think this is a known issue right now because the latest xUnit is incompatible with the latest DNX. I think we have a workaround but we're not yet using it everywhere.

**Comment by hishamco** [comment]
I'm facing an issue to discover the unit test in VS 2015 RTM, I just run the tests from the command line, i will try to summarize the error message

**Comment by hishamco** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Runner.Dnx.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

**Comment by Eilon** [comment]
@kirthik can you repro this?

**Comment by kirthik** [comment]
Which feed are you using? I saw this error with aspnetvolatile feed but aspnetvnext feed has the right xunit private packages.

**Comment by hishamco** [comment]
I already run the same command **dnx . test** before and everything was fine, but now it causes an error even after updating the dnvm version

**Comment by kirthik** [comment]
What feed are you using? Can you check you NuGet.Config?

**Comment by hishamco** [comment]
This is the feed **https://www.myget.org/F/xunit/api/v2**

**Comment by kirthik** [comment]
Could you try this and see if you are still getting the error. 
- Clone localization repository
- Add this `<add key="aspnetvnext" value="https://www.myget.org/F/aspnetvnext/api/v2" />` to your    
  `NuGet.config` if you don't have it already
- Run build.cmd.

**Comment by hishamco** [comment]
I can't clone the repo, because there's a PR already requested, any other idea?

**Comment by hishamco** [comment]
BTW I notice this behavior in almost the repos that I clone (if i'm it's not all)

**Comment by hishamco** [comment]
@kirthik it is still blocking me from running unit tests, any workaround for this without clone the repo?

**Comment by DamianEdwards** [comment]
Just clone it into a different folder. Or do it in another branch.

**Comment by hishamco** [comment]
Ok @DamianEdwards but this is the case in almost the local aspnet repos, I thought there's an issue in xUnit

**Comment by kirthik** [comment]
Please try to clean your packages folder -`%userprofile%/.dnx/packages` and your cache - `%localappdata%/dnu/cache` and do a build again

**Comment by hishamco** [comment]
Same thing?!!

**Comment by Eilon** [comment]
Did you also run `git clean -xdf` in the cloned repo?

No one else seems to be hitting this so we're trying to figure out what the differences are between your machine and other peoples' machines.

**Comment by hishamco** [comment]
Yes I already, I notice this after latest dnx changes in the repo, the problem is affect all the unit tests in aspnet repos

**Comment by kirthik** [comment]
What version of `xunit.runner.dnx` do you have in your packages folder and what version of `dnx` are you using?

**Comment by hishamco** [comment]
I'm using the same version that localization repo use, regarding the dnx I upgrade it to 1.0.0-beta7-12274 clr x86

**Comment by kichalla** [comment]
Looks like you have an older version of DNX...after DNX rename breaking changes, you need to have version `1.0.0-beta7-12290` or higher..try again and let us know (also your xunit.runner.dnx should be `2.1.0-beta5-aspnet-2`)

**Comment by hishamco** [comment]
Is that mean I should modify the ```project.json```

**Comment by hishamco** [comment]
@kichalla I upgrade dnx to ```1.0.0-beta7-12302``` also I modify the xunit.runner.dnx in ```project.json``` without luck :(

**Comment by hishamco** [comment]
@kichalla seems xunit runner works after persist and activate the above version, but new exception shows up, let me dig into it and come back to you soon .. thanks @kichalla

**Comment by hishamco** [comment]
Finally It got fixed after I run ```dnu restore``` for all source projects. BTW no need to change the xunit.runner version, upgrading the dnx is enough

Thanks all :smile:
