### ISSUE TITLE
[Bug] QueryStringRequestCultureProvider Issue

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#62]
While i'm writing unit tests for ```RequestCultureProvider``` implementations,  I notice that ```QueryStringRequestCultureProvider```returns ```DefaultRequestCulture``` for the ```RequestLocalizationOptions``` instead of returning a ```RequestCulture``` based on ```UIQueryStringKey``` property.
I will create a PR soon to fix this bug, also I wrote a unit test to validate the scenario. I'm struggling to create another PR today for  ```RequestCultureProvider``` implementations unit tests

**Comment by Eilon** [comment]
@DamianEdwards thoughts? Is this a correct fallback behavior? I would think that defaulting the culture when it wasn't explicitly set seems wrong, but maybe not...

**Comment by hishamco** [comment]
@Eilon according what i know from ASP.NET WebForms, the default ```Culture``` is **en-US** and ```UICulture``` is **en-GB**, nothing but what I have seen in ```QueryStringRequestCultureProvider``` that whenever the ```UIQueryStringKey``` is missing, it assigned the ```QueryStringKey``` value, so I think the same if ```QueryStringKey``` is missing while it doesn't follow the fallback of ASP.NET

**Comment by DamianEdwards** [comment]
I think my original thoughts were that using the format culture as the UI culture was somehow more OK than using the UI culture as the format culture... maybe. That said, I can't think of any science to back that up. In this case, I don't think I really expected the `QueryStringRequestCultureProvider` to be used in production much; I found it useful to enable during development for easy switching between cultures via the URL, and having it set the UI culture based on the format culture was easy.

So, I'm happy to make it set it both ways,

**Comment by DamianEdwards** [comment]
Fixed in c065c90337bf8364abd2e46815e17ba0d31af7c9
