### ISSUE TITLE
Localize DataAnnotations

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Localization#65]
I'm playing around with IStringLocalizer and, being honest, I still don't get all the inner workings but I was able to create a DbStringLocalizer (and a DbStringLocalizerFactory) that get the strings from my app Db.

What I am failing to see is how can I make my custom string localizer for Data Annotations.
Since strings comes from the db I don't have/want a concrete type to use as a ResourceType.

Is there any built-in or plan to support this kind of scenario? I'm not using a ResourceManager, should I? What's the extensibility point for this (if any)? Any guidance will be really appreciated. Thanks.

**Comment by hishamco** [comment]
Data Annotation is already mentioned in the issue #31
