### ISSUE TITLE
custom IStringLocalizer requires custom StringLocalizerFactory for DI.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Localization#66]
I were wondering if this is the intended behavior, some misconfiguration on my side or a bug so I decided to create an issue.

As of right now (beta7), If I plug my custom StringLocalizer into de DI container like this:
```
services.AddTransient<IStringLocalizer, DbStringLocalizer>();
```
it's not used. (I tried placing it before and after `services.AddLocalization();` in case order matters.

For the framework to actually use my own StringLocalizer I had to implement a StringLocalizerFactory and registering as:
```
 services.AddSingleton<IStringLocalizerFactory, DbStringLocalizerFactory>();
```

In the later, my StringLocalizer is used flawlessly. Is this by design?

Another thing I don't quite understand is that the Create on IStringLocalizerFactory accepts `Type` or `baseName` and `location` to load assembly. I'm pretty sure this is for resources being types. In my case, I was using Database so there's no 'type' involved, which makes it awkward to implement a Create(Type..) with no use. There are high chances I'm doing something wrong, so sorry if that's the case.

**Comment by hishamco** [comment]
If i'm not getting you wrong, you can use ```CustomRequestCultureProvider``` to get the localized string from Database. Have a look to issue #54, perhaps it give you a glimpse to what you wanna do

**Comment by Bartmax** [comment]
I don't see how the `CustomRequestCultureProvider` can be used to get localized strings from the DB. Isn't that for custom ways to detecting the culture? (like via domain or some other mechanisms) ?

**Comment by hishamco** [comment]
Exactly .. Let me know if you need a help

**Comment by Bartmax** [comment]
Well, actually what I'm trying to do is load my String from a database instead of resources. The culture 'detector' is fine using header, cookie, query, etc.

Do you think that I should use another approach? using `CustomRequestCultureProvider` ? I don't see how.

This is my current *wip* implementation of StringLocalizer:

```
 public class DbStringLocalizerFactory : IStringLocalizerFactory
    {
        private readonly ApplicationDbContext _db;

        public DbStringLocalizerFactory(ApplicationDbContext db)
        {
            _db = db;
        }
        public IStringLocalizer Create(Type resourceSource)
        {
            return new DbStringLocalizer(_db);
        }

        public IStringLocalizer Create(string baseName, string location)
        {
            return new DbStringLocalizer(_db);
        }
    }

public class DbStringLocalizer : IStringLocalizer
    {
        private readonly ApplicationDbContext _db;
        private string _cultureName;

        public DbStringLocalizer(ApplicationDbContext db) : this(db, CultureInfo.CurrentUICulture) { }

        public DbStringLocalizer(ApplicationDbContext db, CultureInfo cultureInfo)
        {
            _db = db;
            _cultureName = cultureInfo.Name;
        }

        public LocalizedString this[string name]
        {
            get
            {
                var value = GetString(name);
                return new LocalizedString(name, value ?? name, resourceNotFound: value == null);
            }
        }

        public LocalizedString this[string name, params object[] arguments]
        {
            get
            {
                var format = GetString(name);
                var value = string.Format(format ?? name, arguments);
                return new LocalizedString(name, value, resourceNotFound: format == null);
            }
        }

        private string GetString(string name)
        {
            var query = _db.Localizations.Where(l => l.Culture == _cultureName);
            var value = query.FirstOrDefault(l => l.Key == name);
            return value?.Value;
        }

        public IStringLocalizer WithCulture(CultureInfo culture)
        {
            return new DbStringLocalizer(_db, culture);
        }
        public IEnumerable<LocalizedString> GetAllStrings(bool includeAncestorCultures)
        {
            return _db.Localizations.Where(l => l.Culture == _cultureName)
                .Select(l=> new LocalizedString(l.Key, l.Value, true));
        }
    }

```

**Comment by hishamco** [comment]
Oops, may I miss understood :( , ```CustomRequestCultureProvider``` is used to provide the culture from custom source such a database, domain .. etc.
Regarding loading the values themselves i'm not quite sure that's available out of the box right now, what I now is Resources is still in progress, @DamianEdwards correct me if I'm wrong

**Comment by DamianEdwards** [comment]
Yes, you need to provide an `IStringLocalizerFactory` into DI, that produces `IStringLocalizer`. The factory pattern is common throughout ASP.NET as it allows a singleton to be registered in DI.

As for the overloads, you can have your custom `IStringLocalizer` simply implement the overload that takes `Type` by calling into your implementation that takes `string baseName, string location` by passing in `Type.FullName` as `baseName`.

**Comment by Bartmax** [comment]
:+1: thank you.

**Comment by c1rus** [comment]
Im also trying to get strings from database. Is it safe to store instance of `DbContext` in singleton (`StringLocalizerFactory`)? How can i pass instance of DbContext to `IStringLocalizer`?

**Comment by hishamco** [comment]
@Bartmax  @c1rus this PR #149 may let you interest

**Comment by c1rus** [comment]
Hmm, but you are not using DI to inject ```DbContext```... And you store instance of ```DbContext``` in singleton, should it not be disposed?

I solved it by changing ```IStringLocalizerFactory``` to be scoped instead of singleton.

**Comment by hishamco** [comment]
I inject it before i made the PR, but to make the sample simplistic i used ```IStringLocalizerFactory``` as singleton

**Comment by drauch** [comment]
@DamianEdwards : we have a more complicated setup where we want to load the values from the database only for some cultures, others are in resource files. I cannot see how to support this setup with IStringLocalizerFactory / IStringLocalizer, as the IStringLocalizerFactory.Create() method does not receive the culture as input. How to obtain the currently selected culture from within my own IStringLocalizerFactory implementation?

**Comment by hishamco** [comment]
@drauch could please file a new issue to organize the tracking of your question
