### ISSUE TITLE
[Bug] Unable to run Localization Sample

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#76]
When I run the localization sample I got the following exception **Could not resolve a service of type 'Microsoft.Framework.Localization.IStringLocalizer`1[[LocalizationSample.Startup, LocalizationSample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' for the parameter 'SR' of method 'Configure' on type 'LocalizationSample.Startup'.**

**Comment by kirthik** [comment]
PR https://github.com/aspnet/Localization/pull/77 should fix that issue

**Comment by hishamco** [comment]
Thanks @kirthik

**Comment by kirthik** [comment]
merged 06aa241
