### ISSUE TITLE
Make 'reset link' reset both Cookie & QueryString

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#84]
Reset button should reset both cookie & query string instead of cookie only, the code snippet will be something like
```javascript
function clearQueryString() {
     document.window.href = '/';
}
```
and call both ```clearCookie``` and ```clearQueryString``` in the reset link

**Comment by Eilon** [comment]
If this is just for the sample, there's not much incentive to improve it. It's just to show how some features are used, the UI itself is not a concern.
