### ISSUE TITLE
Still local resource is loaded incorrectly

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Localization#86]
When runtime  beta8 15598 is used:
![resx_not_work](https://cloud.githubusercontent.com/assets/6814395/9956818/2da80b7e-5e2e-11e5-9432-6f4cb5d7d04a.png)

When runtime beta8 15618 is used:
![resx_not_work_15618](https://cloud.githubusercontent.com/assets/6814395/9956888/abfd851c-5e2e-11e5-8919-675ba09a667e.png)

Exception thrown: 'System.InvalidOperationException' in Microsoft.Dnx.ApplicationHost.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Dnx.Host.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in AspNet.Loader.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll

**Comment by hishamco** [comment]
@xatabhk it works fine in my end. Are you sure you running the latest bits?

**Comment by xatabhk** [comment]
It worked on beta 7 or earlier where resources were all in one DLL, but not on latest builds from https://www.myget.org/F/aspnetlitedev/.

**Comment by hishamco** [comment]
@xatabhk can you let me the steps to reproduce it?

**Comment by Eilon** [comment]
@kirthik can you help investigate?

**Comment by kirthik** [comment]
@xatabhk : Are you running this from VS? We don't have the support yet for loading resources from VS (https://github.com/aspnet/dnx/issues/2727). Can you please try running it from command line? - Run `dnx web` and access the website. You should see the correct locale text displayed for "Hello". Please let me know if that is not the case.

**Comment by xatabhk** [comment]
Yes. I am running the sample from VS IDE. I will try it from command line soon.

**Comment by hishamco** [comment]
@xatabhk did you get the expected result when you run it from command line, it's fine at my end

**Comment by xatabhk** [comment]
I tested the sample from command line; it did work fine. I hope it can work in IIS Express and IIS soon.

**Comment by Eilon** [comment]
Closing for now. You can follow the status of https://github.com/aspnet/dnx/issues/2727 to see when this works from non-command-line scenarios. Thanks!

**Comment by hishamco** [comment]
Thanks @Eilon
