### ISSUE TITLE
Create .resx files runtime + add strings to it

### ISSUE THREAD

**Issue by miroslavsiska** [aspnet/Localization#87]
I cant found any possibility to create translations via app code. Its important to have in localization some possibilities to add new languages and strings on runtime.
I mean with it:
Create .resx dynamically via C# code and add localized strings to this .resx file. It is important for each translated modular app.

**Comment by hishamco** [comment]
Have a look to this https://msdn.microsoft.com/en-us/library/gg418542%28v=vs.110%29.aspx

**Comment by Eilon** [comment]
If you need support *at runtime* then RESX is probably not a good solution. RESX is a compile-time resource definition.

With the new localization features in ASP.NET / DNX, I recommend writing a custom resource provider that works with whatever storage medium you have - perhaps a TXT file, a PO file, a database, or something else.

Have a look at how the default implementation in https://github.com/aspnet/Localization/tree/dev/src/Microsoft.Framework.Localization implements what's in https://github.com/aspnet/Localization/tree/dev/src/Microsoft.Framework.Localization.Abstractions to see how the concepts work together.

**Comment by hishamco** [comment]
@Eilon can you check the links, seems something wrong

**Comment by Eilon** [comment]
Fixed links, thanks.
