### ISSUE TITLE
[Bug] Omit the DefaultRequestCulture should not throw NullReferenceException

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#88]
While I'm trying to fix the issue #70 I come up with the case that throws ```NullReferenceException``` when ```DefaultRequestCulture``` is not defined. The exception occurs from this line of code https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNet.Localization/AcceptLanguageHeaderRequestCultureProvider.cs#L60

**Comment by Eilon** [comment]
@kirthik if the PR looks good to you, please resolve this issue.

**Comment by kirthik** [comment]
How can `DefaultRequestCulture` be `null`? By default it is  set to current culture.

**Comment by Eilon** [comment]
`ValidateRequestCulture` might return `null`?

**Comment by hishamco** [comment]
In fact support both SupportedCultures & SupportedUICultures while omit the ```DefaultRequestCulture``` cause the error, I tested in my end. Please verify by running the test

**Comment by kirthik** [comment]
merged 61106d36a17239d60ccd4cb6e0257a267d9f32ba
