### ISSUE TITLE
ResourceStringLocalizerFactory creates string localizer based on resourcetype's name instead of full name

### ISSUE THREAD

**Issue by kirthik** [aspnet/Localization#90]
https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizerFactory.cs#L53

We should use resourceName.FullName so that if same class exists under different namespaces, we can have different `.resx` for each type.

**Comment by Eilon** [comment]
@DamianEdwards thoughts?

**Comment by DamianEdwards** [comment]
It used to be `FullName` but was changed in eefe518ac2f58832413efe2ba6deeae7b692952e. If we use `FullName` again, then the resource name would become `ApplicationName + _resourcesBasePath + type.FullName`, yes?

**Comment by kirthik** [comment]
Yes. That is correct.

**Comment by DamianEdwards** [comment]
OK.
