### ISSUE TITLE
Make 'ResourceManagerStringLocalizer' overload internal

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#92]
After the PR #91 and while we have InternalsVisibleTo in this line of https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Framework.Localization/Properties/AssemblyInfo.cs#L8, it will be nice to modify the access modifier for ResourceManagerStringLocalizer in https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Framework.Localization/ResourceManagerStringLocalizer.cs#L49 to internal rather than public because the intend for this overload to be used for testing purpose only
/cc @kirthik

**Comment by Eilon** [comment]
It could be useful for other people testing outside of this assembly. This is probably fine as-is.

**Comment by hishamco** [comment]
I'm still wondering why it should be ```public```, while ```internal``` is a proper access specifier?!!

**Comment by Eilon** [comment]
Because if it's internal then other assemblies that don't have an InternalsVisibleTo relationship with it won't be able to use it.

**Comment by hishamco** [comment]
Of course @Eilon, but while the intend is for testing purpose, the ```InternalsVisibleTo``` is already there for the testing project that use it. Am I right?

**Comment by hishamco** [comment]
@DamianEdwards thoughts?

**Comment by Eilon** [comment]
IVT is only useful for the target assembly. If a random person with a random assembly wants to call the method, it must be public.

**Comment by hishamco** [comment]
Yep, but while it located in ```Microsoft.Framework.Localization``` and almost the cases the dev deal with ```Microsoft.AspNet.Localization``` so ```internal``` still a valid option. I hope to hear opinions from other guys.
thanks @Eilon

**Comment by Eilon** [comment]
This is the pattern we use almost everywhere in ASP.NET 5 and EF 7. If our own framework needs this, then we assume that others will need this.

**Comment by hishamco** [comment]
Thanks for this clarification @Eilon
