### ISSUE TITLE
Rename Microsoft.Framework.* to Microsoft.Extensions.*

### ISSUE THREAD

**Issue by Eilon** [aspnet/Localization#93]
Need to rename assemblies and namespaces from `Microsoft.Framework.*` to `Microsoft.Extensions.*`.

Once the change is committed, please post an issue in the https://github.com/aspnet/Announcements/issues/ repo that links back to this issue.

**Comment by hishamco** [comment]
@Eilon is there a proper reason for this change?

**Comment by Eilon** [comment]
We didn't like the old name.

**Comment by hishamco** [comment]
Nothing but localization is framework specific, one more thing is this implies to change the name in other repos suck as Logging and so on?!!

**Comment by Eilon** [comment]
All `Microsoft.Framework.*` is getting renamed to `Microsoft.Extensions.*`.

**Comment by pranavkm** [comment]
f782d8845ccd9cea54158d86ddc9a570c91828c0
