### ISSUE TITLE
CultureInfoCache.GetCultureInfo makes a case sensitive comparison

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Localization#95]
For example, when using query string to set culture
1. `http://localhost:5000/Loc/?culture=fr&ui-culture=fr`
2. `http://localhost:5000/Loc/?culture=FR&ui-culture=FR`

I would expect both the cases to work. But currently the 2nd case doesn't work.

cc' @DamianEdwards @kirthik

**Comment by hishamco** [comment]
Sure because ```CultureInfoCache.GetCultureInfo``` behind the scene looking for the supplied culture into ```CultureInfoCache.KnownCultureNames``` HashSet

**Comment by hishamco** [comment]
This can be solved by using the overload 
```csharp
 public static readonly HashSet<string> KnownCultureNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
```
in line https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Framework.Globalization.CultureInfoCache/CultureInfoList.cs#L22

**Comment by hishamco** [comment]
Your thoughts @DamianEdwards?

**Comment by hishamco** [comment]
@kirthik can you have a look to the bug and the fix that I made

**Comment by kirthik** [comment]
Please address @Eilon's comment - https://github.com/aspnet/Localization/pull/96/files#r41166078. The cultures that got added should be removed.

**Comment by hishamco** [comment]
Oops I didn't notice the @Eilon comment, these cultures have been added after i ran ```CultureInfoGenerator``` command, now I will remove them
thanks

**Comment by kirthik** [comment]
merged 722fbc4ef5b7231b2bbb171dbb1a2d9794cf8eb3

**Comment by Eilon** [comment]
@hishamco but where did they come from? Which OS are you running? I talked to @DamianEdwards and we were a bit surprised that there are hundreds of new cultures listed.

**Comment by hishamco** [comment]
@Eilon i'm running Windows 10, if you want me to dig about this, let me know and i will debug the ```CultureInfoGenerator```

**Comment by Eilon** [comment]
@kirthik @DamianEdwards can one of you run the generator on your own Win10 machine to see if you get similar results? We may very well need to update the list of cultures...

**Comment by Eilon** [comment]
Actually, I opened https://github.com/aspnet/Localization/issues/98 to track the potential update.

**Comment by hishamco** [comment]
Thanks @Eilon, I will dig into that too
