### ISSUE TITLE
[Bug] Unable to run Localization Sample & Unit Tests

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#97]
After that latest commit by @pranavkm the sample can't locate few packages 
![capture](https://cloud.githubusercontent.com/assets/3237266/10265498/c28a6408-6a3b-11e5-86c0-d6038cabfff3.JPG)

BTW I upgrade the dnvm before I run ```dnu restore``` command
/cc @kirthik

**Comment by Eilon** [comment]
The build hadn't yet gone through so the packages were temporarily missing. Once the build goes through the packages will be available.

**Comment by hishamco** [comment]
The sample running fine now, but still there's an issue while running the unit tests?!!

**Comment by hishamco** [comment]
@Eilon currently when I run both sample and test project I got this exception The type ```IApplicationBuilder``` couldn't be found, furthermore the sample run but when i hit the url I got internal server error, any idea about this
/cc @kirthik

**Comment by Eilon** [comment]
That sounds like a version mismatch on the machine.

**Comment by hishamco** [comment]
Let me upgrade to the latest ```dnmv``` version

**Comment by hishamco** [comment]
Got fixed :smile:

**Comment by hishamco** [comment]
@Eilon after I removed the changes for the PR #101, fetch the latest changes and upgrade dnvm to 1.0.0-beta8-15604 clr I got **Could not load type 'Microsoft.Dnx.Runtime.PlateformServices'** exception when I run the localization sample. Any idea?!!
