### ISSUE TITLE
Update list of cultures to be current with a recent Win10 installation

### ISSUE THREAD

**Issue by Eilon** [aspnet/Localization#98]
Need to rerun the culture generator on a recent Win10 machine to ensure we have all the latest cultures.

**Comment by hishamco** [comment]
I'm running Windows 10 Enterprise, the .NET release key **393295** there are **809** cultures, I think we should consider the newly added culture that have been remove based on @Eilon comment in  https://github.com/aspnet/Localization/pull/96/files#r41166078

**Comment by DamianEdwards** [comment]
OK yep, I confirmed it. I just ran it here on Windows 10 Pro RTM and it updates to over 800 cultures.

@hishamco, feel free to send a PR that just includes the culture list update, assuming you are running Windows 10 **RTM** (build 10240).

**Comment by hishamco** [comment]
@DamianEdwards I'm running the same version, I will send a PR soon
thanks

**Comment by Kagamine** [comment]
@Eilon It seems that something missed by using the tool. #104

**Comment by hishamco** [comment]
Nope, this is auto generated by the ```CultureInfoGenerator``` command which is fetch all the cultures from the OS

**Comment by kirthik** [comment]
Based on the discussion in this PR - https://github.com/aspnet/Localization/pull/104 it looks like other OSes have valid cultures which we need to add to our list or come up with a smarter way to identifying known cultures.

**Comment by Eilon** [comment]
No longer needed due to https://github.com/aspnet/Localization/issues/111
